### ISSUE TITLE
Livepatch modules can't be disassembled

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#1009]
kpatch-patch modules can't be disassembled by objdump and other tools.  With more recent toolchains like RHEL8, even gdb and crash can't disassemble them either.

objdump: ./usr/lib/kpatch/4.18.0-74.el8.x86_64/kpatch-4_18_0-74-1-0_test.ko: bad value

The problem is the .klp.rela.arch sections:

Relocation section [38] '.klp.rela.vmlinux..text.cmdline_proc_show' for section [ 9] '.text.cmdline_proc_show' at offset 0x29b0 contains 1 entry:
  Offset              Type            Value               Addend Name
  0x0000000000000009  X86_64_PC32     000000000000000000      -4 .klp.sym.vmlinux.saved_command_line,0

.text.cmdline_proc_show already has another rela section: .rela.text.cmdline_proc_show.  So libbfd doesn't like that.

Some ideas:

1) Make the .klp.rela sections PROGBITS instead of RELA.

2) Put the klp relas in .rela.text.cmdline_proc_show.  This would require ensuring that the kernel always preserves that section (or those relas) after doing the normal relocations.  We would also have to get the patched object (.e.g "vmlinux") information some other way way.

3) Teach libbfd to ignore it somehow (assuming this is the only source of all the different tools' confusion).

**Comment by joe-lawrence** [comment]
Reported to binutils a few months back without resolution:

- binutils BZ:  https://sourceware.org/bugzilla/show_bug.cgi?id=24456
- binutils mailing list thread; https://www.mail-archive.com/bug-binutils@gnu.org/msg30761.html

**Comment by joe-lawrence** [comment]
@nickclifton fixed this for us a while back.

Looking through the binutils-gdb commit log, I think these were the two main commits that added support for secondary relocation sections:

commit [a7ba389645d178c43100ec47e513389ae8bf8f93](https://github.com/bminor/binutils-gdb/commit/a7ba389645d178c43100ec47e513389ae8bf8f93)
Author: Nick Clifton <nickc@redhat.com>
Date:   Fri Aug 23 13:22:02 2019 +0100

    Stop the BFD library from failing when encountering a second set of relocs for the same section.

commit [a8e14f4cc2badfcf959f5e2cc57a941dc43f72d4](https://github.com/bminor/binutils-gdb/commit/a8e14f4cc2badfcf959f5e2cc57a941dc43f72d4)
Author: Nick Clifton <nickc@redhat.com>
Date:   Thu Mar 5 15:47:15 2020 +0000

    Add support for ELF files which contain multiple reloc sections which all target the same section.

And so users will want to upgrade (upstream) binutils:
```
% git tag --contains a8e14f4cc2badfcf959f5e2cc57a941dc43f72d4
binutils-2_35
``` 
Fixes have already been backported to current kpatch-supported RHEL releases.

@nickclifton is the above accurate?

**Comment by nickclifton** [comment]
Hi Joe,

> Looking through the binutils-gdb commit log, I think these were the two main commits that added support for secondary relocation sections:
> 
> commit a7ba389645d178c43100ec47e513389ae8bf8f93> commit a8e14f4cc2badfcf959f5e2cc57a941dc43f72d4

> @nickclifton <https://github.com/nickclifton> is the above accurate?

Yes.  There is also this commit which fixes a performance degradation
introduced by the second commit above.  It only works for binaries
which do not use secondary relocs however, so it may not be of 
interest to you:

  commit 44466e45c51b1c68ed2f95f86bcdb1f18f08b380 
  Apply a workaround to mitigate a quadratic performance hit in
  the linker when writing out secondary reloc sections.

(This commit is only in the GNU Binutils mainline development sources
at the moment.  It has not been backported to RHEL).

Cheers
  Nick

**Comment by joe-lawrence** [comment]
Thanks, Nick.  I'll consider this issue closed.
