### ISSUE TITLE
Older gcc versions do not understand "-gz=none"

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1012]
As seen on a RHEL7.6 test system (gcc version 4.8.5):
```
cc1: error: unrecognised debug output level "z=none"
```
commit fe6e3f51bfe17945 ("create-diff-object: disable DWARF compression explicitly") added this option to KCFLAGS to fix #877, but it looks like we need to be gcc-version specific about adding it.

**Comment by steils** [comment]
Sorry, I didn't think about that.
