### ISSUE TITLE
testmod/doit.sh script failure with wrong parameters.

### ISSUE THREAD

**Issue by CentUser** [dynup/kpatch#1017]
After successfully install kpatch, I went to test/testmod, and found doit.sh. Following the instructions found in the dir, I executed the script but got the following Error:

make: `testmod.ko' is up to date.
+ ../../kpatch-build/create-diff-object testmod_drv.o.orig testmod_drv.o.patched testmod.ko output.o
Usage: create-diff-object [OPTION...]
            original.o patched.o parent-name parent-symtab Module.symvers
            patch-module-name output.o

seems like doit.sh is calling create-diff-object with wrong parameters. 

I am now not familiar with this prog, inspecting on it...

**Comment by CentUser** [comment]
Oh, I fogot to post the code version: master , commit: c4fafedf3bb9ead4edc8fad63c1655da83003d44

**Comment by joe-lawrence** [comment]
I don't think we've kept `test/testmod` very up to date and this point I would suggest that we just deprecate and remove it.

**Comment by jpoimboe** [comment]
Agreed, it hasn't been used in 5 years, somebody can just remove it.

**Comment by CentUser** [comment]
> Agreed, it hasn't been used in 5 years, somebody can just remove it.

WoW, had been run into some relics...

But is there any way to test the kpatch build?
