### ISSUE TITLE
don't allow jump labels: causes error in simple patch

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#1021]
Hello,

after upgrading to 0.7.1 i'm getting the following error:

```
...
Extracting new and modified ELF sections
/usr/lib/kpatch/create-diff-object: ERROR: oom_kill.o: kpatch_regenerate_special_section: 2109: Found a jump label at out_of_memory()+0x10a, using key cpusets_enabled_key.  Jump labels aren't currently supported.  Use static_key_enabled() instead.
```

Patch:
```
diff --git a/mm/oom_kill.c b/mm/oom_kill.c
index dbddb7a40..a581fe2a2 100644
--- a/mm/oom_kill.c
+++ b/mm/oom_kill.c
@@ -1089,9 +1089,10 @@ bool out_of_memory(struct oom_control *oc)
         * The OOM killer does not compensate for IO-less reclaim.
         * pagefault_out_of_memory lost its gfp context so we have to
         * make sure exclude 0 mask - all other users should have at least
-        * ___GFP_DIRECT_RECLAIM to get here.
+        * ___GFP_DIRECT_RECLAIM to get here. But mem_cgroup_oom() has to
+        * invoke the OOM killer even if it is a GFP_NOFS allocation.
         */
-       if (oc->gfp_mask && !(oc->gfp_mask & __GFP_FS))
+       if (oc->gfp_mask && !(oc->gfp_mask & __GFP_FS) && !is_memcg_oom(oc))
                return true;
 
        /*
```

This one was building / working fine on 0.6.X.

I wasn't able to find any doc about how to fix this. I didn't find cpusets_enabled_key in oom_kill.c now i did found docs to use static_key_enabled

**Comment by disaster123** [comment]
I don't find any usage of cpusets_enabled_key in oom_kill.c

**Comment by joe-lawrence** [comment]
(Using a 5.2-rcX kernel build I had laying around...)

Find cpusets_enabled_key in the relocations for the .jump_table section:
```
% readelf --wide --relocs oom_kill.o
Relocation section '.rela__jump_table' at offset 0x60668 contains 24 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
  [ ... snip ... ]
0000000000000070  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 230b
0000000000000074  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 24ac
0000000000000078  0000014700000018 R_X86_64_PC64          0000000000000000 cpusets_enabled_key + 0
```
On x86_64, the [jump_entry](https://elixir.bootlin.com/linux/latest/source/include/linux/jump_label.h#L122) relocations come in sets of three:

1. code - where in the code to patch a NOP/jump
2. target - where does non-default code live, ie where to jump
3. key - the static key symbol

Use that info to find out where the code and target point to:
```
% objdump -j .text -D oom_kill.o | awk '/^[0-9a-z]* <.*>:/{fun = $2} /\<230b\>:/ || /\<24ac\>:/{print fun $0}'
<out_of_memory>:    230b:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<out_of_memory>:    24ac:       8b 7a 50                mov    0x50(%rdx),%edi
```
The relocations confirm that oom_kill.o :: out_of_memory() is the location of the jump_entry code and target.

Using `objdump -j .text -DS oom_kill.o`, we can see the C code of the jump_entry target:
```
static inline bool __cpuset_zone_allowed(struct zone *z, gfp_t gfp_mask)
{
        return __cpuset_node_allowed(zone_to_nid(z), gfp_mask);
    24ac:       8b 7a 50                mov    0x50(%rdx),%edi
```
and then run that through [cscope](http://cscope.sourceforge.net/) to come up with call-chain from out_of_memory() to the static key:
```
mm/oom_kill.c :: bool out_of_memory()
  oc->constraint = constrained_alloc(oc);

mm/oom_kill.c :: static enum oom_constraint constrained_alloc()
  if (!cpuset_zone_allowed(zone, oc->gfp_mask))

include/linux/cpuset.h :: static inline bool cpuset_zone_allowed()
  return __cpuset_zone_allowed(z, gfp_mask);

include/linux/cpuset.h :: static inline bool cpusets_enabled()
  return static_branch_unlikely(&cpusets_enabled_key);
```
The non-obvious part here is that all of this call-chain must have been inlined by the compiler into out_of_memory().

**Comment by disaster123** [comment]
Ouch thanks. This might be a good example for the author guide.
Sontheim question is how to avoid / work around this?

**Comment by joe-lawrence** [comment]
Using static_branch_(un)likely() will produce code that may be later patched by jump labels.  (See their non-intuitive defintions in [jump_label.h](https://elixir.bootlin.com/linux/latest/source/include/linux/jump_label.h#L395).)

Unfortunately kpatch-build (and the kernel) doesn't fully support jump_labels in livepatch modules, so the current workaround is to use [static_key_enabled()](https://elixir.bootlin.com/linux/latest/source/include/linux/jump_label.h#L384) checks instead -- those will compile to code that always checks static key values instead of relying upon runtime-patched jump_labels.

In this case, I think the workaround would be to create a new, private call-chain just for out_of_memory() to cpusets_enabled().   The kpatch would need to include:
```
mm/oom_kill.c :: bool out_of_memory()
  mm/oom_kill.c :: static enum kpatch_oom_constraint constrained_alloc()
    mm/oom_kill.c :: static inline kpatch_bool cpuset_zone_allowed()
      mm/oom_kill.c :: static inline kpatch_bool cpusets_enabled()
      {
        return static_key_enabled(&cpusets_enabled_key)
      }
```
This will add a few more functions to the kpatch, but keep the cpusets_enabled() change localized  to out_of_memory().  Rebuilding with a modified cpuset.h could cause a lot of collateral changes which would have included many more functions into your kpatch that you don't want.

Hopefully that will generate a single relocation for the cpusets_enabled_key "key" member and not the other (unsupported) code / target members.

**Comment by disaster123** [comment]
Thanks a lot for your details and explanation.

Isn't something like this enough?
```
diff --git a/include/linux/cpuset.h b/include/linux/cpuset.h
index 934633a05..01a991307 100644
--- a/include/linux/cpuset.h
+++ b/include/linux/cpuset.h
@@ -33,9 +33,10 @@
  */
 extern struct static_key_false cpusets_pre_enable_key;
 extern struct static_key_false cpusets_enabled_key;
-static inline bool cpusets_enabled(void)
+
+static noinline bool cpusets_enabled(void)
 {
-       return static_branch_unlikely(&cpusets_enabled_key);
+       return static_key_enabled(&cpusets_enabled_key);
 }
 
 static inline void cpuset_inc(void)
```

```
oom_kill.o: new function: cpusets_enabled
oom_kill.o: changed function: out_of_memory
```

**Comment by disaster123** [comment]
The following seems to work:
```
diff --git a/include/linux/cpuset_kpatch.h b/include/linux/cpuset_kpatch.h
new file mode 100644
index 000000000..3b20934d4
--- /dev/null
+++ b/include/linux/cpuset_kpatch.h
@@ -0,0 +1,13 @@
+#include <linux/cpuset.h>
+
+static inline bool kpatch_cpusets_enabled(void)
+{
+       return static_key_enabled(&cpusets_enabled_key);
+}
+
+static inline bool kpatch_cpuset_zone_allowed(struct zone *z, gfp_t gfp_mask)
+{
+       if (kpatch_cpusets_enabled())
+               return __cpuset_zone_allowed(z, gfp_mask);
+       return true;
+}
diff --git a/mm/oom_kill.c b/mm/oom_kill.c
index a581fe2a2..3033ce118 100644
--- a/mm/oom_kill.c
+++ b/mm/oom_kill.c
@@ -29,6 +29,7 @@
 #include <linux/timex.h>
 #include <linux/jiffies.h>
 #include <linux/cpuset.h>
+#include <linux/cpuset_kpatch.h>
 #include <linux/export.h>
 #include <linux/notifier.h>
 #include <linux/memcontrol.h>
@@ -300,7 +301,7 @@ static enum oom_constraint constrained_alloc(struct oom_control *oc)
        /* Check this allocation failure is caused by cpuset's wall function */
        for_each_zone_zonelist_nodemask(zone, z, oc->zonelist,
                        high_zoneidx, oc->nodemask)
-               if (!cpuset_zone_allowed(zone, oc->gfp_mask))
+               if (!kpatch_cpuset_zone_allowed(zone, oc->gfp_mask))
                        cpuset_limited = true;
 
        if (cpuset_limited) {
```

**Comment by disaster123** [comment]
Would it be possible to print the call chain directly by kpatch-build? This would make this so much easier.

**Comment by joe-lawrence** [comment]
> Would it be possible to print the call chain directly by kpatch-build? This would make this so much easier.

That would be really nice, but I don't know of any off-the-shelf programmatic way to generate arbitrary call chain reports.  (Let us know if you find one!)

GCC can tell you more about its inlining decisions if you build with -fdump-ipa-clones.  It will leave behind *.ipa-clones files that you can feed through an analysis tool.  For example:

- Using https://github.com/marxin/kgraft-analysis-tool
- Tell me about kernel/module.c :: __mod_update_bounds()

```
% ./kgraft-ipa-analysis.py \
	--symbol=__mod_update_bounds \
	<(echo /usr/src/kernels/4.18.0-80.4.el8.test.ppc64le-ipaclones/kernel/module.c.000i.ipa-clones)

Parsing file (1/1): /usr/src/kernels/4.18.0-80.4.el8.test.ppc64le-ipaclones/kernel/module.c.000i.ipa-clones
Function: __mod_update_bounds/3270 (kernel/module.c:240:13) [REMOVED] [object file: /usr/src/kernels/4.18.0-80.4.el8.test.ppc64le-ipaclones/kernel/module.c.000i.ipa-clones]
  inlining to: mod_update_bounds/3271 (kernel/module.c:251:13) [REMOVED] [edges: 2]
    inlining to: add_unformed_module/3521 (kernel/module.c:3563:12) [REMOVED]
      inlining to: load_module/3526 (kernel/module.c:3661:12)

  Affected functions: 3
    mod_update_bounds/3271 (kernel/module.c:251:13) [REMOVED]
    add_unformed_module/3521 (kernel/module.c:3563:12) [REMOVED]
    load_module/3526 (kernel/module.c:3661:12)
```

**Comment by jpoimboe** [comment]
@disaster123, while kpatch-build is deceptively easy to use, patching the kernel is a delicate operation and patch modules should really only be created by kernel engineers.  If some of this stuff is over your head, TBH, you might want to reconsider whether it makes sense to be live patching your kernel in the first place.

**Comment by disaster123** [comment]
Yes you're right. Mainly i'm able to read and understand what the patch does and if need it in our infrastructure but i haven't cared about the internals - i just thought kpatch will prevent me doing bad things.

**Comment by disaster123** [comment]
Might you be able to tell what this mans?
"/usr/lib/kpatch/create-diff-object: ERROR: tcp_timer.o: kpatch_regenerate_special_section: 2109: Found a jump label at
 tcp_retransmit_timer()+0xdd, using key descriptor.58171.  Jump labels aren't currently supported.  Use static_key_enabled() instead."

it's called key descriptor.58171 - which isn't an enabled key like above. Also an objdump of tcp_timer doesn't show anything?
```
# objdump -j .text -DS /root/.kpatch/tmp/patched/net/ipv4/tcp_timer.o

/root/.kpatch/tmp/patched/net/ipv4/tcp_timer.o:     file format elf64-x86-64
```

**Comment by jpoimboe** [comment]
Hm, 'descriptor' is probably a special case for which we can remove the error.  It's used to enable dynamic debug printks.

**Comment by disaster123** [comment]
ah perfect - that would be great. If i can test a patch i would be happy todo so.

**Comment by jpoimboe** [comment]
https://github.com/jpoimboe/kpatch/commit/14240616a3a09c52c96b10bfb504890ad97a4831

**Comment by joe-lawrence** [comment]
@jpoimboe : fwiw, readelf reports those key symbols offset from "__verbose" on my 5.2 build:
```
% readelf --wide --relocs net/ipv4/tcp_timer.o | awk '/jump_table/' RS="\n\n" ORS="\n\n"
Relocation section '.rela__jump_table' at offset 0x52210 contains 21 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000000  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 601
0000000000000004  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 62e
0000000000000008  0000005d00000018 R_X86_64_PC64          0000000000000000 memcg_sockets_enabled_key + 0
0000000000000010  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 63a
0000000000000014  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 6a7
0000000000000018  0000006800000018 R_X86_64_PC64          0000000000000000 memory_cgrp_subsys_on_dfl_key + 1
0000000000000020  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 852
0000000000000024  0000000100000002 R_X86_64_PC32          0000000000000000 .text + d21
0000000000000028  0000001600000018 R_X86_64_PC64          0000000000000000 __verbose + 98
0000000000000030  0000000100000002 R_X86_64_PC32          0000000000000000 .text + b38
0000000000000034  0000000100000002 R_X86_64_PC32          0000000000000000 .text + d90
0000000000000038  0000001600000018 R_X86_64_PC64          0000000000000000 __verbose + 98
0000000000000040  0000000100000002 R_X86_64_PC32          0000000000000000 .text + cbf
0000000000000044  0000000100000002 R_X86_64_PC32          0000000000000000 .text + d4e
0000000000000048  0000003f00000018 R_X86_64_PC64          0000000000000000 cgroup_bpf_enabled_key + 0
0000000000000050  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 1004
0000000000000054  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 100e
0000000000000058  0000001600000018 R_X86_64_PC64          0000000000000000 __verbose + 60
0000000000000060  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 1098
0000000000000064  0000000100000002 R_X86_64_PC32          0000000000000000 .text + 10a2
0000000000000068  0000001600000018 R_X86_64_PC64          0000000000000000 __verbose + 28

% objdump -j .text -D net/ipv4/tcp_timer.o | awk '/^[0-9a-z]* <.*>:/{fun = $2} /\<601\>:/ || /\<63a\>:/ || /\<852\>:/ || /\<b38\>:/ || /\<cbf\>:/ || /\<1004\>:/ || /\<1098\>:/ {print fun $0}'
<tcp_delack_timer_handler>:     601:    0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<tcp_delack_timer_handler>:     63a:    0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<tcp_retransmit_timer>:     852:        0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<tcp_retransmit_timer>:     b38:        0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<tcp_retransmit_timer>:     cbf:        0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<tcp_retransmit_timer>:    1004:        0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
<tcp_retransmit_timer>:    1098:        0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
```
Does "descriptor." get stripped somewhere in the build?  Just trying to pattern-recognize this case for future reference.

**Comment by disaster123** [comment]
I don't get any output of objdump using -j .text at all on my .o files produced by kpatch - do i need to compile manually? Or do i need a different version of objdump

**Comment by joe-lawrence** [comment]
@jpoimboe : Digging more into include/linux/dynamic_debug.h, I see that DEFINE_DYNAMIC_DEBUG_METADATA puts data structures in to the __verbose section, so it must be referencing static keys stashed there.  Interesting use of a static key union as well in struct _ddebug.

@disaster123 : Do you see any output from "objdump --sections foo.o" ?

**Comment by disaster123** [comment]
your fix works fine. I can now compile a kernel with descriptor.

Regarding objdump it looks like this:
```
# objdump --sections  ./tmp/orig/net/ipv4/route.o
objdump: unrecognized option '--sections'

# objdump -V    
GNU objdump (GNU Binutils for Debian) 2.28
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by joe-lawrence** [comment]
> ```
> # objdump --sections  ./tmp/orig/net/ipv4/route.o
> objdump: unrecognized option '--sections'
> ```

Ah oops, brain fart there (was thinking of readelf).  Does something like '-x' provide any information about your object files?  Also, maybe "-D" works, just without the "-j .text" specification?

**Comment by jpoimboe** [comment]
@disaster123 can you try this new version of the patch?  This one is more generic and should also work for newer kernels which don't call the variable "descriptor".

https://github.com/jpoimboe/kpatch/commit/c1056a8a89334f6efdeccb2a24fb219a85f6f91c

**Comment by disaster123** [comment]
@joe-lawrence 
yes -D without -j .text works fine

@jpoimboe 
works fine as well

**Comment by joe-lawrence** [comment]
> yes -D without -j .text works fine

I think the issue is that when you look at kpatch-build generated kernel object files, we told the compiler to place every function into its own .text.<function_name> ELF section.  For those object files, you could look at the entire disassembly with only "-D", or if you want to specify individual sections (functions), you'll need "-D -j .text.<function_name>"

For many of the examples here, I was using an ordinary kernel built object file, so I could rely on the fact that all the functions were placed into a single ".text" section.

**Comment by disaster123** [comment]
ah perfect - thanks

**Comment by disaster123** [comment]
@joe-lawrence  @jpoimboe i would like to say thank you. The part with objdump and how to find static keys helped me a lot. I got an understanding how gcc handle those, what jumps are and how to identify them especially with inlined code using objdump.

**Comment by jpoimboe** [comment]
@disaster123 I think @joe-lawrence deserves most of the credit, but you're most welcome.  Thank you using kpatch and reporting issues back!

**Comment by CentUser** [comment]
Hello, @disaster123  I run into the same problem, while I'm facing the __once_key, which is used by a macro and then be used by lots of function. If I rewrite it using static_key_enable, that would change a lots of func... It's a little tricky... any suggestions?

**Comment by CentUser** [comment]
related code: 

37 #define DO_ONCE(func, ...)                           \
 38     ({                                   \
 39         bool ___ret = false;                         \
 40         static bool ___done = false;                     \
 41         static struct static_key ___once_key = STATIC_KEY_INIT_TRUE; \
 42         if (static_key_true(&___once_key)) {                 \
 43             unsigned long ___flags;                  \
 44             ___ret = __do_once_start(&___done, &___flags);       \
 45             if (unlikely(___ret)) {                  \
 46                 func(__VA_ARGS__);               \
 47                 __do_once_done(&___done, &___once_key,       \
 48                            &___flags);           \
 49             }                            \
 50         }                                \
 51         ___ret;                              \
 52     }) 
 53 
 54 #define get_random_once(buf, nbytes)                         \
 55     DO_ONCE(get_random_bytes, (buf), (nbytes))


in include/linux/once.h
