### ISSUE TITLE
Stalled process signalling in v5.1+ kernels

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1022]
Ever since upstream v5.1 (specifically commits [0b3d52790e1c](https://github.com/torvalds/linux/commit/0b3d52790e1c) ("livepatch: Remove signal sysfs attribute") and [cba82dea3061](https://github.com/torvalds/linux/commit/cba82dea3061) ("livepatch: Send a fake signal periodically") the kpatch utility script's signal_stalled_processes() functionality has been redundant.

Currently it is coded as:
- If `/sys/kernel/livepatch/$module/signal` is present, use the sysfs interface
- Otherwise iterate through all "stalled" tasks and manually signal them

I tested this against a RHEL-7.8 development release (which includes the mentioned upstream backports) and the old behavior is benign:  the kernel automatically sends "fake" signals while kpatch utility tries to do the same manually.

Going forward we would need to introduce kernel and distro-specific checks into kpatch utility if we wanted to eliminate the redundant signalling.  This should be fairly easy to add, but I wanted to gauge other's opinions as this would be the beginning of such conditional code to kpatch utility.

**Comment by jpoimboe** [comment]
The easiest solution would be to drop support for the almost-two-year-old kernels which have neither the sysfs file nor the automatic signalling, and remove the manual signalling logic altogether.  That would be my vote.

**Comment by joe-lawrence** [comment]
(Thinking out load)  I think ripping removing it from the kpatch utility would okay for older distro kernels without the automatic signalling mechanism -- they may use newer kpatch releases to _build_ kpatch .ko's, but leave the userspace utility alone to retain its old, manual signalling logic.
