### ISSUE TITLE
improve core dump handling with systemd

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#1025]
This message is no longer accurate.
```
kpatch-build/kpatch-build: line 837: 28596 Segmentation fault      (core dumped) "$TOOLSDIR"/create-diff-object "orig/$i" "patched/$i" "$KOBJFILE_NAME" "$SYMTAB" "$SYMVERS_FILE" "${MODNAME//-/_}" "output/$i" 2>&1
     28597 Done                    | logger 1
ERROR: create-diff-object SIGSEGV
ERROR: no core file found, run 'ulimit -c unlimited' and try to recreate. Check /root/.kpatch/build.log for more details.
```
By default systemd places core dumps in /var/lib/systemd/coredump/

**Comment by joe-lawrence** [comment]
Some versions of Ubuntu use [Apport](https://wiki.ubuntu.com/Apport) which I believe puts everything in `/var/crash`.  So maybe we 1) look at `/proc/sys/kernel/core_pattern` to determine who is handling the core files and act accordingly, or 2) search a bunch of paths, or 3) don't bother with the user-friendly message

**Comment by jpoimboe** [comment]
I'm thinking we can just change the message to say something like "There was a SIGSEGV, but no core dump was found in the current directory.  Depending on your distro you might look in /var/lib/systemd/coredump or /var/crash, or set "ulimit -c unlimited"."

**Comment by joe-lawrence** [comment]
Sounds reasonable to me. :+1:
