### ISSUE TITLE
ERROR: panic.o: reference to static local variable spin_counter.34770 in do_oops_enter_exit.part.0 was removed

### ISSUE THREAD

**Issue by haoren3696** [dynup/kpatch#1035]
Hi, I got a error in create-diff-object:
ERROR: panic.o: reference to static local variable spin_counter.34770 in do_oops_enter_exit.part.0 was removed
/kpatch/kpatch-build/create-diff-object: unreconcilable difference

It is because that the do_oops_enter_exit.part.0 in original panic.o can not correlate to do_oops_enter_exit in patched panic.o. So it got fatal error in kpatch_correlate_static_local_variables. In kpatch_rename_mangled_functions, current code seems to rename do_oops_enter_exit.part.0 to do_oops_enter_exit in patched object, but does not rename do_oops_enter_exit to oops_enter_exit.part.0 in my case.

```
localhost:~/.kpatch/tmp # eu-readelf -S orig/kernel/panic.o|grep do_oops_enter_exit
[18] .text.do_oops_enter_exit.part.0 PROGBITS     0000000000000000 00000348 000001d8  0 AX     0   0  8
[19] .rela.text.do_oops_enter_exit.part.0 RELA         0000000000000000 00024020 000002d0 24 I     150  18  8
localhost:~/.kpatch/tmp # eu-readelf -S patched/kernel/panic.o |grep do_oops_enter_exit
[18] .text.do_oops_enter_exit PROGBITS     0000000000000000 00000348 00000200  0 AX     0   0  8
[19] .rela.text.do_oops_enter_exit RELA         0000000000000000 00024240 000002e8 24 I     153  18  8

```

**Comment by haoren3696** [comment]
Here is my test object
[testcase.tar.gz](https://github.com/dynup/kpatch/files/3589709/testcase.tar.gz)

**Comment by joe-lawrence** [comment]
@julien-thierry : would your recent rhel-8.0 rebase PR account for this?

**Comment by CentUser** [comment]
Perhaps you used a different gcc version. I mean the gcc compile date is not the same.
gcc version 4.8.5 20150623
The date following 4.8.5 matters. Different version may have different default compile attributes.
In your situation, I wander if the function is compiled with the attribute noclone.

**Comment by julien-thierry** [comment]
Sorry, I kinda forgot to reply to this issue.

The testcase does not have the symbol table or the symvers files so I'm not sure how to test this. But it sounds like the following PR could fix this:
https://github.com/dynup/kpatch/pull/1054

**Comment by joe-lawrence** [comment]
bump: @haoren3696 : can you verify if @julien-thierry 's suggestion that #1054 might fix this issue? Thanks!

Also note that the testcase.tar.gz includes AARCH64 object files, for which kpatch-patch doesn't officially support yet (patches welcome).
