### ISSUE TITLE
Static Local Variable: missing reference to it...

### ISSUE THREAD

**Issue by CentUser** [dynup/kpatch#1049]
Hi, 

I am patch code:v4.9.2 in kernel.org with this patch:https://github.com/torvalds/linux/commit/ee60ad219f5c7c4fb2f047f88037770063ef785f , but failed.

I'm using the latest kpatch from github, I wander if we can use kpatch to patch the system function using static local variables?

In this try, I encountered an error: 
/usr/local/libexec/kpatch/create-diff-object: ERROR: route.o: kpatch_regenerate_special_section: 2043: Found a jump label at ip_del_fnhe.isra.38()+0x29, using key ___once_key.65353.  Jump labels aren't currently supported.  Use static_key_enabled() instead.

Following the instruction found in previous issues, I find myself must rewrite the function 
fnhe_hashfun included in ip_del_fnhe. While this function uses __once_key, which is a static local variable. 

```
static inline u32 kpatch_fnhe_hashfun(__be32 daddr)
{
	static u32 fnhe_hashrnd __read_mostly;
	u32 hval;              
                                       
        bool ___ret = false;                     
        static bool ___done = false;                     
        static struct static_key ___once_key = STATIC_KEY_INIT_TRUE;               
        if (static_key_enabled(&___once_key)) {                 
            unsigned long ___flags;                 
            ___ret = __do_once_start(&___done, &___flags);      
            if (unlikely(___ret)) {                 
                get_random_bytes(&fnhe_hashrnd, sizeof(fnhe_hashrnd));               
                __do_once_done(&___done, &___once_key,      
                           &___flags);  
            }                            
        }                               
    
    //	net_get_random_once(&fnhe_hashrnd, sizeof(fnhe_hashrnd
	hval = jhash_1word((__force u32) daddr, fnhe_hashrnd);
	return hash_32(hval, FNHE_HASH_SHIFT);
}
static inline u32 fnhe_hashfun(__be32 daddr)
{
	static u32 fnhe_hashrnd __read_mostly;
	u32 hval;


	net_get_random_once(&fnhe_hashrnd, sizeof(fnhe_hashrnd));
	hval = jhash_1word((__force u32) daddr, fnhe_hashrnd);
	return hash_32(hval, FNHE_HASH_SHIFT);
}
```

After rewriting the function fnhe_hashfun to kpatch_fnhe_hashfun, still there was an error:
ERROR: route.o: static local ___once_key.65353 has been correlated with ___once_key.65353, but patched update_or_create_fnhe is missing a reference to it
/usr/local/libexec/kpatch/create-diff-object: unreconcilable difference

eh, different error. 
I located the message "missing a reference to it" in create-diff-object. it is in:
https://github.com/dynup/kpatch/blob/df5730076f4834fa9b4ff00a0a001ef88e585bf5/kpatch-build/create-diff-object.c#L1127

I perhaps not quite familiar with the code subtleties, but i wander why I changed ip_del_fnhe, and write a new function kpatch_fnhe_hashfun could make update_or_create_fnhe a patched function?

Besides, whether we could include the original piece of code if we could not find a missing patched version?

**Comment by CentUser** [comment]
I also find out that the function ip_del_fnhe was optimized by gcc ipa-clones to function called: ip_del_fnhe.isra.38 .  After adding code disable gcc optimization on this function ,  there still is the error:
ERROR: route.o: reference to static local variable ___done.65352 in ip_del_fnhe.isra.38 was removed
/usr/local/libexec/kpatch/create-diff-object: unreconcilable difference

check the object file of route.o, confirmed that there is really no function ip_del_fnhe.isra.38.

**Comment by joe-lawrence** [comment]
@CentUser : Unfortunately, I can't think of an easy way around modifying functions that include the local, static keys that the `DO_ONCE` macros create:

```C
#define DO_ONCE(func, ...)                                                   \
        ({                                                                   \
                bool ___ret = false;                                         \
                static bool ___done = false;                                 \
                static DEFINE_STATIC_KEY_TRUE(___once_key);                  \
                if (static_branch_unlikely(&___once_key)) {                  \
                        unsigned long ___flags;                              \
                        ___ret = __do_once_start(&___done, &___flags);       \
                        if (unlikely(___ret)) {                              \
                                func(__VA_ARGS__);                           \
                                __do_once_done(&___done, &___once_key,       \
                                               &___flags);                   \
                        }                                                    \
                }                                                            \
                ___ret;                                                      \
        })
```
@jpoimboe any ideas here?

**Comment by jpoimboe** [comment]
I'm working on improving jump label / static key support this week, I suspect it will solve this problem.

**Comment by CentUser** [comment]
Thanks for the response, I'm also reading the codes. Due to the lack of relation information between sections, I'm reading it with difficulties. But I'll continue that.

**Comment by scofieldsoros** [comment]
Any update on this ? We met the same problem, and unfortunately static local variables are everywhere in the kernel ...

**Comment by CentUser** [comment]
emm... I haven't found a solution myself, but I find out that kpatch version:0.6.3 could compile it successfully, but with warnings. As they said, static local variables support is difficult. So , version 0.6.3 may contain some bugs, depend on you. 
Here goes my experience, I strongly suggests you compile your patches with kpatch using the same gcc version, thus , gcc may produce the same static local varible suffix, which may lead to little mis-correlates problems.
And if that does not ease the pain, try version 0.6.3 at your risk. @scofieldsoros

**Comment by scofieldsoros** [comment]
@CentUser Thanks for your kind reply !

I tried the way this [link](https://github.com/dynup/kpatch/blob/master/doc/patch-author-guide.md#removing-references-to-static-local-variables) says, but if failed.

Trying 0.6.3 may be a solution, but I'm thinking if we can workaround this with the solution in the above link.

**Comment by CentUser** [comment]
I also tried that, and failed as you did. ^_^
