### ISSUE TITLE
ARCHVERSION is not match the current running kernel

### ISSUE THREAD

**Issue by name-null** [dynup/kpatch#1060]
when i build an livepatch for --oot-module with option -e,
it failed !
OS : CentOS 7.6
cur-kernel : 3.10.0-957.el7.x86_64（neither install nor update kernel  3.10.0-957.12.1）
and i build oot-module with cur kernel,
but
ARCHVERSION="$(modinfo -F vermagic "$OOT_MODULE" | awk '{print $1}')"
"3.10.0-957.12.1.el7.x86_64"
the result don't match the cur-kernel
ERROR: kernel-debuginfo-3.10.0-957.12.1.el7.x86_64 not installed
so, get ARCHVERSION from vermagic is unreliable !

**Comment by joe-lawrence** [comment]
[ cc += @pcd1193182 ]

Hmm, I don't think we ever planned or tested for a use case where the OOT module has been built for a different, but still kABI compatible, kernel version.

Correct me if I have this information wrong:
* The running kernel is 3.10.0-957.el7
* The OOT module was built against 3.10.0-957.12.1.el7

Thinking more on this, I believe that kpatch-build's warning is legitimate.

The correct build difference for the resulting kpatch module should be:  OOT_original (3.10.0-957.12.1.el7) vs. OOT_patched (3.10.0-957.12.1.el7).

If it were to compare with OOT_patched(3.10.0-957.el7), theoretically there could be kernel-provided inline functions that have changed from 3.10.0-957.el7 to 3.10.0-957.12.1.el7.  These would be detected by kpatch-build and inadvertently included in the kpatch module.

If kernel-debuginfo-3.10.0-957.12.1.el7.x86_64 is installed, does a subsequent kpatch-build and kpatch load succeed as expected?

**Comment by name-null** [comment]
1.
 "3.10.0-957.12.1.el7" kernel never installed.
2.
The version of debuginfo rpm :
kernel-debuginfo-3.10.0-957.el7.x86_64
kernel-debuginfo-common-x86_64-3.10.0-957.el7.x86_64
3.
I had `sudo grep -rni 3.10.0-957.12.1.el7.x86_64 /`, but got nothing !
so where the string came from?

**Comment by name-null** [comment]
I think i have found where the string came from:
1. At the step 'Install the dependencies for compiling kpatch'
`UNAME=$(uname -r)`
`sudo yum install gcc kernel-devel-${UNAME%.*} elfutils elfutils-devel`
kernel version was not specifiled, so the up-to-date version '3.10.0-957.12.1.el7' devel and headers were installed, so the VERSION was changed when compiled OOT-modules.

2. The diff content of header file:
diff kernel-headers-3.10.0-957.el7.x86_64/usr/include/linux/version.h kernel-headers-3.10.0-957.12.1.el7.x86_64/usr/include/linux/version.h
7,8c7,8
< #define RHEL_RELEASE "957"
< #define KERNEL_HEADERS_CHECKSUM "08e373f05de231b7b9b6ec5af5075ddc5410c0c4"
---
> #define RHEL_RELEASE "957.12.1"
> #define KERNEL_HEADERS_CHECKSUM "37aafa9e1ce9776ed27088e0d7a51412eaeeea89"

3. The diff content of Makefile:
diff /usr/src/kernels/3.10.0-957.el7.x86_64/Makefile /usr/src/kernels/3.10.0-957.12.1.el7.x86_64/Makefile
4c4
< EXTRAVERSION = -957.el7.x86_64
---
> EXTRAVERSION = -957.12.1.el7.x86_64
8c8
< RHEL_RELEASE = 957
---
> RHEL_RELEASE = 957.12.1

**Comment by name-null** [comment]
Solution: 
1.Change the /etc/yum.repos.d/CentOS-Base.repo, redirect mirror URL to vault
2.Downgrade headers and devels
