### ISSUE TITLE
Enabling GCC warnings to catch type conversion issues

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#1066]
As discussed in #1065 I think it would be a good idea to enable `-Wconversion` and possibly ` -Wno-sign-conversion` to prevent more nasty bugs.

**Comment by kamalesh-babulal** [comment]
I had the patch series based on the discussion ready, #1067. Waiting for the patch discussed in #1065  to be merged, as the series fixes the warnings on top of the patch.

**Comment by joe-lawrence** [comment]
Fixed by #1067
