### ISSUE TITLE
test/integration/gcc-static-local-var-4.patch fails on RHEL-7.7 ppc64le

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1069]
The gcc-static-local-var-4.test script checks that it can't find a "free_ioctx" symbol in the resulting kpatch .ko, but on ppc64le it finds klp-relocation symbols that do match:
```
(x86_64)
  % nm ~/.kpatch/tmp/patch/livepatch-gcc-static-local-var-4.ko | grep 'free_ioctx'
  (nothing)

(ppc64le)
  % nm ~/.kpatch/tmp/patch/livepatch-gcc-static-local-var-4.ko | grep 'free_ioctx'
  0000000000000000 a .klp.sym.vmlinux.free_ioctx,1
  0000000000000000 a .klp.sym.vmlinux.free_ioctx_rcu,1
```
So perhaps we should narrow the grep pattern to filter them out `-v .klp.sym.` and add word boundaries `\<free_ioctx\>` to be even more specific.

At the same time, I'm not entirely clear how this test works.  The [patch](https://github.com/dynup/kpatch/blob/master/test/integration/rhel-7.7/gcc-static-local-var-4.patch) adds a small function with a printk and calls it from put_aio_ring_file().  But the [test](https://github.com/dynup/kpatch/blob/master/test/integration/rhel-7.7/gcc-static-local-var-4.test) looks for the existence of a free_ioctx symbol.  Is the test checking that unmodified functions that contain dynamic debugging printk's aren't incorrectly included in the resulting livepatch .ko?

**Comment by jpoimboe** [comment]
> Is the test checking that unmodified functions that contain dynamic debugging printk's aren't incorrectly included in the resulting livepatch .ko?

That would be my best guess.

I wonder why this wasn't caught by CI @sm00th ?

**Comment by sm00th** [comment]
> I wonder why this wasn't caught by CI @sm00th ?
Checked on 7.7 and nm we have there(2.27-41.base.el7) fails to read the resulting .ko:

```
# nm livepatch-gcc-static-local-var-4.ko 
nm: livepatch-gcc-static-local-var-4.ko: Bad value
```

We never check nm's return code and that output does not contain 'free_ioctx' so the test passes.

**Comment by sm00th** [comment]
Tried it with an updated binutils 2.27-43.base.el7 and that one works.

**Comment by joe-lawrence** [comment]
> Tried it with an updated binutils 2.27-43.base.el7 and that one works.

D'oh!  That makes perfect sense now.  I was in the process of testing the klp-relocation binutils fix on ppc64le when I stumbled across this.

I can queue up a PR that adds better filters the nm output as well as checking the return code in case the .ko is missing / corrupt / etc.

**Comment by sm00th** [comment]
> I can queue up a PR that adds better filters the nm output as well as checking the return code in case the .ko is missing / corrupt / etc.

We definitely need to do that, but we might want to postpone merging it until we have updated binutils on our test-distros.

**Comment by joe-lawrence** [comment]
> but we might want to postpone merging it until we have updated binutils on our test-distros

Good point.  Since we have a whole host of integration test directories for various distributions and versions, tracking all of them sounds like a major pain.

On the other hand, even older `eu-readelf` versions can handle klp-relocation sections/symbols. If we instead use `eu-readelf --wide --symbols`, we can side step this problem across all distro / version tests.

**Comment by joe-lawrence** [comment]
... but now I notice that we have a bunch of previous commits to use the binutils variants of tools like readelf instead of their elfutils counterparts.
