### ISSUE TITLE
ppc64le kpatch-build crashes when .rela.toc is missing

### ISSUE THREAD

**Issue by julien-thierry** [dynup/kpatch#1078]
The following kernel patch causes create-diff-object to segfault on ppc64le

```
diff --git a/net/ceph/pagelist.c b/net/ceph/pagelist.c
index c7c220a736e..c748e45be48 100644
--- a/net/ceph/pagelist.c
+++ b/net/ceph/pagelist.c
@@ -5,6 +5,8 @@
 #include <linux/highmem.h>
 #include <linux/ceph/pagelist.h>
 
+/* Dummy change */
+
 static void ceph_pagelist_unmap_tail(struct ceph_pagelist *pl)
 {
 	if (pl->mapped_tail) {
```

The reason is that the .toc section of `net/ceph/pagelist.o` only contains constants and in such cases the compiler does not create a corresponding .rela.toc section. The current function toc_rela() expect this section to alway be present and tries to access it.

**Comment by kamalesh-babulal** [comment]
Hi Julien,

I am tryinng to reproduce it with upstream `5.6-rc3` Kernel and the `rela.toc` section has constant entries: (gcc is `9.2.1`):
```
Relocation section '.rela.toc' at offset 0x20558 contains 2 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000000  0000003b00000026 R_PPC64_ADDR64         0000000000000000 kmalloc_caches + 0
0000000000000008  0000004300000026 R_PPC64_ADDR64         0000000000000000 vmemmap + 0
```
```
objdump -Dr ./patched/net/ceph/pagelist.o
Disassembly of section .toc:

0000000000000000 <.toc>:
        ...
                        0: R_PPC64_ADDR64       kmalloc_caches
                        8: R_PPC64_ADDR64       vmemmap
```

**Comment by julien-thierry** [comment]
Hi Kamalesh,

I managed to reproduce this on RHEL-7.7. So I don't know whether it is the RHEL-7.7 kernel code base triggering this or the compiler used in RHEL-7.7 (gcc (GCC) 4.8.5 20150623).

```
Disassembly of section .toc:

0000000000000000 <.toc>:
   0:   e0 ff ff ff     .long 0xffffffe0
   4:   ff ff ff 0f     twui    r31,-1
```

**Comment by julien-thierry** [comment]
Here's the object file (I'll try to add the unit test). Had to put it in tar format because github doesn't accept elf objects.

[toc-norela.tar.gz](https://github.com/dynup/kpatch/files/4267140/toc-norela.tar.gz)

**Comment by kamalesh-babulal** [comment]
Looks interesting. I compiled `kernel-3.10.0-1062.el7` with `gcc-9`
```
Disassembly of section .toc:
0000000000000000 <.toc>:
        ...
                        0: R_PPC64_ADDR64       .data
                        8: R_PPC64_ADDR64       .data.rel
                        10: R_PPC64_ADDR64      .rodata
                        18: R_PPC64_ADDR64      .rodata.str1.8
                        20: R_PPC64_ADDR64      __this_module
```
Looks like some GCC thing, I will try to setup RHEL 7.7 sometime next week. Probably, we should add a warning.
