### ISSUE TITLE
Which architectures is kpatch compatible with?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [dynup/kpatch#1101]
Since it doesn't say in the README, I thought that kpatch was compatible in all architectures, so I tried to use it on my Raspberry Pi (Aarch64), but then realized that kpatch is not compatible with Aarch64 (or the other way around) thanks to this comment https://github.com/dynup/kpatch/issues/1099#issuecomment-625913876. I'd like to know which architectures kpatch is available on, so I can work on making a PR for it just to make it more clear.

**Comment by yhcote** [comment]
The currently supported architectures are x86 and ppc64.

**Comment by kamalesh-babulal** [comment]
> The currently supported architectures are x86 and ppc64.

Adding to it, on Power only 64-bit Little Endian (ppc64le) is supported.

**Comment by TheEvilSkeleton** [comment]
Thank you for the information. https://github.com/dynup/kpatch/pull/1104
