### ISSUE TITLE
KLP module fails to build with latest mainline [5.8-rc]

### ISSUE THREAD

**Issue by kamalesh-babulal** [dynup/kpatch#1125]
The current mainline tree `5.8-rc` fails to build the kernel livepatching module,
  during the module build stage, with the error:
 ```
meminfo.o: changed function: meminfo_proc_show
make -C /root/objtool/linux M=/root/.kpatch/tmp/patch
make[1]: Entering directory '/root/objtool/linux'
  LDS     /root/.kpatch/tmp/patch/kpatch.lds
  AR      /root/.kpatch/tmp/patch/built-in.a
  CC [M]  /root/.kpatch/tmp/patch/patch-hook.o
  LD [M]  /root/.kpatch/tmp/patch/livepatch-meminfo.o
  MODPOST /root/.kpatch/tmp/patch/Module.symvers
/root/.kpatch/tmp/patch/.output.o.cmd: No such file or directory
make[2]: *** [scripts/Makefile.modpost:111: /root/.kpatch/tmp/patch/Module.symvers] Error 1
make[1]: *** [Makefile:1669: modules] Error 2
make[1]: Leaving directory '/root/objtool/linux'
make: *** [Makefile:22: livepatch-meminfo.ko] Error 2
```
 
the commit 70f30cfe5b89 ("modpost: use read_text_file() and get_line() for reading
text files") would fail any `.o` used in the building a module without `*.cmd` file.
The `*.cmd` file, holds the information like gcc command line used to build the
`.o`, source file details and dependencies list. This information I guess its used
by kbuild to trigger rebuilding of `.o` or `.o.*` files in case of the dependencies
are updated.
 
`kpatch/kmod/patch/Makefile`:
```
  ...
  $(KPATCH_NAME)-objs += patch-hook.o output.o
 
  all: $(KPATCH_NAME).ko
 
  $(KPATCH_NAME).ko:
          $(KPATCH_MAKE)
 
  patch-hook.o: patch-hook.c kpatch-patch-hook.c livepatch-patch-hook.c
          $(KPATCH_MAKE) patch-hook.o
```

`output.o` doesn't uses the kernel build system but is hand build using
`create-diff-object`, hence the `.output.o.cmd` is not generated. One way to
address this issue would be created an empty `.output.o.cmd`, so that the kernel
build system is happy and it technically has no dependency on the kernel to
trigger re-build over using make -i (ignore) flag to bypass any such issue.

```
  --- a/kpatch-build/kpatch-build
  +++ b/kpatch-build/kpatch-build
@@ -963,6 +963,8 @@ ld -r $KPATCH_LDFLAGS -o ../patch/tmp_output.o $(find . -name "*.o") 2>&1 | logg
  
 if [[ "$USE_KLP" -eq 1 ]]; then
        cp "$TEMPDIR"/patch/tmp_output.o "$TEMPDIR"/patch/output.o || die
+       # empty .cmd file is required to keep KBUILD happy
+       touch "$TEMPDIR"/patch/.output.o.cmd
 else
        # Add .kpatch.checksum for kpatch script
        md5sum ../patch/tmp_output.o | awk '{printf "%s\0", $1}' > checksum.tmp || die
```
Makefile magic is something I don't understand well, I guess there are better ways
to fix this issue.

**Comment by joe-lawrence** [comment]
Hi @kamalesh-babulal,

I knew this was familiar ... a few months ago I was working on a [hook-hacking-helpers branch](https://github.com/dynup/kpatch/compare/master...joe-lawrence:hook-hacking-helpers) that added some more debug-ability to the build.  One of the things I patched over was the "WARNING: could not find .output.cmd for output.o".  I never really finished that branch, but now we learn that the .cmd file is a requirement.

I applied a similar fix to create an empty .output.cmd file.  If you think the other commits in [hook-hacking-helpers branch](https://github.com/dynup/kpatch/compare/master...joe-lawrence:hook-hacking-helpers) look useful, I can just rebase and open a PR for that.  I can't think of a better way to handle this one either.

**Comment by kamalesh-babulal** [comment]
> I applied a similar fix to create an empty .output.cmd file. If you think the other commits in hook-hacking-helpers branch look useful, I can just rebase and open a PR for that. I can't think of a better way to handle this one either.

Hi @joe-lawrence,

I liked the branch, thanks for putting together the function description and commentary that will be surely helpful, while working on the livepatching hook.  I guess the debugging information in `kmod/patch/Makefile` can be removed in the PR.

**Comment by joe-lawrence** [comment]
>  I guess the debugging information in `kmod/patch/Makefile` can be removed in the PR.

Heh, that was actually the most interesting part of the branch IMHO.  Otherwise one has to go figure out all the environment variables (like the kernel data structure sizes) before re-running the build or individual kpatch-build programs.  I can spun out those debug and commentary changes from the modpost fix if that makes it cleaner.

**Comment by kamalesh-babulal** [comment]
>  Heh, that was actually the most interesting part of the branch IMHO. Otherwise one has to go figure out all the environment variables (like the kernel data structure sizes) before re-running the build or individual kpatch-build programs. 

Sorry, I initially thought it was your debugging leftover, that you were using to solve `.cmd` build issue, like every one of us have different stages during the KLP build to capture some of those information especially the kernel data structure sizes.  I write the kernel data structure unconditionally (with or without `-d`) into `build.log` along with `--skip-cleanup` for every build.  Yeah, makes sense to capture the environment in `build.env`.

> I can spun out those debug and commentary changes from the modpost fix if that makes it cleaner.

I am okay with both of the approaches.
