### ISSUE TITLE
kernel 5.8 jump label support backport

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#1142]
I've seen that kpatch 0.9.2 will support jump labels for 5.8+ kernels. Is there a way to backport those kernel patches back to kernel 5.4 to support jump labels there as well? 

If yes which commits are need to be backported to 5.4?

Greets,
Stefan

**Comment by joe-lawrence** [comment]
Hi @disaster123 ,

The patchset in question was @jpoimboe's [[PATCH v4 00/11] livepatch,module: Remove .klp.arch and module_disable_ro()](https://lore.kernel.org/live-patching/cover.1588173720.git.jpoimboe@redhat.com/).
Off hand I don't know how difficult it would be to backport to 5.4, but I would think there is probably a decent amount of code churn in the affected files.  Omitting some unneeded arch stuff (s390, um) might help.

**Comment by disaster123** [comment]
this patchset applied fine to 5.4 just some small hickups. Main issue seems to be the missing text_poke_sync function. But those patches introducing text_poke_sync do not apply

**Comment by joe-lawrence** [comment]
@jpoimboe would have a better handle on backporting possibilities for the patchset, but perhaps untangling the klp-relocation updates from the other cleanups could help.  That would pare down the list to only:
```
dcf550e52f56 livepatch: Disallow vmlinux.ko
7c8e2bdd5f0d livepatch: Apply vmlinux-specific KLP relocations early
1d05334d2899 livepatch: Remove .klp.arch
ca376a937486 livepatch: Prevent module-specific KLP rela sections from referencing vmlinux symbols
```
which you've said already mostly applies on top of v5.4-stable.

**Comment by disaster123** [comment]
@joe-lawrence thanks a lot. @jpoimboe do you think this is possible and doable? Does kpatch 0.9.2 automatically detect this?

**Comment by jpoimboe** [comment]
@disaster123 I try to avoid messing with backports unless I'm getting paid to do so ;-) but @joe-lawrence 's approach sounds good to me.  You would also have to modify this check in kpatch-build, change 5.8.0 to 5.4.0:
```
        if kernel_is_rhel || ! kernel_version_gte 5.8.0; then
                USE_KLP_ARCH=1
                KPATCH_LDFLAGS="--unique=.parainstructions --unique=.altinstructions"
                CDO_FLAGS="--klp-arch"
        fi
```

**Comment by disaster123** [comment]
thanks
