### ISSUE TITLE
clang needs -mprofile-kernel switch for ppc64le

### ISSUE THREAD

**Issue by sm00th** [dynup/kpatch#1157]
During discussion in #1156 we found out that while it is possible to build a ppc64le kernel with clang, generated code is not kpatchable and clang needs an analog of gcc's `-mprofile-kernel` switch. @kamalesh-babulal is going to find out whether IBM's compiler team will be able to help us with that.

**Comment by jpoimboe** [comment]
I presume we would also need a clang plugin similar to our gcc plugin to insert nops after local calls.

**Comment by kamalesh-babulal** [comment]
> I presume we would also need a clang plugin similar to our gcc plugin to insert nops after local calls.

I guess so, we might need a clang plugin variant too.

**Comment by kamalesh-babulal** [comment]
Quick update: I had checked with the compiler team on two questions.
1. If there is some alternative or undocumented switch in clang that's equal to that of  gcc's `-mprofile-kernel`?
    clang lacks support for `-mprofile-kernel` equivalent. 
2. Is this any work planned or in progress to have such switch?
    There are no plans to add it in the near future. I update the issue, if there is some news on it.
