### ISSUE TITLE
kpatch-build: changed section .rela.static_call_sites not selected for inclusion

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1165]
Yulia noticed that shadow-newpid.patch fails to build on a RHEL-9 kernel (5.12.0-0.rc2.166.el9.x86_64).  Interesting excerpt from the build.log:
```
ERROR: fork.o: 1 unsupported section change(s)
fork.o: WARNING: unable to correlate static local variable ctr.97 used by kernel_clone, assuming variable is new
fork.o: changed function: kernel_clone
fork.o: changed section .rela.static_call_sites not selected for inclusion
create-diff-object: unreconcilable difference
ERROR: exit.o: 1 unsupported section change(s)
exit.o: changed function: do_exit
exit.o: changed section .rela.static_call_sites not selected for inclusion
create-diff-object: unreconcilable difference
array.o: changed function: proc_pid_status
```
[cachedir-tmp-shadow-newpid.tar.gz](https://github.com/dynup/kpatch/files/6172293/cachedir-tmp-shadow-newpid.tar.gz)
[build.log.txt.gz](https://github.com/dynup/kpatch/files/6172304/build.log.txt.gz)

**Comment by jpoimboe** [comment]
Always fun when a feature I write in Linux ends up breaking kpatch.  It happens more often than I care to admit.

**Comment by jpoimboe** [comment]
This will probably be a simple fix, I just need to add .static_call_sites to the special sections.
