### ISSUE TITLE
integration: module.patch: mcsafe_key has been deprecated

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1166]
The `mcsafe_key` went away with [ec6347bb4339](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ec6347bb4339) ("x86, powerpc: Rename memcpy_mcsafe() to copy_mc_to_{user, kernel}()"), introduced upstream in  v5.10. 

@jpoimboe : from reading the patch, I think `mcsafe_key` was randomly picked from vmlinux?  Can we just substitute for another exported static key like `context_tracking_enabled`?  (Other suggestions welcome.)

**Comment by jpoimboe** [comment]
Yeah, I think any exported static key would do.

**Comment by joe-lawrence** [comment]
Fixed in #1166

**Comment by jpoimboe** [comment]
> Fixed in #1166

Recursive fix? ;-)

**Comment by joe-lawrence** [comment]
> > Fixed in #1166
> 
> Recursive fix? ;-)

Cool, glad I didn't take down github with that typo.  Correct info below:

Fixed in #1265
