### ISSUE TITLE
couldn't find matching read_write.c local symbols in vmlinux symbol table

### ISSUE THREAD

**Issue by alishir** [dynup/kpatch#1170]
Hello,
I tried to implement simple patch for learning purpose, but I got following error:

```
$ ./kpatch-build/kpatch-build  --skip-compiler-check -t vmlinux read.patch                                                      07:34:42
WARNING: Skipping compiler version matching check (not recommended)
Using cache at /home/ali/.kpatch/src
Testing patch file(s)
Reading special section data
readelf: Error: LEB value too large
readelf: Error: LEB value too large
readelf: Error: LEB value too large
readelf: Error: LEB value too large
readelf: Error: LEB value too large
Building original source
Building patched source
Extracting new and modified ELF sections
/home/ali/learning/livepatch/kpatch/kpatch-build/create-diff-object: ERROR: read_write.o: find_local_syms: 180: couldn't find matching read_write.c local symbols in vmlinux symbol table
ERROR: 1 error(s) encountered. Check /home/ali/.kpatch/build.log for more details.
```

And here is my patch file:

```patch
Index: b/fs/read_write.c
===================================================================
--- a/fs/read_write.c
+++ b/fs/read_write.c
@@ -595,6 +595,7 @@ static inline loff_t *file_ppos(struct f

 ssize_t ksys_read(unsigned int fd, char __user *buf, size_t count)
 {
+       printk("Hello livepatch.\n");
        struct fd f = fdget_pos(fd);
        ssize_t ret = -EBADF;

```

**Comment by jpoimboe** [comment]
Hi @alishir,

The "LEB value too large" warning is concerning.  I wonder if there's something wrong with the vmlinux.  Did it come from a debuginfo RPM or similar (not sure what distro you're using)?

Another idea is that `--skip-compiler-check` could potentially be the cause of the find_local_syms error, depending on how different the compiler version is from the original.

**Comment by alishir** [comment]
I've installed kpatch-build on ubuntu 20.04 with the given instructions in the project README and here is the list of installed packages for linux that contains debug symbols:

```
❯ dpkg -l | grep dbgsym                                                                                                       
ii  linux-image-5.8.0-48-generic-dbgsym          5.8.0-48.54~20.04.1                   amd64        Signed kernel image generic
ii  linux-image-unsigned-5.8.0-48-generic-dbgsym 5.8.0-48.54                           amd64        Linux kernel debug image for version 5.8.0 on 64 bit x86 SMP
```
The reason that I used `--skip-compiler-check` is the following error while both gcc versions are `10.2.0`:
```
❯ ./kpatch-build/kpatch-build -t vmlinux read.patch                                                                         
Using cache at /home/ali/.kpatch/src
ERROR: gcc/kernel version mismatch
gcc version:    GCC: (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
kernel version: GCC: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Install the matching gcc version (recommended) or use --skip-compiler-check
to skip the version matching enforcement (not recommended)
ERROR: kpatch build failed.
```

**Comment by alishir** [comment]
I just installed exact gcc version and know I got this error:
```
❯ ./kpatch-build/kpatch-build -t vmlinux read.patch                                                                             08:13:06
Using cache at /home/ali/.kpatch/src
readelf: symbol lookup error: readelf: undefined symbol: ctf_arc_bufopen, version LIBCTF_1.0
readelf: symbol lookup error: readelf: undefined symbol: ctf_arc_bufopen, version LIBCTF_1.0
Testing patch file(s)
ERROR: /home/ali/projects/livepatch/kpatch/read.patch file failed to apply. Check /home/ali/.kpatch/build.log for more details.
```

**Comment by liu-song-6** [comment]
I got a similar error: 
`/data/users/songliubraving/kpatch/kpatch-build/create-diff-object: ERROR: sys.o: find_local_syms: 193: couldn't find matching sys.c local symbols in vmlinux symbol table`

The patch I use is like 

```
diff --git i/kernel/sys.c w/kernel/sys.c
index d325f3ab624a..ae31c7cd76cb 100644
--- i/kernel/sys.c
+++ w/kernel/sys.c
@@ -1266,7 +1266,7 @@ SYSCALL_DEFINE1(uname, struct old_utsname __user *, name)
                return -EFAULT;

        down_read(&uts_sem);
-       memcpy(&tmp, utsname(), sizeof(tmp));
+       memcpy(&tmp, "hello", sizeof(tmp));
        up_read(&uts_sem);
        if (copy_to_user(name, &tmp, sizeof(tmp)))
                return -EFAULT;

```

After digging into the code, I found it is caused by a mismatch of a OBJECT named "offsets.56223", which is got a different number in  vmlinux.symtab: 
`  9458: ffffffff8204e2a0    11 OBJECT  LOCAL  DEFAULT    2 offsets.56225`

The only "offsets" in sys.c is an array:
```
        static const unsigned char offsets[] = {
                offsetof(struct prctl_mm_map, start_code),
                offsetof(struct prctl_mm_map, end_code),
                offsetof(struct prctl_mm_map, start_data),
                offsetof(struct prctl_mm_map, end_data),
               ....
       };
```
What shall we do to fix such issues?

**Comment by jpoimboe** [comment]
There seem to be a lot of different issues going on here.

> readelf: symbol lookup error: readelf: undefined symbol: ctf_arc_bufopen, version LIBCTF_1.0

I've never seen this before, it looks like maybe your version of readelf is having a problem with CTF.

ERROR: /home/ali/projects/livepatch/kpatch/read.patch file failed to apply. Check /home/ali/.kpatch/build.log for more details.

This means the patch doesn't apply for some reason.  Maybe your ~/.kpatch directory got corrupted somehow?

> /data/users/songliubraving/kpatch/kpatch-build/create-diff-object: ERROR: sys.o: find_local_syms: 193: couldn't find matching sys.c local symbols in vmlinux symbol table

Usually this means there's some mismatch, either in the code or the toolchain, between the original compilation of vmlinux and the kpatch-build compilation.  The kernel code and toolchain (compiler, binutils, etc) need to be identical.

**Comment by liu-song-6** [comment]
@jpoimboe Thanks! I think you are right, there must be some mismatch.

**Comment by jpoimboe** [comment]
BTW, if it is indeed a mismatch, pull requests are welcome to improve the error message :-)  Maybe something like "possible kernel code or compiler toolchain mismatch compared to the original kernel" at the end of the message.

**Comment by alishir** [comment]
@jpoimboe Thanks a lot. How can I ensure that the toolchain and kernel code are identical? How can I found the versions of toolchain that used for compiling my running kernel?

**Comment by jpoimboe** [comment]
@alishir That's probably more of a distro question, but I don't know enough about Ubuntu to be able to answer that.  There used to be some Ubuntu folks that contributed here, but I think that was years ago now.

The most important part of the toolchain is the compiler.  If you're still getting that warning with the same compiler, there might be some difference in the code itself.

**Comment by liu-song-6** [comment]
> BTW, if it is indeed a mismatch, pull requests are welcome to improve the error message :-) Maybe something like "possible kernel code or compiler toolchain mismatch compared to the original kernel" at the end of the message.

I am not able to reproduce this with the same test patch on a 5.12 based kernel. I will play more with it. Thanks!

**Comment by nunojpg** [comment]
see #1209
