### ISSUE TITLE
Remind: not install kpatch-build from apt-get, compile it for your self, to avoid 100% CPU blocking for tens of hours..

### ISSUE THREAD

**Issue by MaoJianwei** [dynup/kpatch#1184]
=== CLI output ===

XXXX@XXXX:~$ kpatch-build version.patch
Debian/Ubuntu distribution detected
Downloading and unpacking the kernel source for 5.4.0-73-generic
Testing patch file(s)
Reading special section data
readelf: Error: LEB value too large
readelf: Error: LEB value too large
Building original source
Building patched source
Extracting new and modified ELF sections

=== build.log ===

  LD [M]  sound/xen/snd_xen_front.ko
  LD [M]  ubuntu/hio/hio.ko
  LD [M]  ubuntu/xr-usb-serial/xr_usb_serial_common.ko
Debug: build-generic
checking file fs/proc/version.c
patching file fs/proc/version.c
Debug: /home/XXXX/.kpatch/src/debian/stamps/stamp-build-generic build_image vmlinux bldimg vmlinux
make ARCH=x86 CROSS_COMPILE=/usr/lib/kpatch/kpatch-gcc\  KERNELVERSION=5.4.0-73-generic CONFIG_DEBUG_SECTION_MISMATCH=y KBUILD_BUILD_VERSION="82" LOCALVERSION= localver-extra= CFLAGS_MODULE="-DPKG_ABI=73" O=/home/XXXX/.kpatch/tmp/build-generic -j48 vmlinux modules
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
  GEN     Makefile
  DESCEND  objtool
  CALL    /home/XXXX/.kpatch/src/scripts/atomic/check-atomics.sh
  CALL    /home/XXXX/.kpatch/src/scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CHK     kernel/kheaders_data.tar.xz
  CC      fs/proc/version.o
  AR      fs/proc/built-in.a
  AR      fs/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
  LD      .tmp_vmlinux.kallsyms1
  KSYM    .tmp_vmlinux.kallsyms1.o
  LD      .tmp_vmlinux.kallsyms2
  KSYM    .tmp_vmlinux.kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  Building modules, stage 2.
  MODPOST 5495 modules
Debug: build-generic

After I git clone from this repository, compile, install, and run kpatch-build again as shown at the Readme.md, I get the patch .ko file in several seconds. :)

XXXX@XXXX:~$ kpatch-build -t vmlinux version.patch
Using cache at /home/XXXX/.kpatch/src
Testing patch file(s)
Reading special section data
readelf: Error: LEB value too large
readelf: Error: LEB value too large
Building original source
Building patched source
Extracting new and modified ELF sections
version.o: changed function: version_proc_show
Patched objects: vmlinux
Building patch module: livepatch-version.ko
SUCCESS

Thanks for your work so much!

**Comment by jpoimboe** [comment]
This sounds like an issue with the Ubuntu distro version of kpatch-build.  Please reopen if I'm mistaken.

Lately there seems to have been an uptick in the number of reported issues on Ubuntu.  Any contributions to improve Ubuntu support would be welcome.
