### ISSUE TITLE
kpatch: bug in core_loaded  function when determining whether kpatch.ko is loaded

### ISSUE THREAD

**Issue by xiejingf** [dynup/kpatch#1187]
kpatch.service exited abnormally during system boot. 

`systemd[1]: Starting "Apply kpatch kernel patches" ...
kpatch[1156]: loading core module: /usr/local/lib/kpatch/4.19.91.x86_64/kpatch.ko
kpatch[1156]: loading patch module: /var/lib/kpatch/4.19.91.x86_64/kpatch-3938029.ko
kpatch[1156]: loading patch module: /var/lib/kpatch/4.19.91.x86_64/kpatch-4148281.ko
kpatch[1156]: loading patch module: /var/lib/kpatch/4.19.91.x86_64/kpatch-4312241.ko
insmod core module:  /usr/local/lib/kpatch/4.19.91.x86_64/kpatch.ko
insmod : EROR: could not insert module  /usr/local/lib/kpatch/4.19.91.x86_64/kpatch.ko: File exists
kpatch: failed to load core module
kpatch.service: main process exited, code=exited, status=1/FAILURE
Failed to start "Apply kpatch kernel patches"
Unit kpatch.service entered failed state
kpatch.service failed
`

After analysis, we found that the core_loaded function in kpatch script can be wrong in some cases

core_loaded ()
{
      grep -q -e "T klp_enable_patch" -e "T kpatch_register" /proc/kallsyms
}

reading /proc/kallsyms can be inconsistent as this post mentioned ( [https://stackoverflow.com/questions/5713451/is-it-safe-to-parse-a-proc-file](url) )

In the other hand, I can reproduce the same issue when insmod & rmmod repeatedly, here is my test case:

one process, execute the folllowing command
 insert and remove bridge.ko repeatedly, just to manipulate the kallsyms file content
`
while true; do rmmod bridge; modprobe bridge; done
`

the other process, loop to check core_loaded value, following is my script:

!/bin/bash
BASE="$PWD"
COREMOD="/usr/local/lib/kpatch/$(uname -r)/kpatch.ko"
LOGFILE="$BASE/test.log"

core_loaded () {
        grep -q -e "T klp_enable_patch" -e "T kpatch_register" /proc/kallsyms
}

logger() {
    local to_stdout=${1:-0}
     tee -a "$LOGFILE"
}

warn() {
        echo "$(date) kpatch: $*" | logger
}

die() {
        warn "$@"
        exit 1
}

cleanup() {
        rmmod "$COREMOD" || die "failed to unload core module"
}

trap cleanup EXIT INT TERM HUP
while true
 do
         insmod "$COREMOD" || die "failed to load core module"
         if ! core_loaded; then
                die "core not loaded"
         fi
        rmmod "$COREMOD" || die "failed to unload core module"
done

the test script fails after printing 'core not loaded' within 1 min.

**Comment by guangmuzhu** [comment]
For `/proc/kallsyms`, `kallsyms_op` uses `pos`(like line number) as an iterator, without any lock of module load/unload. So if we cat/grep `/proc/kallsyms` on module unloading, and if the symbols of the module is before `kpatch_register`, the offset of `kpatch_register` will be reduced and the iterator may skip over it.

I suggest checking the output of installing kpatch.ko so we can find it's already installed in this case.

**Comment by euspectre** [comment]
> I suggest checking the output of installing kpatch.ko so we can find it's already installed in this case.

**Comment by euspectre** [comment]
@xiejingf : which version of kpatch tools are you using? Is it 'vanilla' version from this git repo or it has some custom patches? If so, which ones?

The problem itself looks very strange, I'll try to reproduce it with different kernels.

The boot-time log you have provided indeed shows that the script tried to load kpatch.ko twice, so, yes, it might have thought that kpatch.ko is not loaded while it was actually loaded. Whether it is a bug in the implementation of kallsyms or somewhere else, I do not know yet.

The kernel was 4.19.91, so, I guess, the distro was Debian or Debian-based?

**Comment by xiejingf** [comment]
> @xiejingf : which version of kpatch tools are you using? Is it 'vanilla' version from this git repo or it has some custom patches? If so, which ones?
> 
> The problem itself looks very strange, I'll try to reproduce it with different kernels.
> 
> The boot-time log you have provided indeed shows that the script tried to load kpatch.ko twice, so, yes, it might have thought that kpatch.ko is not loaded while it was actually loaded. Whether it is a bug in the implementation of kallsyms or somewhere else, I do not know yet.
> 
> The kernel was 4.19.91, so, I guess, the distro was Debian or Debian-based?

My test was based on kpatch-0.8.0,   kernel is a custom kernel based on 4.19.91 and the kallsyms implementation is same as upstream.

BTW, I will test on ubuntu or centos

**Comment by guangmuzhu** [comment]
> > I suggest checking the output of installing kpatch.ko so we can find it's already installed in this case.
> 
> I don't think this would be enough: 'kpatch' script needs to know whether kpatch.ko is loaded. It does not matter if it is not installed.

My mistake. What I said 'install kpatch.ko' is to insmod kpatch.ko. If the kpatch.ko is loaded before, the insmod would print 'File exists'. But after reading the source code of insmod and function `load_module()` in Linux kernel, I think it's not safe enough to make sure kpatch.ko loaded.

> The boot-time log you have provided indeed shows that the script tried to load kpatch.ko twice, so, yes, it might have thought that kpatch.ko is not loaded while it was actually loaded. Whether it is a bug in the implementation of kallsyms or somewhere else, I do not know yet.

Before discussing whether it's a bug or not, I'll try to explain what happened.

During system boot, the systemd will execute `kpatch load --all`. I have serval hotfix modules to load and the `kpatch` script would check core_loaded for each hotfix.
```shell
load_module () {
	local module="$1"

	if ! core_loaded; then
		if modprobe -q kpatch; then
			echo "loaded core module"
		else
			find_core_module || die "can't find core module"
			echo "loading core module: $COREMOD"
			insmod "$COREMOD" || die "failed to load core module"
		fi

		# Now that the core module has been loaded, set $SYSFS to the
		# correct value based on the loaded core module's ABI.
		init_sysfs_var
	fi

...

	"--all")
		for i in "$INSTALLDIR/$(uname -r)"/*.ko; do
			[[ -e "$i" ]] || continue
			load_module "$i" || die "failed to load module $i"
		done
		;;
```

And the `core_loaded()` checks `klp_enable_patch` and `kpatch_register` via `/proc/kallsyms`. Let's assume `klp_enable_patch` doesn't exist and kpatch.ko is loaded. Normally we'll see `kpatch_register` in `/proc/kallsyms`. However, systemd starts services in parallel so a kernel module may be in the process of deleting while `kpatch` is reading `/proc/kallsyms`. Unfortunately there is no lock in kernel for `/proc/kallsyms` to prevent output corruption.

Actually the Linux kernel uses seq_file for file operations and array index as iterator(Please read `kallsyms_op` and `module_get_kallsym()` for more details). I don't think it's a bug of kernel because the kernel may have no better choice. So in my opinion, the `/proc/kallsyms` is not reliable, especially during system boot with systemd.

**Comment by euspectre** [comment]
Yes, I understand that part about kallsyms.

I doubt, however, that many kernel modules are unloaded during the boot process, so something else might have made /proc/kallsyms unreliable.

If no better solution appears, we could allow the script to try to load kpatch.ko each time and ignore EEXIST errors.

Checking /sys/module/kpatch is probably not very reliable either.

**Comment by euspectre** [comment]
> My test was based on kpatch-0.8.0, kernel is a custom kernel based on 4.19.91 and the kallsyms implementation is same as upstream.

> BTW, I have tested on kernel 3.10 , centos distro, still can reproduce the same issue

I see. It would be interesting (but may be time-consuming) to try newer kernels, like 5.12. kallsyms subsystem is revisited from time to time and not all improvements there are eligible to stable kernel branches, I suppose.

**Comment by joe-lawrence** [comment]
> Checking /sys/module/kpatch is probably not very reliable either.

I'd think looking at the existence of /sys/module/kpatch would be safe than content inside /proc/kallsyms, right?  It's been a long time since I've had to use kpatch.ko, but does it create any other breadcrumbs, elsewhere in sysfs, that could be keyed on to determine that the support module is present?

Alternatively, I wonder why kpatch utility uses `insmod` and not `modprobe` to bring in kpatches?  Wouldn't the latter load any module dependencies first, and render a lot of that `if ! core_loaded` logic moot?

**Comment by euspectre** [comment]
> Alternatively, I wonder why kpatch utility uses insmod and not modprobe to bring in kpatches? Wouldn't the latter load any module dependencies first, and render a lot of that if ! core_loaded logic moot?

I don't know for sure, but, I guess, it would require to use depmod somehow to teach modprobe where to look for kpatch.ko and the patch modules. modprobe does not accept the full paths to the modules, or does it?

As patch modules could reside anywhere in the file system, using insmod directly seems easier.

**Comment by euspectre** [comment]
> I'd think looking at the existence of /sys/module/kpatch would be safe than content inside /proc/kallsyms, right?

May be. I vaguely remember some issues with lifetime of sysfs dirs/files for modules in the older kernels, but I can be mistaken here.

**Comment by euspectre** [comment]
> but does it create any other breadcrumbs, elsewhere in sysfs, that could be keyed on to determine that the support module is present?

Good question.
/sys/kernel/kpatch/ directory comes to mind. It is maintained by kpatch.ko, corresponds to its main kobject. This one is created during module_init() of kpatch.ko and removed in module_exit(), so it looks rather reliable.

**Comment by xiejingf** [comment]
> > but does it create any other breadcrumbs, elsewhere in sysfs, that could be keyed on to determine that the support module is present?
> 
> Good question.
> /sys/kernel/kpatch/ directory comes to mind. It is maintained by kpatch.ko, corresponds to its main kobject. This one is created during module_init() of kpatch.ko and removed in module_exit(), so it looks rather reliable.

/sys/kernel/kpatch/ directory  sounds good,  I have tested it for 1 hour, all is right so far.

**Comment by euspectre** [comment]
> do you have any concerns about this, if not, I will send a PR.
Checking /sys/kernel/kpatch/ seems OK to me. It should not affect the klp-based patches for the newer kernels either.

So, yes, please send the pull request. Thanks.

**Comment by xiejingf** [comment]
> So, yes, please send the pull request. Thanks.

please review my pull request #1192
