### ISSUE TITLE
create-diff-object: ERROR:couldn't find matching helloDev.c local symbols in helloDev symbol table

### ISSUE THREAD

**Issue by jinzhiyu1** [dynup/kpatch#1195]
[root@localhost jinzhiyu]# cat helloDev.patch 
--- test_cdev/helloDev.c	2021-06-23 10:47:15.290581340 +0800
+++ test_cdev/helloDev.c.new	2021-06-23 10:48:17.030581924 +0800
@@ -35,6 +35,11 @@
 
```
 ssize_t hello_read(struct file *f, char __user *u, size_t s, loff_t *l)
 {
+	int i = 0;
+	for(i = 0; i < 10; i++)
+	{
+		printk(KERN_INFO "i: %d\n", i);
+	}
 	return 0;
 }
```
[root@localhost jinzhiyu]# kpatch-build -s ./test_cdev/ -t all -e ./test_cdev/helloDev.ko helloDev.patch 
Using source directory at /home/jinzhiyu/test_cdev
Testing patch file(s)
Reading special section data
Building original source
Building patched source
ERROR: kpatch build failed. Check /root/.kpatch/build.log for more details.

 /root/.kpatch/build.log：
[root@localhost .kpatch]# cat /root/.kpatch/build.log 
checking file helloDev.c
patching file helloDev.c
make -C /lib/modules/4.19.190-2.el8.x86_64/build/ M=/home/jinzhiyu/test_cdev modules
make[1]: Entering directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
  CC [M]  /home/jinzhiyu/test_cdev/helloDev.o
/home/jinzhiyu/test_cdev/helloDev.o: warning: objtool: .text.unlikely.hello_init+0x0: stack state mismatch: cfa1=7+8 cfa2=7+16
  Building modules, stage 2.
  MODPOST 1 modules
  LD [M]  /home/jinzhiyu/test_cdev/helloDev.ko
make[1]: Leaving directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
checking file helloDev.c
patching file helloDev.c
make -C /lib/modules/4.19.190-2.el8.x86_64/build/ M=/home/jinzhiyu/test_cdev modules
make[1]: Entering directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
  CC [M]  /home/jinzhiyu/test_cdev/helloDev.o
/home/jinzhiyu/test_cdev/helloDev.o: warning: objtool: .text.unlikely.hello_read+0x0: stack state mismatch: cfa1=7+8 cfa2=7+24
/home/jinzhiyu/test_cdev/helloDev.o: warning: objtool: .text.unlikely.hello_init+0x0: stack state mismatch: cfa1=7+8 cfa2=7+16
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/jinzhiyu/test_cdev/helloDev.mod.o
  LD [M]  /home/jinzhiyu/test_cdev/helloDev.ko
make[1]: Leaving directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
/usr/local/libexec/kpatch/create-diff-object: ERROR: helloDev.o: find_local_syms: 181: couldn't find matching helloDev.c local symbols in helloDev symbol table

**Comment by jinzhiyu1** [comment]
**After add a printk sentence, unexpectedly build success:**

[root@localhost jinzhiyu]# cat helloDev.patch 
--- test_cdev/helloDev.c	2021-06-23 16:10:08.070963986 +0800
+++ test_cdev/helloDev.c.new	2021-06-23 16:14:11.139960214 +0800
@@ -31,6 +31,12 @@
 
 `ssize_t hello_read(struct file *f, char __user *u, size_t s, loff_t *l)
 {
+	printk(KERN_INFO "hello\n");
+	int i = 0;
+	for(i = 0; i < 10; i++)
+	{
+		printk(KERN_INFO "i: %d\n", i);
+	}
        
 	return 0;
 }`
 
[root@localhost jinzhiyu]# kpatch-build -s ./test_cdev/ -t all -e ./test_cdev/helloDev.ko helloDev.patch 
Using source directory at /home/jinzhiyu/test_cdev
Testing patch file(s)
Reading special section data
Building original source
Building patched source
Extracting new and modified ELF sections
helloDev.o: changed function: hello_read
Patched objects: helloDev.ko
Building patch module: livepatch-helloDev.ko
SUCCESS

**Comment by jpoimboe** [comment]
Is helloDev.c in the original kernel?  Or is it an out-of-tree module?

**Comment by jinzhiyu1** [comment]
An out-of-tree module.

**Comment by jinzhiyu1** [comment]
**I added some debugging information and found that when the condition (child->type==sym->type && child->name==sym->name) is false, this will cause the function locals_match to always return 0, eventually leading to ERROR, but I don’t know what these variables represent**
[root@localhost jinzhiyu]# cat /root/.kpatch/build.log 
checking file helloDev.c
patching file helloDev.c
make -C /lib/modules/4.19.190-2.el8.x86_64/build/ M=/home/jinzhiyu/test_cdev modules
make[1]: Entering directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
  CC [M]  /home/jinzhiyu/test_cdev/helloDev.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/jinzhiyu/test_cdev/helloDev.mod.o
  LD [M]  /home/jinzhiyu/test_cdev/helloDev.ko
make[1]: Leaving directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
checking file helloDev.c
patching file helloDev.c
make -C /lib/modules/4.19.190-2.el8.x86_64/build/ M=/home/jinzhiyu/test_cdev modules
make[1]: Entering directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
  CC [M]  /home/jinzhiyu/test_cdev/helloDev.o
/home/jinzhiyu/test_cdev/helloDev.o: warning: objtool: .text.unlikely.hello_read+0x0: stack state mismatch: cfa1=7+8 cfa2=7+24
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/jinzhiyu/test_cdev/helloDev.mod.o
  LD [M]  /home/jinzhiyu/test_cdev/helloDev.ko
make[1]: Leaving directory '/home/jinzhiyu/kernel/linux-4.19.190-2.el8.x86_64'
**Debug info: table->objname: helloDev, table->obj_nr: 25, table->exp_nr: 9154, hint: helloDev.c
Debug info: table->local_syms is NULL
Debug info: sym->type: 4
Debug info: sym->type: 4
Debug info: hint: helloDev.c
Debug info: child->type: 1, sym->type: 2, child->name: __UNIQUE_ID_license29, sym->name: hello_read.cold.2
Debug info: child->type: 1, sym->type: 2, child->name: __UNIQUE_ID_license29, sym->name: hello_read.cold.2
Debug info: locals_match: 0**
/usr/local/libexec/kpatch/create-diff-object: ERROR: helloDev.o: find_local_syms: 196: couldn't find matching helloDev.c local symbols in helloDev symbol table

**Comment by jpoimboe** [comment]
Out of tree module support is limited.  See the "Can you patch out-of-tree modules?" section in README.md.  It recommends the `--oot-module` flag.  I don't know if it still works.

**Comment by jinzhiyu1** [comment]
Thank you, I will read README.md carefully and try to use the flag later.

**Comment by jinzhiyu1** [comment]
I used the recommended flag, but the result was no difference. So in some cases, kpatch does not support out-of-tree modules? Why are the following two patches not much different, but one builds successed and the other failed?

-successed patch:

`--- test_cdev/helloDev.c	2021-06-24 14:33:54.079712879 +0800
+++ test_cdev/helloDev.c.new	2021-06-24 14:42:47.936704595 +0800
@@ -31,6 +31,12 @@
 
 ssize_t hello_read(struct file *f, char __user *u, size_t s, loff_t *l)
 {
+	printk(KERN_INFO "hello");
+	int i = 0;
+	for(i = 0; i < 10; i++)
+	{
+		printk(KERN_INFO "i: %d\n", i);
+	}
 	return 0;
 }
`

- failed patch:

`--- test_cdev/helloDev.c	2021-06-24 14:31:23.718715212 +0800
+++ test_cdev/helloDev.c.new	2021-06-24 14:33:38.423713122 +0800
@@ -31,6 +31,11 @@
 
 ssize_t hello_read(struct file *f, char __user *u, size_t s, loff_t *l)
 {
+	int i = 0;
+	for(i = 0; i < 10; i++)
+	{
+		printk(KERN_INFO "i: %d\n", i);
+	}
 	return 0;
 }
`

**Comment by jinzhiyu1** [comment]
I found the cause of the problem, sometimes target ko symbol table will generate *.cold or *.part symbol which can not find in orig ko. So I added these codes when foreach symbol ：
`if(strstr(sym->name, ".cold") || strstr(sym->name, ".part"))
			continue;`
It worked.

**Comment by jpoimboe** [comment]
@jinzhiyu1 I'm glad you found a solution that worked.  In general we don't have the bandwidth to support the patching of out-of-tree modules, but if you want to submit a pull request with the fix we can take a look at merging it.
