### ISSUE TITLE
Patch: turning on a CONFIG which is set for Ubuntu-built kernels

### ISSUE THREAD

**Issue by luckycat889** [dynup/kpatch#1208]
I think I have concluded that stock Ubuntu kernels are built with CONFIG_DEBUG_SECTION_MISMATCH=y.
This CONFIG controls whether or not '-fno-inline-functions-called-once' is set during compilation.
For 'kpatch' this is naturally important; I see instances where there is a long c file with a lot of 'static' functions in it called only once from a public function.
And if it's not too complex, the compiler will inline the function, UNLESS the above flag is on.
As anyone knows, this could pose problems for the kpatch tool

However, the perhaps strange thing is that it's not on in the .config file provided in the 'modules' package.
Instead look in the following files, using Ubuntu 21.04 as an example:

linux-5.11.0/debian/rules.d/0-common-vars.mk:255
...
kmake = make ARCH=$(build_arch) \
	CROSS_COMPILE=$(CROSS_COMPILE) \
	KERNELVERSION=$(abi_release)-$(target_flavour) \
	CONFIG_DEBUG_SECTION_MISMATCH=y \
	KBUILD_BUILD_VERSION="$(uploadnum)" \
	LOCALVERSION= localver-extra= \
	CFLAGS_MODULE="-DPKG_ABI=$(abinum)" \
	PYTHON=$(PYTHON)
ifneq ($(LOCAL_ENV_CC),)
kmake += CC="$(LOCAL_ENV_CC)" DISTCC_HOSTS="$(LOCAL_ENV_DISTCC_HOSTS)"
endif

linux-5.11.0/Makefile:914
...
ifdef CONFIG_DEBUG_SECTION_MISMATCH
KBUILD_CFLAGS += $(call cc-option, -fno-inline-functions-called-once)
endif

If one only uses linux-5.11.0/Makefile to build as kpatch does it, then this is not set. 
However, the debian-style scripts used during official builds, see https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel for a good reference, the build is kicked off with:
$ LANG=C fakeroot debian/rules binary
This is debian's way of building the kernel + a boatload of DKMS modules and debian packaging (This takes forever to build....thus not desired for kpatch)

The patch I suggest is the following:

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
index 186b725..53da76c 100755
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -703,6 +703,7 @@ elif [[ "$DISTRO" = ubuntu ]] || [[ "$DISTRO" = debian ]]; then
        fi
 
        export PATH="/usr/lib/ccache:$PATH"
+       export CONFIG_DEBUG_SECTION_MISMATCH=y
 fi
 
 find_dirs || die "can't find supporting tools"

I am not 100% this is the best home for this flag, but this spot makes it active for both Ubuntu and Debian builds.

**Comment by luckycat889** [comment]
Here is a file instead; since the inline got screwed up above
[ubuntu_patch.txt](https://github.com/dynup/kpatch/files/6983854/ubuntu_patch.txt)

**Comment by jpoimboe** [comment]
If I understand correctly, this sounds like a hack to work around the fact that Debian and Ubuntu are delivering the wrong .config.  I'd recommend trying to get it fixed in those distros.

That said, the hack seems confined to the Debian/Ubuntu portion of the kpatch-build script, so I don't have any objections if you want to submit a pull request.  We get very few contributions from the Ubuntu community and any efforts to improve kpatch there would be welcome.

**Comment by luckycat889** [comment]
Yes, I'd agree about the characterization of it being a 'hack', but it's a debian-style hack :)
The Debian/Ubuntu kernel source build system is quite a mix of shell, perl, python and make scripts, in addition to linux upstream, and I might understand the need for this abstraction, since it supports N architectures etc etc. However, I was a bit perplexed about the hidden config item in the makefile itself. I do not have a clue as to why it's put there, apart from some comments in the scripts elaborating on the fact that the builds is less dependent on the whims of the compiler. As you pointed out, why isn't this config generated into the .config file? Debian already has a quite elaborate way of generating .config based on 'policies', architectures etc.
Anyway, I might attempt to inquire about this in the Debian community (might take a while, this config item has been done this way at least since 14.04 I believe).
Yes, that's the idea, the debian-style config addition is safely enclosed within a Ubuntu/Debian portion.
I'd be happy to contribute to kpatch going forward.
Once I have 2F setup for my github (which seemingly is a requirement nowadays), I try to submit a MR
