### ISSUE TITLE
kpatch-build: ignores ERROR() from create-kpatch-module and create-klp-module

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1223]
As discovered in #1203, **kpatch-build** continues executing if **create-klp-module** or **create-kpatch-module** sets error status.  

In both cases, `check_pipe_status()` is called to try and catch a segfault condition (code 139), but the `ERROR()` macro in log.h sets `EXIT_STATUS_ERROR` which is not the same.  This can lead to **kpatch-build** reporting success when an error actually occurred.

**Comment by sm00th** [comment]
`check_pipe_status()` handles the segfault case, but it also writes down the commands exit-code into `rc` variable. In case of `create-diff-object` call this variable is then properly checked, but neither of module create calls do that. So we don't need to touch `check_pipe_status()` itself, but rather add exit-status handling code after those calls.
