### ISSUE TITLE
create-diff-object segfault

### ISSUE THREAD

**Issue by liu-song-6** [dynup/kpatch#1257]
We hit a weird segfault on create-diff-object with a simple patch (attached at the end). It happens for gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3), but not clang. After digging into it a little bit, I think it was caused by the following rela entry. 

```
readelf -W -r btf.o
...
0000000000025342  0000000c00000001 R_X86_64_64            0000000000000000 .text.btf_show_name + 0
000000000002534a  0000000c00000001 R_X86_64_64            0000000000000000 .text.btf_show_name + e0
0000000000025355  000001df00000001 R_X86_64_64            000000000000000c .LC3 + 14            <<<   this one
000000000002535e  0000000c00000001 R_X86_64_64            0000000000000000 .text.btf_show_name + e0
0000000000025366  0000000c00000001 R_X86_64_64            0000000000000000 .text.btf_show_name + 1c4
```

How should we fix this case?

Thanks,
Song

The patch:

```
diff --git a/include/linux/bpf_verifier.h b/include/linux/bpf_verifier.h
index 7a7be8c057f2..5fc160288fa0 100644
--- a/include/linux/bpf_verifier.h
+++ b/include/linux/bpf_verifier.h
@@ -566,9 +566,11 @@ static inline u32 type_flag(u32 type)
        return type & ~BPF_BASE_TYPE_MASK;
 }

+/* only use after check_attach_btf_id() */
 static inline enum bpf_prog_type resolve_prog_type(struct bpf_prog *prog)
 {
-       return prog->aux->dst_prog ? prog->aux->dst_prog->type : prog->type;
+       return prog->type == BPF_PROG_TYPE_EXT ?
+               prog->aux->dst_prog->type : prog->type;
 }

 #endif /* _LINUX_BPF_VERIFIER_H */
```

**Comment by jpoimboe** [comment]
I also see this seg fault on Fedora with GCC 11.2.1.  Looking...

**Comment by jpoimboe** [comment]
Ha.  This issue only happens with unstripped objects because the bad relocation is in a debug section.  But our unit test framework requires objects to be stripped, which removes the debug sections.  So maybe I can just skip the unit tests for this one ;-)

**Comment by liu-song-6** [comment]
> Ha. This issue only happens with unstripped objects because the bad relocation is in a debug section. But our unit test framework requires objects to be stripped, which removes the debug sections. So maybe I can just skip the unit tests for this one ;-)

Shall we just strip the debug section before running create-diff-object?

**Comment by jpoimboe** [comment]
We used to, but at least in the past there was a requirement to be able to debug (or run the 'crash' tool) with livepatch modules, in case something goes wrong at runtime.

**Comment by liu-song-6** [comment]
Got it. Thanks for the information and the quick fix.
