### ISSUE TITLE
integration tests: CONFIG_MODVERSIONS and linux-5.18.0/symvers-disagreement-FAIL.patch

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#1293]
The symvers-disagreement-FAIL.patch purposely modifies ABI for a few exported symbols to run through kpatch-build's exported symbol versioning checks.  See [Exported symbol versioning](https://github.com/dynup/kpatch/blob/master/doc/patch-author-guide.md#exported-symbol-versioning) for full details.  As such, it requires `CONFIG_MODVERSIONS=y` else the patch will be successfully built as there are no versions to compare.

I'm just adding a bug here in case someone else searches to figure why linux-5.18.0/symvers-disagreement-FAIL.patch might be failing when tested on a config without `CONFIG_MODVERSIONS=y` (looking at you Fedora).

**Comment by liu-song-6** [comment]
I got hit by missing CONFIG_MODVERSIONS this week. Shall we add a check in kpatch-build? Or better, shall we select with CONFIG_LIVEPATCH? (Maybe I should ask the second question in the mail list?)

**Comment by joe-lawrence** [comment]
> I got hit by missing CONFIG_MODVERSIONS this week. Shall we add a check in kpatch-build? Or better, shall we select MODVERSIONS with CONFIG_LIVEPATCH? (Maybe I should ask the second question in the mail list?)

Hi @liu-song-6 ,
- When you say you "got hit by missing CONFIG_MODVERSIONS", is that in reference to kpatch integration tests, or did you have to debug a kpatch that tweaked exported symbol abi?
- The kpatch integration tests assume the same result for all arches and configs.  Perhaps they could be made more aware of their environment.
- MODVERSIONS is a nice safety feature when building kpatches, but maybe there is other tooling that generates livepatches that can make do without it?  And/or some distros that would want to livepatch even without MODVERSIONS?

**Comment by liu-song-6** [comment]
> When you say you "got hit by missing CONFIG_MODVERSIONS", is that in reference to kpatch integration tests, or did you have to debug a kpatch that tweaked exported symbol abi?

I was trying to make kpatch-build work for a kernel without CONFIG_MODVERSIONS. kpatch-build works, but the patch cannot load. The fix was to reenable CONFIG_MODVERSIONS. 

I think we can have kpatch-build check whether CONFIG_MODVERSIONS is enabled. If it is not, kpatch-build fails. Is this reasonable?

**Comment by joe-lawrence** [comment]
> I was trying to make kpatch-build work for a kernel without CONFIG_MODVERSIONS. kpatch-build works, but the patch cannot load. The fix was to reenable CONFIG_MODVERSIONS.ing to make kpatch-build work for a kernel without CONFIG_MODVERSIONS. kpatch-build works, but the patch cannot load. The fix was to reenable CONFIG_MODVERSIONS.

Interesting, so setting CONFIG_MODVERSIONS alone fixed the kpatch.ko load, or did it help point out inadvertent symvers change?

> I think we can have kpatch-build check whether CONFIG_MODVERSIONS is enabled. If it is not, kpatch-build fails. Is this reasonable?

That would affect distros like Fedora, which probably aren't the best use case for kpatch, but certainly handy for development and testing.  How about a warning?

**Comment by liu-song-6** [comment]
> Interesting, so setting CONFIG_MODVERSIONS alone fixed the kpatch.ko load, or did it help point out inadvertent symvers change?

In this case, setting CONFIG_MODVERSIONS fixes the issue. 

> That would affect distros like Fedora, which probably aren't the best use case for kpatch, but certainly handy for development and testing. How about a warning?

A warning should also work. 

Thanks,
Song

**Comment by jpoimboe** [comment]
What error message did you see when the patch failed to load?  I'm trying to understand why enabling CONFIG_MODVERSIONS fixed it.
