### ISSUE TITLE
New error building patch for 6.2-rc2?

### ISSUE THREAD

**Issue by liu-song-6** [dynup/kpatch#1321]
While running some tests with latest upstream kernel, I got error like:
```
create-diff-object: ERROR: decompressor.o: kpatch_bundle_symbols: 241: symbol z_erofs_transform_plain at offset 16 within section .text.z_erofs_transform_plain, expected 0: Success
```
I think this is new, as I never seen it before. But I haven't looked into it. 
The test patch I used is (though I don't think it matters, any patch should trigger the same):
```
diff --git a/fs/erofs/decompressor.c b/fs/erofs/decompressor.c
index 51b7ac7166d9..a0f594c9733a 100644
--- a/fs/erofs/decompressor.c
+++ b/fs/erofs/decompressor.c
@@ -236,6 +236,9 @@ static int z_erofs_lz4_decompress_mem(struct z_erofs_lz4_decompress_ctx *ctx,
        if (IS_ERR(src))
                return PTR_ERR(src);

+       if (src)
+               return PTR_ERR(-EAGAIN);
+
        /* legacy format could compress extra data in a pcluster. */
        if (rq->partial_decoding || !support_0padding)
                ret = LZ4_decompress_safe_partial(src + inputmargin, out,
--
2.30.2
```

**Comment by liu-song-6** [comment]
[config-6.2-rc2.txt](https://github.com/dynup/kpatch/files/10362652/config-6.2-rc2.txt)

The config used in the test.

**Comment by liu-song-6** [comment]
```
			if (sym->sym.st_value != 0 &&
			if (sym->sym.st_value != 0x10 &&
```
I think this breaks it on older kernels. And the error message in the line 244 needs update. 

Somehow, I am getting sym->sym.st_value of 0 now, even with 6.2-rc2... I am not sure what was changed.

**Comment by joe-lawrence** [comment]
> ```
> 			if (sym->sym.st_value != 0 &&
> 			if (sym->sym.st_value != 0x10 &&
> ```
> 
> I think this breaks it on older kernels. And the error message in the line 244 needs update.
> 
> Somehow, I am getting sym->sym.st_value of 0 now, even with 6.2-rc2... I am not sure what was changed.

Right it that commit was just hacked together for testing.  A real fix would probably need to key off arch and kernel version and indicate to create-diff-object what the nop padding size should be (if any).  You could probably make the condition check 0 or 0x10 offset if that moves you forward.

**Comment by liu-song-6** [comment]
I have got st_value == 0 for some functions, and st_value == 0x10 for some other functions. I guess we do need 0 for 0x10 here.

**Comment by joe-lawrence** [comment]
Yeah, I notice that some/all? '.cold' functions don't get the padding, so there are definitely multiple offsets we'll need to handle.

**Comment by joe-lawrence** [comment]
A second attempt: https://github.com/dynup/kpatch/commit/a3f3688c39309a73ec5d2cf5b1a2465e3226426e is more flexible in that it accounts for any amount of NOP padding on x86.   That should retain backwards compat and keep the unit tests happy.

**Comment by liu-song-6** [comment]
I am getting
```
ERROR: multiple parent matches for raid10.o: drivers/md/built-in.a drivers/md/raid10.mod.
```
For a simple patch:
```
---
 drivers/md/raid10.c | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/drivers/md/raid10.c b/drivers/md/raid10.c
index 3aa8b6e11d58..5c1e95892b93 100644
--- a/drivers/md/raid10.c
+++ b/drivers/md/raid10.c
@@ -4298,6 +4298,9 @@ static void raid10_free(struct mddev *mddev, void *priv)
 {
        struct r10conf *conf = priv;

+       if (!conf)
+               return;
+
        mempool_exit(&conf->r10bio_pool);
        safe_put_page(conf->tmppage);
        kfree(conf->mirrors);
--
2.30.2
```

**Comment by swine** [comment]
I'm guessing you have recently changed RAID10=m to =y (or reverse) w/o make
clean, and one of those parents is itself now an orphan, not mentioned in
any *.{o,a,ko}.cmd

I suspect this is a situation that can come up pre-6.2 too, even before
Josh's rewrite of the parent-tracking for 5.19 .o.cmd changes

**Comment by joe-lawrence** [comment]
I agree w/ @swine.  I could repro the same ancestor problem as I was adding .config options, starting with the =m, then moving on to grabbing @liu-song-6 's entire attached config.  Only after doing a make clean and make mrproper, the error went away.

**Comment by liu-song-6** [comment]
Yeah, the error went away after `make clean`. Sorry about the noise.
