### ISSUE TITLE
Regarding "statically allocated data" again

### ISSUE THREAD

**Issue by zegao96** [dynup/kpatch#1373]
Hi @jpoimboe ,

I'm studying how kpatch (and the kernel part) works  and kinda baffled by "Patches which modify statically allocated data are not directly supported. kpatch-build will detect that and return an error. " , one of the limitations that's posted.  By "modify", does this refer to "changing the data layout or just accessing (read/write)?

Regarding KLP and its consistency model,  IIUC any patched function with global semantic needs manual inspection for correctness,  no matter if it refers to statically allocated or dynamically allocated variables.  And here kpatch-build claims that it would detect "statically allocated data" case  specially, I wonder how it works? Does it achieve this by just rejecting any relocations against statically global vars in the patched function if i understand "modify" correctly?

Will be much appreciated if you help to clear my doubts. :) 

Thanks!

**Comment by jpoimboe** [comment]
This refers to data which is allocated and initialized at compile time.  For example, if the patch causes any changes to the .data section, kpatch-build will detect that and throw an error.

**Comment by zegao96** [comment]
> This refers to data which is allocated and initialized at compile time. For example, if the patch causes any changes to the .data section, kpatch-build will detect that and throw an error.

Thanks for your elaboration.  So it's not about global data references here but rather .data section changes, seems like i overthink a little bit. :)
