### ISSUE TITLE
Get rid of the stop_machine from kpatch

### ISSUE THREAD

**Issue by mhiramathitachi** [dynup/kpatch#138]
Since the ```stop_machine()``` stops all CPUs at a while, it is not good for some mission critical systems which are the main target of live patching. Thus, we need to apply patch without ```stop_machine()```. The main reason why kpatch requires that is to check the activity of the target functions, in other words, to ensure the target function is NOT in use when patching.

To solve this issue without ```stop_machine()```, I'd like to propose new approach, which directly checks the target functions are in use by using ftrace and kretprobes. Of course, we still need a stack dump checking too.

The basic idea is simple: increment counter at the entry of the function and decrement it at the return of the function. After checking stacks of all processes, if we see the counter is 0, that is safe and go live patching. If not, no go. Moreover, we can also add a latency period after checking the stacks. While the period, if the counter decremented to 0, it can go patching.

To implement the trick, we use ```atomic_inc_not_zero()``` and ```atomic_dec_not_zero()```. So the reference value of the counter will be 1.
Here is the patching-side concept code. I'm sure it is very simple.

```c
atomic_t counter;
ftrace_handler() {
  func = kpatch_get_func();
  if (func->updating) {
    ret = atomic_inc_not_zero(&counter);
    if (ret != 0)
       func = kpatch_get_committed_func(); /* we're under checking, use only committed one*/
    else {
       /* we've already checked and it is safe to apply patch */
    }
  }
  if (func)
    regs->ip = func->ip;
}

kretprobe_handler() {
  ret = atomic_dec_not_zero(&counter);
  if (ret == 1 and we already checked all stacks) {
    atomic_cmpxhg(&counter, 1, 0); /* Try to fix the state 1 -> 0 */
  }
}
```

Note that actually using kretprobes on NMI is not safe now in upstream kernel, so I need to fix that. And also, kretprobes can fail to hooking function return. Anyway, in that case the ```counter``` just never reach to 1. Thus we need to set a timer to give it up.

Additional discussion point of this method is that we'd better support incremental binary patch, because it becomes hard to find the point that all target functions are not in use if the number of target function is increased.

Thank you,

**Comment by jpoimboe** [comment]
I think we can close this issue.  kpatch.ko can continue to use stop_machine until it retires (when livepatch closes the feature gap).
