### ISSUE TITLE
fair.o: changed section .data..read_mostly not selected for inclusion

### ISSUE THREAD

**Issue by wardenjohn** [dynup/kpatch#1399]
When I use a patch to build a livepatch, I found this error happens:
```
fair.o: changed section .data..read_mostly not selected for inclusion
```
I looked into the code of create-diff-object and found that if one section is taged as CHANGED but this sec->include is not set,
this error will raise.

Which section will be included?
I found the section and symbol will be included:
1. standard element. eg, .shstrtab, .strtab, etc.
2. string literal section. For example,.rodata.* section or .str section
3. call back sections
4. force sections
5. debug sections

I am sorry that I have some base concept question to ask:
1. for the section which will call kpatch_include_section to include, the symbol type is STT_SECTION and the section status is CHANGED. But why this problem raised? From my point of view, since this section is not a section as mentioned above, it seems to be a normal section. It changed, but why not included?
2. I found kpatch-build have function to reorder symbols.  What is the reason why we need to reorder the symbols?
3. I found that kpatch-build need the information of some exported struct size link alt_instr size,jump_str size. I seems not to find the usage of these structer size in create-diff-object while create-diff-object read it **_group_size functions. How to use it?

Thanks for answering my question, and thank your time, again.

Regards,
Wardenjohn

**Comment by joe-lawrence** [comment]
Hi @wardenjohn 

1. Why we don't include .data..read_mostly section changes? kpatch_verify_patchability() specifically looks for changes to any ".data" prefixed section (amongst others).  Changes to data sections are not supported as kpatch can't safely apply those changes to a live system.  For example, how to modify a static variable?  There may be mutual exclusion issues, data type changes, etc.
2. Why do we need kpatch_reorder_symbols()?  kpatch-build generates a new elf output file comprised of original vs. patched object code differences.  This new file may have altered section, relocations, symbol information, etc.  This function sorts the symbols them as per ld linker (and probably ELF spec) expectations.
3. How does kpatch-build use kernel struct sizes in special sections?  Just look for the "group_size" variable across create-diff-object.c.

**Comment by wardenjohn** [comment]
Thank you joe @joe-lawrence !
I am still learning the techology of kpatch-build and still a long way to go.
Hoping can become a member of this community as fast as possable! :)

**Comment by wardenjohn** [comment]
@joe-lawrence I have some futher question for answer.

For answer 1, kpatch_verify_patchability() will make sure .data.* section will not be included. However, `changed section is not selected for inclusion` is not raise in this case. It seems that this section is changed but the include flag is not set.
It is not the situation that kpatch_verify_patchability not allow any data section change. 

In my scenario, this section's flag is not set to be include even it is changed. Is that a bug?

**Comment by joe-lawrence** [comment]
Hi @wardenjohn : can you (re)build this patch with kpatch-build `-d` debugging option, then create and attach a tarball of the following files from ~/.kpatch (most of these should be under ~/.kpatch/tmp/...)

* kpatch-build.env
* Module.symvers
* ORIG.o
* PATCHED.o
* vmlinux.symtab

Seeing the input kpatch would be helpful as well if you can post that.   (GitHub should let you attach files directly in an issue comment.)  Thanks.

**Comment by wardenjohn** [comment]
Hi joe, @joe-lawrence 
I will rebuild for a check. But I am not sure my organization if they allow me to up a the built object.
I need some time to check.

**Comment by wardenjohn** [comment]
@joe-lawrence Hi, bro!
I read the README.md of kpatch-build project and found that we can talk in web.libera chat. It very interesting if we can chat on line.
I join https://web.libera.chat/ under kpatch channel.
![image](https://github.com/dynup/kpatch/assets/33785009/4e94788e-8c71-4955-a9e0-a58e8767f810)
but found nobody in the channel chating.
Am I joined the wrong channel?
Thank you very much!

**Comment by joe-lawrence** [comment]
We should probably remove this from the docs as I think most people have sunset IRC.  I know I don't even have a client installed after the N-th chat protocol was adopted at work.

**Comment by wardenjohn** [comment]
@joe-lawrence I am afraid that there may be some difficulty for me to upload this file (and I found I loss that patch ... lol.. sorry, bro T_T) .

Can you tell me how to analysis this problem at the start? May be the next time I met this problem again, I can analysis it first and later submit some more useful information in github. If necessary, I can raise an other issuse.

Thank you , Joe !

**Comment by joe-lawrence** [comment]
> Can you tell me how to analysis this problem at the start?

If you can't share generated object or input kpatch code due to licensing reasons, then the next-best thing would be a minimal reproducer.

 For example, with the kernel/sched/fair.c file, I would think changing this value would provoke the $SUBJECT error message:
```C
static unsigned long __read_mostly max_load_balance_interval = HZ/10;
```
Of course, the root cause may not be as obvious, in which case, you might try abstracting your kpatch changes to simple `nop()` calls.  This would allow you to systematically search to see if there is a particular function that is driving the error (perhaps it references a ready-mostly data value.)

If neither of those approaches are successful, you could always run create-diff-object through the gdb debugger.  (Hint, build with the --skip-cleanup option and source the ~/.kpatch/tmp/kpatch-build.env to export necessary kernel structure sizes.)
