### ISSUE TITLE
can't access module-created percpu variables

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#442]
When patching a module, the dynamic relocation code can't find percpu variables that were created by modules.  The following patch:

```
$ cat /tmp/percpu.patch
Index: src/arch/x86/kvm/vmx.c
===================================================================
--- src.orig/arch/x86/kvm/vmx.c
+++ src/arch/x86/kvm/vmx.c
@@ -7538,6 +7538,8 @@ static struct kvm_vcpu *vmx_create_vcpu(
    struct vcpu_vmx *vmx = kmem_cache_zalloc(kvm_vcpu_cache, GFP_KERNEL);
    int cpu;

+   printk("foo\n");
+
    if (!vmx)
        return ERR_PTR(-ENOMEM);

```

Results in the following error when loading:

```
[ 2825.026626] kpatch: unable to find symbol 'vmxarea'
```

Unlike vmlinux-created percpu variables, module-created percpu variable offsets are apparently not added to kallsyms.

**Comment by euspectre** [comment]
Are there any updates on this one?

I've also hit this problem recently when trying to prepare a binary patch from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=06bd3c36a733ac27962fea7d6f47168841376824. The patch was for a custom kernel where there is an additional percpu variable in ext4 (fs/ext4/inode.c), `ext4_bd_full_ratelimits`. The build process went fine but loading of the patch failed with

```
kpatch: symbol 'ext4_bd_full_ratelimits' not found in symbol table
kpatch: unable to find symbol 'ext4_bd_full_ratelimits'
```

in dmesg.

If this cannot be fixed without changes in the upstream kernel, perhaps, kpatch-build could be enhanced to detect such things when it is building the binary patch and report an error?

**Comment by jpoimboe** [comment]
Hm, the original patch seems to load for me now on a Fedora 4.10 kernel.  Maybe this has been fixed upstream?

**Comment by jpoimboe** [comment]
@flaming-toast Any idea how/when this was fixed?  It would be interesting to know if this issue still exists on RHEL 7.

**Comment by euspectre** [comment]
It might be because, it seems, neither mainline kernel nor RHEL7 kernels have that percpu variable in inode.c, so you did not hit the problem. Unfortunately, the custom kernel I worked with, does have it.

**Comment by flaming-toast** [comment]
@jpoimboe Access to module percpu symbols via kallsyms was fixed in upstream commit e0224418516b4d8a6c2160574bac18447c354ef0 ("module: keep percpu symbols in module's symtab").

**Comment by flaming-toast** [comment]
@euspectre You may need to backport the above fix for your custom kernel. Does your custom kernel have Miroslav's fix? See: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e0224418516

**Comment by euspectre** [comment]
@flaming-toast Thanks a lot!

The kernel I experimented with was based on the one from RHEL 7 / CentOS 7 and did not have this fix yet. I will try it.

**Comment by euspectre** [comment]
Yes, that upstream patch helps. The binary patch now loads OK into the updated kernel.

Thanks for the hint!
