### ISSUE TITLE
[RFC] provide more information in hotfix kernel module

### ISSUE THREAD

**Issue by gnehzuil** [dynup/kpatch#471]
Now after using kpatch-build to build a hotfix kernel module as README.md described, a kpatch-meminfo-string.ko kernel module will be generated.  But in a product system, it should have a lot of hotfix kernel module, and it's quite hard for us to identify the functionality of a hotfix kernel module and manage these hotfix kernel modules.

I propose to add a description file for a hotfix kernel module when this kernel module is built.  For example, we could add a new argument called '--description' in kpatch-build, and this description will be written into a description file.  After building kernel module, the description file and kernel module will be compressed into a kpatch-${SHA1}.tar.gz file, which shall be distributed.  When the user wants to load a hotfix kernel module, kpatch tool will be executed and this tarball will be decompressed into /var/lib/kpatch/$(uname -r)/available/kpatch-$(SHA1)/ and kernel module will be loaded.  In the mean time, the user can run kpatch info to get description of this hotfix.

Regards,
                                        - Zheng

**Comment by jpoimboe** [comment]
@gnehzuil ping?
