### ISSUE TITLE
silentoldconfig fails

### ISSUE THREAD

**Issue by devonblzx** [dynup/kpatch#483]
When a patch introduces a new option in the kernel config, the build fails due the 'make silentoldconfig' aborting.  How can we force kpatch to use 'make olddefconfig'.

Once would assume that using kpatch-build -c to specify the new config file would work, but this also fails with the same error.  It seems like when kpatch is building the original kernel, it overwrites this config so all the new options are removed.

**Comment by jpoimboe** [comment]
Thus far we've always assumed that the config file doesn't change.  The -c option also makes that assumption.  kpatch is really designed for patching small bug fixes which don't change the kernel config.

Config changes can result in completely different files getting built, changed compiler flags, etc.  I think it would be pretty hard to add proper support for it, and I'm not really convinced it makes sense to do so, given the scope of kpatch.

**Comment by devonblzx** [comment]
Okay, thank you for filling me in.  I was trying to use kpatch for minor version upgrades with the upstream kernel.  Looks like kexec may be better for that, the only downside is kexec requires checkpointing all running processes (small downtime) while kpatch does not.

**Comment by jpoimboe** [comment]
Yeah, kexec + criu is definitely a better fit for that use case.
