### ISSUE TITLE
Can we use kpatch to do recurisive patch?

### ISSUE THREAD

**Issue by stevensyy** [dynup/kpatch#487]
Hi,  my question is can we use kpatch to patch the same function based on the patched kernel?

say if i modify fs/proc/version.c and generate kpatch-version.ko then load it into the kernel ,

can I  again modify version.c based on the already patched source code and then generate kpatch-version_1.ko 

Does it work if i load this kpatch-version_1.ko into the kernel which already has kpatch-version.ko?

Best regards
                                stevensyy

**Comment by jpoimboe** [comment]
Currently kpatch doesn't have a way to build a 2nd patch against a patched kernel source (which already includes the 1st patch).  Properly detecting and managing dependencies between patches is extremely tricky, so currently we don't even try to do it.

But you _can_ build the 2nd patch against the _original_ kernel source.  You just have to be careful that there are no unforeseen side effects between the two patches.

When doing multiple patches, I think the safest approach is for them to be cumulative.  So I'd recommend that the second patch be a superset of the first patch.  And then use "kpatch replace" to atomically replace the old one with the new one.
