### ISSUE TITLE
Don't require to run the kernel to patch

### ISSUE THREAD

**Issue by vincentbernat** [dynup/kpatch#495]
Hi!

As far as I understand, kpatch-build is only using the running kernel to get some information like its version. If this is really the case, this information could be provided on the command-line and running the kernel to patch could not be required. Is that correct?

**Comment by spartacus06** [comment]
There are two options for building patches for a non-running kernel; --sourcerpm and --sourcedir.  sourecdir is probably what you wanting to use.  If you have a built kernel source tree (you ran "make"), you can pass that to kpatch-build using --sourcedir and it will build the patches against that kernel version, using the vmlinux and .config and other required files from that tree.

**Comment by vincentbernat** [comment]
Thanks! It works just fine. I am also able to build kpatch itself with `KPATCH_BUILD` set to the right location.

**Comment by spartacus06** [comment]
Cool! Glad you got it figured out.  Ok to close?

**Comment by vincentbernat** [comment]
Yes!
