### ISSUE TITLE
load/unload hooks for livepatch

### ISSUE THREAD

**Issue by arges** [dynup/kpatch#501]
kpatch has load/unload hooks for kpatch modules. This feature would also be nice to have in livepatch module.

**Comment by jpoimboe** [comment]
Agreed, and we are planning it.  That said, I'd really like to get a consistency model merged before adding any significant features like this to livepatch.

**Comment by jpoimboe** [comment]
The goal of livepatch is to eventually make kpatch.ko obsolete.  So after the consistency model is merged upstream, we're definitely planning this, and all other features which will close the feature gap.

However I'd rather not use the kpatch github to track all the missing livepatch features.  Rest assured it will get done before we retire kpatch.ko :-)
