### ISSUE TITLE
ERROR: kpatch_find_static_twin: 1231: found another static local variable matching xxx.17486

### ISSUE THREAD

**Issue by zhouchengming1** [dynup/kpatch#514]
My original code is :

void function(void) {
    {
         static int xxx;
         /* do something */
    }
    {
         static long xxx;
         /* do something */
    }
}

Then I add a new function before this function, and use kpatch-build to create a hot-patch, 
but report an error as the title.

So I dive into the code, find the two static local variables both changed its name:
xxx.17478  --->  xxx.17486
xxx.17483  --->  xxx.17497

When the function " kpatch_find_static_twin " find twin for xxx.17486, it report the error because it find another static local variable xxx.17497.

So how to handle this situation ? Please help...

**Comment by jpoimboe** [comment]
Yes, it doesn't currently handle the situation where there are two static local variables with the same name in the same function.  If you're not patching the function you can tell kpatch-build to ignore it with the KPATCH_IGNORE_FUNCTION macro.

**Comment by zhouchengming1** [comment]
Thanks, perhaps this is the only solution now.

**Comment by jpoimboe** [comment]
Another issue with the static local variable handling is that static local symbols are correlated by name before the static-specific correlation logic runs.  For example, if the following two symbols changed their name:

xxx.17478 ---> xxx.17483
xxx.17483 ---> xxx.17497

It will incorrectly correlate the two xxx.17483 symbols.

Working on a rewrite of the static local variable handling to deal with these issues properly.

**Comment by jpoimboe** [comment]
@zhouchengming1 Can you check if the patch in #535 fixes your issue?

**Comment by jpoimboe** [comment]
@zhouchengming1 Please disregard my question, the patch still needs some work.
