### ISSUE TITLE
kASLR support

### ISSUE THREAD

**Issue by cbay** [dynup/kpatch#540]
Is kASLR supported? When it's enabled, I get:

    livepatch: symbol 'arch_report_meminfo' not found at specified address 0xffffffff81058000, kernel mismatch?

Indeed:

    # zgrep arch_report_meminfo /proc/kallsyms
    ffffffff95058000 T arch_report_meminfo

When booting with `nokaslr`, it works fine. Tested on Linux 4.3 and 4.1.

**Comment by jpoimboe** [comment]
It's not currently supported, but it would be a nice feature to add.

**Comment by cbay** [comment]
Thanks. In the meantime, a note in the README might be helpful.

**Comment by zhouchengming1** [comment]
It's a bug in livepatch, not kpatch-build.
When enable KASLR, func->old_addr will be set to zero
and livepatch will find the right old address.
But for reloc, livepatch just verify it using reloc->val (old addr from user), 
so verify failed and report “kernel mismatch" error.
I've modified the code of livepatch, can I send a patch later ?

**Comment by cbay** [comment]
I'm ready to test a patch if you have one.

**Comment by zhouchengming1** [comment]
ok, I will send a patch to lkml and copy to you soon. Thanks.

**Comment by jpoimboe** [comment]
Ah @zhouchengming1, you're right.  I mistakenly thought this issue was reported against kpatch.ko.  Generally we try to only track kpatch issues here.

**Comment by zhouchengming1** [comment]
@jpoimboe , oh, I know.

**Comment by zhouchengming1** [comment]
@cbay , you still get the 'symbol not found in symbol table' error ?

**Comment by zhouchengming1** [comment]
@cbay , this patch is on top of linux-4.1, I will make one on top of linux-4.3 later, maybe will solve your error. Thanks.

**Comment by cbay** [comment]
@zhouchengming1 It fails on Linux 4.1.12 as well:

    livepatch: symbol 'arch_report_meminfo' not found in symbol table

This is the patch I'm testing:

```
diff -ru linux-source-4.1/fs/proc/meminfo.c linux-source-4.1~/fs/proc/meminfo.c
--- linux-source-4.1/fs/proc/meminfo.c  2015-10-03 13:52:18.000000000 +0200
+++ linux-source-4.1~/fs/proc/meminfo.c 2015-11-01 15:32:53.201668272 +0100
@@ -134,7 +134,7 @@
                "Committed_AS:   %8lu kB\n"
                "VmallocTotal:   %8lu kB\n"
                "VmallocUsed:    %8lu kB\n"
-               "VmallocChunk:   %8lu kB\n"
+               "VMALLOCCHUNK:   %8lu kB\n"
 #ifdef CONFIG_MEMORY_FAILURE
                "HardwareCorrupted: %5lu kB\n"
 #endif
```

**Comment by zhouchengming1** [comment]
@cbay , it's a little strange. I think I'd better test myself before ask you.
Thanks.

**Comment by zhouchengming1** [comment]
@cbay , I just did a test myself. With the patch I just sent, there was no problem.
Can you test the new patch and let me know if it works?

**Comment by cbay** [comment]
@zhouchengming1 I've just tested on Linux 4.3, it works fine. Thanks!
