### ISSUE TITLE
Can kpatch also be used in CentOS 6.6?

### ISSUE THREAD

**Issue by blade1989** [dynup/kpatch#577]
Sorry, if this is not the place to ask, but does kpatch also support CentOS 6.*?

Also, is this a "stable" product. Meaning can this be used on a production machine?

**Comment by jpoimboe** [comment]
kpatch doesn't work on CentOS 6 because it's missing the ftrace feature which kpatch relies on.

I do consider it stable for production use, but only if you're very careful with your patch analysis.

FYI the kpatch mailing list is probably a better place to ask general questions.
