### ISSUE TITLE
Can kpatch work with kernel 4.x?

### ISSUE THREAD

**Issue by luceneli** [dynup/kpatch#586]
I am using self compiled kernel 4.x on CentOS 7 and I know kernel 4.x supports livepatch, Does kpatch work with kernel 4.x? Do I need extra change for kpatch to work with 4.x?

**Comment by flaming-toast** [comment]
You shouldn't have any issues using kpatch with 4.x kernels. The kpatch-build tools should build the correct patch module depending on whether `CONFIG_LIVEPATCH` is enabled or not. Feel free to comment if you run into issues.

**Comment by flaming-toast** [comment]
Closing, if there aren't any other issues.

**Comment by JohnMHarrisJr** [comment]
This seems to be relevant again, after https://github.com/torvalds/linux/commit/c8fe4609827aedc9c4b45de80e7cdc8ccfa8541b

**Comment by jpoimboe** [comment]
@JohnMHarrisJr Yeah, and unfortunately there are also some other problems with kernels >= 4.7.  We're working on getting them fixed soon.  The issues I know of: #607, #623, and #620 (Fedora 24/25).
