### ISSUE TITLE
kpatch-build with -t argument only builds patch modules with partial Module.symvers

### ISSUE THREAD

**Issue by flaming-toast** [dynup/kpatch#589]
Documenting the bug found in issue #587, since the `-t` target argument only compiles the relevant portion of the kernel, only a partial Module.symvers gets generated, which is then compiled with the patch module. The full Module.symvers needs to be used instead.

**Comment by vincentbernat** [comment]
Except not using `-t`, is there a more efficient workaround for this problem?

**Comment by jpoimboe** [comment]
Not that I know of.  Use of `-t` isn't really recommended, pretty much "use at your own risk".

**Comment by jpoimboe** [comment]
I think there are some improvements we can make here:

- Somehow detect and report an error when Module.symvers is truncated/incomplete.
- Save/restore Module.symvers during kpatch-build script init/cleanup
  - Or even better, remove the make mrproper, as being discussed in #848.  This makes using the '-t' flag to build modules so much faster (and more reliable)
