### ISSUE TITLE
Got an error while building kpatch

### ISSUE THREAD

**Issue by bluezd** [dynup/kpatch#593]
CC [M]  /root/kpatch/kpatch/kmod/core/core.o
/root/kpatch/kpatch/kmod/core/core.c:47:28: fatal error: asm/stacktrace.h: No such file or directory

The kernel version is 3.10.0-327 in CentOS 7, and I have already installed the kernel-devel and debuginfo packages.

Could anybody have a look at it ?

I have another question about kpatch, in CentOS src rpm, under rpmbuild/SOURCES/centos-kpatch.x509, this public key would be built in the kernel, and the kernel will load it during startup:
my question is what is the purpose of the kpatch.x509 ?

Thanks !

**Comment by jpoimboe** [comment]
> CC [M] /root/kpatch/kpatch/kmod/core/core.o
> /root/kpatch/kpatch/kmod/core/core.c:47:28: fatal error: asm/stacktrace.h: No such file or directory
> 
> The kernel version is 3.10.0-327 in CentOS 7, and I have already installed the kernel-devel and debuginfo packages.

What do you see with the following?
```
ls -l /lib/modules/$(uname -r)/build/arch/x86/include/asm/stacktrace.h
```
That file should be provided by the `kernel-devel` RPM.

> I have another question about kpatch, in CentOS src rpm, under rpmbuild/SOURCES/centos-kpatch.x509, this public key would be built in the kernel, and the kernel will load it during startup:
> my question is what is the purpose of the kpatch.x509 ?

I don't have any involvement with the CentOS source RPM, but I'd guess those files are related to building signed kernel modules.

**Comment by bluezd** [comment]
Thanks for your reply!

>
> CC [M] /root/kpatch/kpatch/kmod/core/core.o
> /root/kpatch/kpatch/kmod/core/core.c:47:28: fatal error: asm/stacktrace.h: No such file or directory
>
> The kernel version is 3.10.0-327 in CentOS 7, and I have already installed the kernel-devel and debuginfo packages.
>
> What do you see with the following?
>
> ls -l /lib/modules/$(uname -r)/build/arch/x86/include/asm/stacktrace.h

No such file or directory

# uname -m
ppc64le

It works properly under X86_64 platform.

>
> That file should be provided by the kernel-devel RPM.

Yes, I have already installed it.

>
> I have another question about kpatch, in CentOS src rpm, under rpmbuild/SOURCES/centos-kpatch.x509, this public key would be built in the kernel, and the kernel will load it during startup:
> my question is what is the purpose of the kpatch.x509 ?
>
> I don't have any involvement with the CentOS source RPM, but I'd guess those files are related to building signed kernel modules.
>

As far as I know, kernel will generate its own x509 public and private
certificate files by using x509.genkey configuration file during
kernel building, and kernel will load the corresponding public x509
file for signing the kernel modules, not the kpatch.x509 file. So I
got confused here what's the exact purpose of the kpatch.x509 public
file. For decoding the signed kpatch kernel modules ? But the kernel
do not contain the paired private key files. Any other thoughts about
it ?


-- 
Best Regards,
Dong Zhu

**Comment by bluezd** [comment]
Thanks for your reply!

What do you see with the following?
>
> ls -l /lib/modules/$(uname -r)/build/arch/x86/include/asm/stacktrace.h
>
>
No such file or directory
# uname -m
ppc64le

It works properly under X86_64 platform.

>  That file should be provided by the kernel-devel RPM.
>
Yes, I have already installed it.


> I have another question about kpatch, in CentOS src rpm, under
> rpmbuild/SOURCES/centos-kpatch.x509, this public key would be built in the
> kernel, and the kernel will load it during startup:
> my question is what is the purpose of the kpatch.x509 ?
>
> I don't have any involvement with the CentOS source RPM, but I'd guess
> those files are related to building signed kernel modules.
>

As far as I know, kernel will generate its own x509 public and private
certificate files by using x509.genkey configuration file during kernel
building, and kernel will load the corresponding public x509 file for
signing the kernel modules, not the kpatch.x509 file. So I got confused
here what's the exact purpose of the kpatch.x509 public file. For decoding
the signed kpatch kernel modules ? But the kernel do not contain the paired
private key files. Any other thoughts about it ?



-- 
Best Regards,
Dong Zhu

**Comment by jpoimboe** [comment]
> ppc64le

Ah, that explains it.  kpatch only supports x86_64 right now.

> As far as I know, kernel will generate its own x509 public and private certificate files by using x509.genkey configuration file during kernel building, and kernel will load the corresponding public x509 file for signing the kernel modules, not the kpatch.x509 file. So I got confused here what's the exact purpose of the kpatch.x509 public file. For decoding the signed kpatch kernel modules ? But the kernel do not contain the paired private key files. Any other thoughts about it ?

Sorry, I just don't know.  You should probably ask the CentOS folks.
