### ISSUE TITLE
Resolving duplicate local functions

### ISSUE THREAD

**Issue by rosslagerwall** [dynup/kpatch#604]
The following patch fails to compile:

```
/usr/libexec/kpatch/create-diff-object: ERROR: dir.o: kpatch_create_patches_sections: 2528: lookup_local_symbol call_filldir (dir.c)
```

``` diff
diff --git a/fs/ext4/dir.c b/fs/ext4/dir.c
index f8d56e4..949aa45 100644
--- a/fs/ext4/dir.c
+++ b/fs/ext4/dir.c
@@ -115,6 +115,9 @@ static int ext4_readdir(struct file *filp,
    struct super_block *sb = inode->i_sb;
    int ret = 0;
    int dir_has_error = 0;
+   static unsigned int count;
+
+   count += 1;

    if (is_dx_dir(inode)) {
        err = ext4_dx_readdir(filp, dirent, filldir);
```

The problem is that both fs/ext3/dir.c and fs/ext4/dir.c define call_filldir. I haven't yet thought of a better way of handling this...

**Comment by jpoimboe** [comment]
> The problem is that both fs/ext3/dir.c and fs/ext4/dir.c define call_filldir.

Are you sure?  I haven't investigated this yet, but at least in theory it already supports duplicate static function names.

Is ext4 compiled as a module?

**Comment by rosslagerwall** [comment]
> Are you sure? I haven't investigated this yet, but at least in theory it already supports duplicate static function names.

No, I'm not sure, but I assumed I was hitting https://github.com/dynup/kpatch/blob/master/kpatch-build/lookup.c#L176 - "dup file+symbol, unresolvable ambiguity"

The kernel has two symbols each called call_filldir, both part of "dir.c". How would you expect it to be able resolve the ambiguity?

> Is ext4 compiled as a module?

This is a 3.10 kernel, with both ext3 and ext4 compiled into the kernel.

**Comment by jpoimboe** [comment]
Ah right, that makes sense.

**Comment by zhouchengming1** [comment]
Hi, I think we can support this dup file+symbol situation. I have thought of two ways to handle this.

1. use base object elf to find the file in lookup table.
( I have implemented this, and test is ok for the above patch )

2. use call relationship to find a unique symbol.
( like A call B, and B is a dup file+symbol function, A is a unique function, so we can first find A
in the lookup table, and then we can find the right B )

Obviously, method1 is easier to implement, but it doesn't support the situation that two files have
all same local symbols. But method2 will have to record the call relationships in lookup table, it maybe
harder to implement. And I prefer the method1. So how do you think?

**Comment by jpoimboe** [comment]
@zhouchengming1 Method 1 sounds good to me.

**Comment by jpoimboe** [comment]
@zhouchengming1 Did you say you had a patch for this?  Would you like to share it? :-)

**Comment by zhouchengming1** [comment]
Sorry, I almost forgot it. I will send the patch today when I have time. Thanks for your reminding.

**Comment by janeczku** [comment]
@zhouchengming1 looks like you getting there?

**Comment by zhouchengming1** [comment]
@janeczku  , sorry, I do not quite understand what you mean :)

**Comment by janeczku** [comment]
@zhouchengming1 i did not realize that you had already opened the PR here https://github.com/dynup/kpatch/pull/651. All good 😃
