### ISSUE TITLE
dynrelas not being rewritten after disabling and reenabling a patch module

### ISSUE THREAD

**Issue by flaming-toast** [dynup/kpatch#606]
Say we have a patch module that patches a target module X. The patch module will break/panic after the following sequence of events:

1) Load module X
2) Load patch module (dynrelas are first written)
3) Disable patch module via sysfs 
4) rmmod module X
5) modprobe module X
6) Renable patch module via sysfs (dynrelas get skipped this time around because we've already modified the instructions in step 2)

Upon re-enabling the patch module, since we've written dynrelas already at step 2 we're going to end up skipping re-applying dynrelas in step 6 and we'll see the warning ("Skipping dynrela for ___ ... the instruction has been changed already"). If module X was never removed in step 4 we would still be OK since its sections/data would retain the same addresses in memory, but if we rmmod and insmod module X the addresses are different and dynrelas must be forcibly re-written.

I remember we changed the patch module's behavior to skip writing dynrelas if an instruction appears to have already been modified to accommodate paravirt instruction patching, it seems this might be an unresolvable limitation for the kpatch core module...

**Comment by zhouchengming1** [comment]
Q: Is this also a problem to the livepatch core ( not the kpatch core module) ?
Because we can't modify back the code when the module goes away, so later when the module comes back, livepatch won't write new dynrelas ?
