### ISSUE TITLE
PPC64LE support

### ISSUE THREAD

**Issue by kamalesh-babulal** [dynup/kpatch#613]
I am currently looking into getting livepatch hook to work on PPC64LE. As suggested on "Getting Involved " section, using this issue to discuss and brainstorm on idea's.

**Comment by kamalesh-babulal** [comment]
Design is to introduce PPC64 specific bits to enhance kpatch, to build livepatch supported modules on PPC64 and guard kpatch specific information with #ifdef's. 

To start with make kmod module to print, about the state of support on powerpc, while kmod
module is loaded.

diff --git a/kmod/core/core.c b/kmod/core/core.c
index 77c7290..5922d55 100644
--- a/kmod/core/core.c
+++ b/kmod/core/core.c
@@ -32,9 +32,11 @@
  * return instruction pointer so that ftrace will return to the new function.
  */
 
+#include <linux/printk.h>
+#include <linux/module.h>
+#ifndef __powerpc__
 #define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
 
-#include <linux/module.h>
 #include <linux/slab.h>
 #include <linux/stop_machine.h>
 #include <linux/ftrace.h>
@@ -1199,6 +1201,14 @@ static void kpatch_exit(void)
        kobject_put(kpatch_patches_kobj);
        kobject_put(kpatch_root_kobj);
 }
+#else
+static int kpatch_init(void)
+{
+       printk(KERN_INFO "kpatch on PPC only supports Livepatching infrastructure");
+       return 0;
+}
+static void kpatch_exit(void) { }
+#endif
 
 module_init(kpatch_init);
 module_exit(kpatch_exit);
 
2. Modify kpatch-build/kpatch-build to address or capture special section required for PPC64LE v2 ELF.
3. Introduce code to read the _mcount location for PPC64LE, which are little tricky.
4. Modify kpatch/kmod/patch/livepatch-patch-hook.c to guard kpatch specific details with #ifdefery.

Can let me your thoughts on it.

**Comment by jpoimboe** [comment]
I think the hardest part of this, by far, would be porting kpatch-build to work with ppc64le.  Before spending much time on that, it would probably be best to wait a few weeks, because we're going to be discussing the future of the livepatch patch creation tooling at Linux Plumber's Conference on Nov 2.

**Comment by kamalesh-babulal** [comment]
>I think the hardest part of this, by far, would be porting kpatch-build to work with ppc64le. Before >spending much time on that, it would probably be best to wait a few weeks, because we're going to be
>discussing the future of the livepatch patch creation tooling at Linux Plumber's Conference on Nov 2.

Thank you. Agree, kpatch-build has been the toughest part. While trying to get the end to end simple patch working on ppc64le. Is there any virtual channel, through which. I can be part of livepatching micro-conference at plumbers or can I please get access to summary of discussions, incase it's put together at some place.

**Comment by jpoimboe** [comment]
> Is there any virtual channel, through which. I can be part of livepatching micro-conference at plumbers or can I please get access to summary of discussions, incase it's put together at some place.

I don't think there's any way to participate or watch remotely, though there might be meeting minutes posted somewhere afterwards.  I'd recommend you watch the live-patching and kpatch mailing lists, and maybe LWN.  And we can keep this issue open as well.

**Comment by kamalesh-babulal** [comment]
>I don't think there's any way to participate or watch remotely, though there might be meeting minutes >posted somewhere afterwards. I'd recommend you watch the live-patching and kpatch mailing lists, and >maybe LWN. And we can keep this issue open as well.

Sure, Thanks

**Comment by jpoimboe** [comment]
@kamalesh-babulal Looks like we're sticking with kpatch-build, at least for now.  The other approach I proposed has some [issues](http://www.spinics.net/lists/live-patching/msg02958.html) with respect to gcc optimizations.

**Comment by kamalesh-babulal** [comment]
@jpoimboe Thank you. Thanks for the notes from livepatching mini-conf. Does the initial approach of supporting livepatch hook for PPC sounds good, to begin with ?

**Comment by kamalesh-babulal** [comment]
Have other presentation from miniconf, been uploaded other than gcc optimization one. Can you please point me to them.

**Comment by jpoimboe** [comment]
If you really want to disable the kpatch core module for powerpc, I think it would be better to do it from the kpatch-build script instead of hacking up core.c.  Like:
```
diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
index a900a6f..48d33fa 100755
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -486,6 +486,9 @@ if grep "CONFIG_LIVEPATCH=y" "$OBJDIR/.config" > /dev/null; then
                KPATCH_LDFLAGS="--unique=.parainstructions --unique=.altinstructions"
        fi
 else
+       if grep -q "CONFIG_PPC64=y" "$OBJDIR/.config"; then
+               die "The kpatch core module doesn't support powerpc.  Please enable CONFIG_LIVEPATCH."
+       fi
        # No support for livepatch in the kernel. Kpatch core module is needed.
        find_core_symvers || die "unable to find Module.symvers for kpatch core module"
        KBUILD_EXTRA_SYMBOLS="$SYMVERSFILE"
```

**Comment by jpoimboe** [comment]
Most of the slides from the LPC live patching microconf are linked on this page:

https://www.linuxplumbersconf.org/2016/ocw/events/LPC2016/tracks/525

**Comment by kamalesh-babulal** [comment]
>If you really want to disable the kpatch core module for powerpc, I think it would be better to do it from the >kpatch-build script instead of hacking up core.c

Thank you for the suggestion. This approach looks cleaner than hacking core.c. For the clean compilation from top level directory, couple of changes to Makefile should resolve the build issue. Next step, is to identifying the special sections, while constructing the module. Makefile changes for the build, can be introduced later.

**Comment by kamalesh-babulal** [comment]
> Most of the slides from the LPC live patching microconf are linked on this page:

Thanks for the pointer to the slides and Jon lwn.net coverage link over the mailing list.

**Comment by kamalesh-babulal** [comment]
#650 [RFC] ppc64le livepatch hook support

It's the first attempt to get end-to-end patching for ppc64le livepatch hook support.
