### ISSUE TITLE
KASLR support

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#617]
kpatch is broken on the latest Fedora 24 kernels which have CONFIG_RANDOMIZE_BASE enabled.

**Comment by joe-lawrence** [comment]
Hi Josh, I took a crack at backporting the upstream livepatch kallsyms callback and friends here: [617_KASLR_support](https://github.com/joe-lawrence/kpatch/compare/joe-lawrence:master...617_KASLR_support)  With those changes, if I can load kpatch modules once again on F24 + ```CONFIG_RANDOMIZE_BASE```.  Stock CentOS7 still loads as well.  Perhaps this is overkill and ```kaslr_offset()``` would have sufficed, but at least this approach will align the kallsyms code a lot closer to its livepatch counterpart.  Let me know if there are any additional tests I can run or code to clean up. -- Joe

**Comment by jpoimboe** [comment]
At first glance, looks good!  Open a pull request and we'll give it a proper review.
