### ISSUE TITLE
Detect out-of-range relocations

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#618]
It would be good to add a check at the end of create-diff-object to find any out-of-range relocations so we can find issues like #615 earlier.

**Comment by stettberger** [comment]
My gcc (8.3.0-6) produces such bad relocations in the first place. I got to a situation, where this relocation check failed on the produced patch file. However, when I called the check on the input ELFs there where already bad relocations in place. Has anyone encountered this Problem before? (GCC Producing relocations that point beyond a section boundary).

**Comment by jpoimboe** [comment]
@stettberger I'm confused, from reading the code in kpatch_check_relocations() it seems that it would already support such jump table relocations.  Do you have a more specific example?

**Comment by stettberger** [comment]
With the Follwing sections
```
  [70] .text.ap_send_error_response PROGBITS        0000000000000000 002e20 00094b 00  AX  0   0 16
  [72] .rodata.ap_send_error_response PROGBITS        0000000000000000 00376c 000350 00   A  0   0  4
```
the relocations

```
Relocation section '.rela.rodata.ap_send_error_response' at offset 0x182a0 contains 212 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
...
00000000000002d8  0000003800000002 R_X86_64_PC32          0000000000000000 .text.ap_send_error_response + b13
00000000000002dc  0000003800000002 R_X86_64_PC32          0000000000000000 .text.ap_send_error_response + b17
```

fails with the current version of `kpatch_check_relocations()` fails as 0xb13 > 0x94b.

**Comment by jpoimboe** [comment]
So why do the rodata relocations (presumably from a GCC switch statement jump table) reference code which doesn't exist?  There seems to be a mismatch, is it pulling .rela.rodata.ap_send_error_response from the original unpatched .o file somehow?  I don't see how that can happen.

**Comment by stettberger** [comment]
The compiler produces the following trampoline (L466, L463 are labels within the code section):

```asm
.section .text.ap_send_error_response
        leaq    .L430(%rip), %rdx
        movslq  (%rdx,%r12,4), %rax
        addq    %rdx, %rax
        jmp     *%rax

.section        .rodata.ap_send_error_response,"a",@progbits
.align 4
.align 4
.L430:
        .long   .L466-.L430
        .long   .L463-.L430
        .long   .L463-.L430
        .long   .L465-.L430
```

The jump table is filled with offsets that are relative to the beginning of the jump table. Therefore, the trampiline adds the address of the jump table with the table entry to get the jump target in `%rax`. This only works if the relocations entries have an combined addend that includes the relative offset within the text section as well as the relative offset between text and rodata section. Thereby, the addend can point after the text section, which is corrected by PC32 relocations. (At this point my understanding also gets a little bit muddy).

**Comment by jpoimboe** [comment]
I've seen a lot of GCC jump tables but I haven't seen this pattern.  Is this from a C switch statement or a manual C "goto" jump table?  I guess the out-of-range check is only expected to work in normal kernel conditions.  I'm guessing there's something different about your environment, like different compiler flags or an out-of-tree module with jump table code.

Maybe the check could be tweaked for the case where the relocation is a PC32 relocation for a.rodata.* section.  Pull requests welcome :-)

**Comment by stettberger** [comment]
As far as I understand it (the object files I was diffing were provided by a colleague), this jump-table pattern was generated by compiling apache2. The relevant function is [ap_send_error_response()](https://github.com/apache/httpd/blob/2517583a449cc109733e443f8994bf7782687bdc/modules/http/http_protocol.c#L1189) from the HTTP module. There is no switch/case but I did not try to fully understand that function.

While have a patch to mitigate the error message without sacrificing the check, it is so ugly it should never see the day of light in a pull request.

**Comment by jpoimboe** [comment]
Ok.  Patching user space is a whole 'nother ball of wax...
