### ISSUE TITLE
testing: meminfo-cmdline-rebuild-SLOW.patch fails to build on CentOS 7

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#625]
As seen when running #624 :

**OS:** CentOS 7
**kernel version**: 3.10.0-327.36.3.el7.x86_64
**gcc version**: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

```
Using cache at /home/vagrant/.kpatch/src
Testing patch file
checking file fs/proc/cmdline.c
checking file fs/proc/meminfo.c
checking file include/linux/kernel.h
Reading special section data
Building original kernel
Building patched kernel
Extracting new and modified ELF sections
/usr/local/libexec/kpatch/create-diff-object: ERROR: copy_user_64.o: fixup_group_size: 1423: can't find .fixup rela group at offset 0

cmdline.o: changed function: cmdline_proc_show
meminfo.o: changed function: meminfo_proc_show

ERROR: 1 error(s) encountered. Check /home/vagrant/.kpatch/build.log for more details.
```

**Comment by jpoimboe** [comment]
create-diff-object gets confused because the bad_from_user() asm function in copy_user_64.S is in the .fixup section.  It should really be in .text.  I'll submit a patch upstream to fix it.

**Comment by jpoimboe** [comment]
(In the mean time, the bug can be avoiding by not changing header files.)

**Comment by jpoimboe** [comment]
Actually bad_from_user() is going to be removed completely from the upstream kernel.  The change is already in the tip tree.  So this needs a fix either in RHEL or a workaround in kpatch.
