### ISSUE TITLE
kpatch and patch module builds fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#636]
**OS**: Ubuntu 16.04.1
**kernel version**:  4.4.0-53-generic
**gcc version**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

For kpatch:
```
make[3]: Entering directory '/usr/src/linux-headers-4.4.0-53-generic'
  CC [M]  /home/vagrant/kpatch/kmod/core/core.o
/home/vagrant/kpatch/kmod/core/core.c: In function ‘kpatch_write_relocations’:
/home/vagrant/kpatch/kmod/core/core.c:683:54: error: ‘struct module’ has no member named ‘module_core’
        unsigned long core = (unsigned long)kpmod->mod->module_core;
                                                      ^
/home/vagrant/kpatch/kmod/core/core.c:684:44: error: ‘struct module’ has no member named ‘core_size’
        unsigned long core_size = kpmod->mod->core_size;
                                            ^
/home/vagrant/kpatch/kmod/core/core.c:752:43: error: ‘struct module’ has no member named ‘core_ro_size’
                if (loc < core + kpmod->mod->core_ro_size)
                                           ^
scripts/Makefile.build:258: recipe for target '/home/vagrant/kpatch/kmod/core/core.o' failed
```
The build fails because Ubuntu backported upstream [7523e4dc5057e](https://github.com/torvalds/linux/commit/7523e4dc5057e) "module: use a structure to encapsulate layout".  The kpatch code currently wraps the code in question around ```#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 5, 0)``` blocks, however the distribution's kernel numbering defeats this check.

For patch modules:
```
/home/vagrant/.kpatch/tmp/patch/livepatch-patch-hook.c:261:10: error: ‘struct klp_reloc’ has no member named ‘val’
    lreloc->val = reloc->kdynrela->src;
```
The klp_reloc structure was updated in [064c89df6247](https://github.com/torvalds/linux/commit/064c89df6247) "livepatch: add sympos as disambiguator field to klp_reloc" which was also introduced in upstream v4.5.  Kpatch source's ```#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 5, 0)``` guards fail to protect when building against Ubuntu's 4.4.0-53-generic kernel.

**Comment by joe-lawrence** [comment]
From ```apt-get changelog linux-image-4.4.0-53-generic```:
```
[ ... snip ... ]

linux (4.4.0-7.22) xenial; urgency=low
  ...
  * Miscellaneous upstream changes
    ...
    - livepatch: add old_sympos as disambiguator field to klp_func
    - livepatch: add sympos as disambiguator field to klp_reloc
    - livepatch: function,sympos scheme in livepatch sysfs directory
    - module: Use the same logic for setting and unsetting RO/NX
    - gcov: use within_module() helper.
    - module: use a structure to encapsulate layout.
    - module: clean up RO/NX handling.
    - module: keep percpu symbols in module's symtab
    - livepatch: Cleanup module page permission changes

 -- Tim Gardner <tim.gardner@canonical.com>  Tue, 16 Feb 2016 14:24:45 -0700
```

**Comment by jpoimboe** [comment]
We should probably add an Ubuntu-specific kernel version check.  Also we should try to encapsulate all these kernel version checks in separate functions where possible to make the code cleaner.

@arges Do you guys have a fix for this in your 16.04 kpatch-build package?  Patches welcome :-)

**Comment by arges** [comment]
Yes, I have some distro-patches to detect the version then add the proper ifdefs so things compile. I can send them after I test it a bit.

**Comment by jpoimboe** [comment]
@arges Thanks!  BTW if you guys are carrying any other patches, you're more than welcome to push them upstream.  It would be good for upstream kpatch to work with distros as much as possible out of the box.

**Comment by arges** [comment]
Cool, will do.
