### ISSUE TITLE
kpatch-build breaks on Ubuntu with stock kernel

### ISSUE THREAD

**Issue by kamalesh-babulal** [dynup/kpatch#648]
Distro: Ubuntu 16.10
Kernel: 4.8.5
gcc: 5.4.1 

kpatch-build breaks, while creating livepatch hook based module.

make[2]: Entering directory '/root/.kpatch/obj'
      CC [M]  /root/.kpatch/tmp/patch/patch-hook.o
    In file included from /root/.kpatch/tmp/patch/livepatch-patch-hook.c:28:0,
                     from /root/.kpatch/tmp/patch/patch-hook.c:21:
    /root/.kpatch/tmp/patch/livepatch-patch-hook.c: In functionpatch_ini:
    /root/linux-4.8.15/include/generated/utsrelease.h:2:32: error: too many decimal points in number
     #define UTS_UBUNTU_RELEASE_ABI 4.8.15
                                    ^
    /root/.kpatch/tmp/patch/livepatch-patch-hook.c:252:7: note: in expansion of macro UTS_UBUNTU_RELEASE_ABI
           UTS_UBUNTU_RELEASE_ABI >= 7 ) \
           ^

**Comment by kamalesh-babulal** [comment]
#649 kpatch-build: Add UTS_UBUNTU_RELEASE_ABI tag for non-stock kernel pull request, attempts to fix this issue.

**Comment by joe-lawrence** [comment]
@kamalesh-babulal - Since PR #649 was merged, can we consider this closed?
