### ISSUE TITLE
Compilation error: kmod/core/core.c:992:27: error: passing argument 2 of ‘set_bit’ from incompatible pointer type [-Werror=incompatible-pointer-types]

### ISSUE THREAD

**Issue by marcin-github** [dynup/kpatch#666]
Hi!
I'm getting compilation error:

  CC [M]  /var/tmp/kpatch/kmod/core/core.o
/var/tmp/kpatch/kmod/core/core.c: In function ‘kpatch_register’:
/var/tmp/kpatch/kmod/core/core.c:992:27: error: passing argument 2 of ‘set_bit’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  set_bit(TAINT_LIVEPATCH, &kpmod->mod->taints);
                           ^
In file included from ./include/linux/bitops.h:36:0,
                 from ./include/linux/kernel.h:10,
                 from ./include/linux/list.h:8,
                 from ./include/linux/module.h:9,
                 from /var/tmp/kpatch/kmod/core/core.c:37:
./arch/x86/include/asm/bitops.h:72:1: note: expected ‘volatile long unsigned int *’ but argument is of type ‘unsigned int *’
 set_bit(long nr, volatile unsigned long *addr)
 ^
cc1: some warnings being treated as errors

\# gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-5.4.0-r2/work/gcc-5.4.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/python --enable-languages=c,c++,objc,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 5.4.0-r2 p1.2, pie-0.6.5' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libcilkrts --disable-libmpx --enable-vtable-verify --enable-libvtv --enable-lto --with-isl --disable-isl-version-check --disable-libsanitizer
Thread model: posix
gcc version 5.4.0 (Gentoo 5.4.0-r2 p1.2, pie-0.6.5)

**Comment by jpoimboe** [comment]
@marcin-github Thanks for reporting it.  I'm guessing you have Linux 4.9?

Linux 4.9 has the module-specific livepatch taint (2992ef29ae01), but the conversion of mod->taints to long (7fd8329ba) isn't until 4.10.  So we shouldn't be doing the set_bit() with 4.9.

Maybe we can just skip setting the module-specific taint on 4.9, and change the setting of HAS_MODULE_TAINT to >= 4.10.  @joe-lawrence, thoughts?

**Comment by marcin-github** [comment]
You are right, I'm using 4.9.

**Comment by joe-lawrence** [comment]
@jpoimboe -- yup, double checking now and the commit/releases timeline is correct.

So really there are three! possible taints - kernel, module (int), and module (long).  Would it make sense to convert ```HAS_RHEL7_MODULE_TAINT``` into ```HAS_LONG_MODULE_TAINT``` ?

**Comment by jpoimboe** [comment]
@joe-lawrence Yeah, that sounds like a good idea.

**Comment by marcin-github** [comment]
With this patch kpatch build without problem.
I'm reading readme and trying to do my first live kernel patch. kpatch-build throws:
ERROR: can't find special struct size.

It looks that gawk can't find needed information from output of `readelf -wi`. Should I continue looking for help of the problem here, in new issue or at https://www.redhat.com/mailman/listinfo/kpatch ?

**Comment by joe-lawrence** [comment]
@marcin-github - thanks for testing the fix!  As far as the ```ERROR: can't find special struct size``` msg goes, can you provide the ```kpatch-build``` command line and if you've got a stock or custom kernel installed?

**Comment by marcin-github** [comment]
Thanks for fix:) I'm using custom kernel. I've copied source tree to temporary directory, then I run:
`./kpatch-build  -s /var/tmp/portage/linux-bcache-kpatch/ /tmp/meminfo-test.patch`

**Comment by joe-lawrence** [comment]
That kpatch-build invocation looks correct, so open a new issue and add:  gcc version, output from that ```readelf | gawk``` script in kpatch-build that you've noted.  Attaching your kernel .config might be useful as well.  Thanks.

**Comment by ric96** [comment]
hmmm.... anyone getting this:
[ric@localhost kpatch-stuff]$ kpatch-build -t vmlinux meminfo-string.patch
Using cache at /home/ric/.kpatch/src
Testing patch file
checking file fs/proc/meminfo.c
Hunk #1 FAILED at 95.
1 out of 1 hunk FAILED
ERROR: source patch file failed to apply.
[ric@localhost kpatch-stuff]$ 

the patch applies fine using git apply, same patch as that of the example
kernel source: 4.9.6-200.fc25.x86_64

**Comment by jpoimboe** [comment]
@ric96 the meminfo_proc_show() function changed in Linux 4.9, so the old meminfo-string.patch no longer applies.

**Comment by ric96** [comment]
@jpoimboe oh, I am kinda new to this kpatch stuff, can you suggest another patch that's suitable for show and tell.

**Comment by jpoimboe** [comment]
@ric96 I'd recommend to just port the meminfo patch for your newer kernel, like:
```
diff --git a/fs/proc/meminfo.c b/fs/proc/meminfo.c
index 8a42849..d8cf031 100644
--- a/fs/proc/meminfo.c
+++ b/fs/proc/meminfo.c
@@ -132,7 +132,7 @@ static int meminfo_proc_show(struct seq_file *m, void *v)
        seq_printf(m, "VmallocTotal:   %8lu kB\n",
                   (unsigned long)VMALLOC_TOTAL >> 10);
        show_val_kb(m, "VmallocUsed:    ", 0ul);
-       show_val_kb(m, "VmallocChunk:   ", 0ul);
+       show_val_kb(m, "VMALLOCCHUNK:   ", 0ul);
 
 #ifdef CONFIG_MEMORY_FAILURE
        seq_printf(m, "HardwareCorrupted: %5lu kB\n",
```

**Comment by ric96** [comment]
@jpoimboe 
finally got the git stuff sorted, the kernel modules builds fine. But the load gives an error of "improper format" or something similar. But I got it work on centos 7 so that works for me...

**Comment by joe-lawrence** [comment]
@ric96 : you may receive an "invalid module format" error if you're trying to load a kpatch patch module that was built for a kernel that's different than the one you're currently booted.  (You can run ```modinfo kpatch-xyz.ko | grep vermagic``` and compare that to ```uname -r``` to check.)

**Comment by jpoimboe** [comment]
@ric96 Also check dmesg for clues.

**Comment by ric96** [comment]
Actual error message
```
[ric@localhost kpatch-stuff]$ sudo ./kpatch/kpatch/kpatch load kpatch-0001-meminfo-string.ko 
[sudo] password for ric: 
loading core module: /home/ric/kpatch-stuff/kpatch/kpatch/../kmod/core/kpatch.ko
loading patch module: kpatch-0001-meminfo-string.ko
insmod: ERROR: could not insert module kpatch-0001-meminfo-string.ko: Invalid module format
kpatch: failed to load module kpatch-0001-meminfo-string.ko
[ric@localhost kpatch-stuff]$
```

version check checkouts fine
```
[ric@localhost kpatch-stuff]$ modinfo kpatch-0001-meminfo-string.ko | grep vermagic
vermagic:       4.9.6-200.fc25.x86_64+ SMP mod_unload 
[ric@localhost kpatch-stuff]$ uname -r
4.9.6-200.fc25.x86_64
[ric@localhost kpatch-stuff]$ modinfo kpatch-0001-meminfo-string.ko | grep vermagic
vermagic:       4.9.6-200.fc25.x86_64+ SMP mod_unload 
[ric@localhost kpatch-stuff]$ uname -r
4.9.6-200.fc25.x86_64
```

dmesg:
```
[ 3143.795811] kpatch_0001_meminfo_string: version magic '4.9.6-200.fc25.x86_64+ SMP mod_unload ' should be '4.9.6-200.fc25.x86_64 SMP mod_unload '
```
looks like the "+" after x86_64 is causing the issue, btw i am using the source automatically downloaded by kaptch-build

**Comment by jpoimboe** [comment]
@ric96 I wonder if the ~/.kpatch/src cache got corrupted somehow.  Try removing ~/.kpatch and try again.

**Comment by ric96** [comment]
already did, I am thinking about creating a new issue to see if this affects multiple users

**Comment by jpoimboe** [comment]
@ric96 Opening another issue sounds good, this seems unrelated to the original issue reported here.
