### ISSUE TITLE
Message ERROR: can't find special struct size.

### ISSUE THREAD

**Issue by marcin-github** [dynup/kpatch#668]
I'm trying to use `kpatch-build` on custom 4.9 kernel. I invoked it in this way:
`./kpatch-build -s /var/tmp/portage/linux-bcache-kpatch/ /tmp/meminfo-test.patch`
`Skipping cleanup`
`Using source directory at /var/tmp/portage/linux-bcache-kpatch`
`Testing patch file`
`checking file fs/proc/meminfo.c`
`Reading special section data`
`ERROR: can't find special struct size`

Output of `readelf | gawk` is empty:
`# readelf -wi /var/tmp/portage/linux-bcache-kpatch/vmlinux| gawk --non-decimal-data ' BEGIN { a = b = p = e = 0 } a == 0 && /DW_AT_name.* alt_instr\s*$/ {a = 1; next}`
`               b == 0 && /DW_AT_name.* bug_entry\s*$/ {b = 1; next}`
`               p == 0 && /DW_AT_name.* paravirt_patch_site\s*$/ {p = 1; next}`
`               e == 0 && /DW_AT_name.* exception_table_entry\s*$/ {e = 1; next}`
`               a == 1 {printf("export ALT_STRUCT_SIZE=%d\n", $4); a = 2}`
`               b == 1 {printf("export BUG_STRUCT_SIZE=%d\n", $4); b = 2}`
`               p == 1 {printf("export PARA_STRUCT_SIZE=%d\n", $4); p = 2}`
`               e == 1 {printf("export EX_STRUCT_SIZE=%d\n", $4); e = 2}`
`               a == 2 && b == 2 && p == 2 && e == 2 {exit}'`
`#`

\# gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-5.4.0-r2/work/gcc-5.4.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/python --enable-languages=c,c++,objc,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 5.4.0-r2 p1.2, pie-0.6.5' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libcilkrts --disable-libmpx --enable-vtable-verify --enable-libvtv --enable-lto --with-isl --disable-isl-version-check --disable-libsanitizer
Thread model: posix
gcc version 5.4.0 (Gentoo 5.4.0-r2 p1.2, pie-0.6.5)

**Comment by marcin-github** [comment]
I'm trying to upload `.config` but github hangs with "Uploading your files..."

**Comment by marcin-github** [comment]
[config.txt](https://github.com/dynup/kpatch/files/750847/config.txt)

**Comment by joe-lawrence** [comment]
@marcin-github - does ```readelf -wi /var/tmp/portage/linux-bcache-kpatch/vmlinux``` have _any_ output?  (or does ```file vmlinux``` state that the ELF is stripped?)

**Comment by marcin-github** [comment]
Hi!
I didn't strip vmlinux (at least intentionally).
`# readelf -wi /var/tmp/portage/linux-bcache-kpatch/vmlinux |wc -l`
`22889`
`# file /var/tmp/portage/linux-bcache-kpatch/vmlinux
/var/tmp/portage/linux-bcache-kpatch/vmlinux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=ac351beb6cc98c9b0848d7176bd8c07b2d41e79f, not stripped

`# gawk -V`
`GNU Awk 4.1.4, API: 1.1`
`Copyright (C) 1989, 1991-2016 Free Software Foundation.`

**Comment by joe-lawrence** [comment]
Hmm, I get a lot more output from readelf on my fedora/upstream build: 
```
% readelf -wi vmlinux | wc -l
74993958
```
Is your ```vmlinux``` truncated by any chance?  @jpoimboe - any ideas?  Could there be a ```.config``` option that is removing this information?

**Comment by marcin-github** [comment]
Hmm, I've options set:
CONFIG_DEBUG_INFO_SPLIT
CONFIG_DEBUG_INFO_REDUCED

maybe it makes difference? I'll try.

**Comment by marcin-github** [comment]
After unsetting CONFIG_DEBUG_INFO_SPLIT I'm  getting:
`# readelf -wi /var/tmp/portage/linux-bcache-kpatch/vmlinux |wc -l`
`7374169`

**Comment by joe-lawrence** [comment]
@marcin-github - that's better.  How about the ```gawk``` command, can it find all the sizes that it's looking for?

**Comment by marcin-github** [comment]
gawk returns:
export ALT_STRUCT_SIZE=1
export PARA_STRUCT_SIZE=1
export BUG_STRUCT_SIZE=1
export EX_STRUCT_SIZE=1

**Comment by jpoimboe** [comment]
Hm, guess we should add checking to kpatch-build to print an error if CONFIG_DEBUG_INFO_SPLIT is set. 

Either that, or figure out a way to find the special section struct sizes from the split out dwarf data.

**Comment by joe-lawrence** [comment]
Thanks for all the info and testing.  I can reproduce this here with those .config options.  Two things, first I think there is a bug in the awk script:

Normal kernel build:
```
% readelf -wi /mnt/disk/linux/vmlinux | grep -A1 alt_instr
    <daa61>   DW_AT_name        : (indirect string, offset: 0x171b8): alt_instr
    <daa65>   DW_AT_byte_size   : 13
--
    <62d8de>   DW_AT_name        : (indirect string, offset: 0x171b8): alt_instr
    <62d8e2>   DW_AT_byte_size   : 13
--
    <63cb52>   DW_AT_name        : (indirect string, offset: 0x37586): __alt_instructions
    <63cb56>   DW_AT_decl_file   : 1
--
    <63cb5e>   DW_AT_name        : (indirect string, offset: 0x374ad): __alt_instructions_end
    <63cb62>   DW_AT_decl_file   : 1
```

vs. CONFIG_DEBUG_INFO_REDUCED build:
```
% readelf -wi vmlinux | grep -A1 alt_instr
    <22ac1>   DW_AT_name        : (indirect string, offset: 0x8dac): alt_instr
    <22ac5>   DW_AT_declaration : 1
--
    <f0cc0>   DW_AT_name        : (indirect string, offset: 0x8dac): alt_instr
    <f0cc4>   DW_AT_byte_size   : 13
--
    <f3088>   DW_AT_name        : (indirect string, offset: 0x1e3d5): __alt_instructions
    <f308c>   DW_AT_decl_file   : 1
--
    <f3094>   DW_AT_name        : (indirect string, offset: 0x1e34f): __alt_instructions_end
    <f3098>   DW_AT_decl_file   : 1
```

The awk script will only consider the first match for ```/DW_AT_name.* alt_instr\s*$/``` and then use the value in the next line's key/value pair.  It should be verifying that the next line is a ```DW_AT_byte_size```.

The second issue is that ```CONFIG_DEBUG_INFO_SPLIT``` is packaging up debug info into separate ```.dwo``` files.  Supporting that should probably be a separate issue.

**Comment by joe-lawrence** [comment]
@marcin-github - try applying the attached patch and see if ```kpatch-build``` successfully completes. (Shamelessly borrowed from @flaming-toast's [kpatch-rhel6](https://github.com/flaming-toast/kpatch/tree/kpatch-rhel6) WIP branch.)

[test.patch.txt](https://github.com/dynup/kpatch/files/755207/test.patch.txt)

@jpoimboe, @flaming-toast - what are your thoughts about supporting either of these two kernel options?  I think ```CONFIG_DEBUG_INFO_REDUCED``` is only a matter of fixing up the ```SPECIAL_VARS``` processing.  (At least on my Fedora VM, I could finish and load a kpatch patch module with such change.)

**Comment by jpoimboe** [comment]
@joe-lawrence Sounds like CONFIG_DEBUG_INFO_REDUCED support is a simple fix which makes the existing code more robust anyway, so that sounds fine.

For CONFIG_DEBUG_INFO_SPLIT support, I don't have a strong feeling about it either way.  It doesn't seem to be a commonly used option, at least not by the distros.  For now we could just spit out an error for it.  We could always add support for it later if anybody wants to do so.

**Comment by marcin-github** [comment]
I run:
`HOME=/var/tmp/kpatch-home bash -x ./kpatch-build -s /var/tmp/portage/linux-bcache-kpatch/ /var/tmp/portage/linux-bcache-kpatch/meminfo-test.patch`

Output:
`[...]`
Reading special section data
++ readelf -wi /var/tmp/kpatch-home/.kpatch/tmp/vmlinux
++ gawk --non-decimal-data '

           BEGIN { a = b = p = e = 0 }
           # Set state if name matches
           a == 0 && /DW_AT_name.* alt_instr[[:space:]]*$/ {a = 1; next}
           b == 0 && /DW_AT_name.* bug_entry[[:space:]]*$/ {b = 1; next}
           p == 0 && /DW_AT_name.* paravirt_patch_site[[:space:]]*$/ {p = 1; next}
           e == 0 && /DW_AT_name.* exception_table_entry[[:space:]]*$/ {e = 1; next}
           # Reset state unless this abbrev describes the struct size
           a == 1 && !/DW_AT_byte_size/ { a = 0; next }
           b == 1 && !/DW_AT_byte_size/ { b = 0; next }
           p == 1 && !/DW_AT_byte_size/ { p = 0; next }
           e == 1 && !/DW_AT_byte_size/ { e = 0; next }
           # Now that we know the size, stop parsing for it
           a == 1 {printf("export ALT_STRUCT_SIZE=%d\n", $4); a = 2}
           b == 1 {printf("export BUG_STRUCT_SIZE=%d\n", $4); b = 2}
           p == 1 {printf("export PARA_STRUCT_SIZE=%d\n", $4); p = 2}
           e == 1 {printf("export EX_STRUCT_SIZE=%d\n", $4); e = 2}
           # Bail out once we have everything
           a == 2 && b == 2 && p == 2 && e == 2 {exit}'
\+ SPECIAL_VARS='export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12'
\+ [[ -n export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12 ]]
\+ eval 'export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12'
++ export ALT_STRUCT_SIZE=13
++ ALT_STRUCT_SIZE=13
++ export EX_STRUCT_SIZE=12
++ EX_STRUCT_SIZE=12
++ export BUG_STRUCT_SIZE=12
++ BUG_STRUCT_SIZE=12
\+ [[ -z 13 ]]
\+ [[ -z 12 ]]
\+ [[ -z '' ]]
\+ die 'can'\''t find special struct size'
\+ [[ -z can't find special struct size ]]
\+ msg='can'\''t find special struct size'
\+ [[ -e /var/tmp/kpatch-home/.kpatch/build.log ]]
\+ warn 'can'\''t find special struct size.'
\+ echo 'ERROR: can'\''t find special struct size.'
ERROR: can't find special struct size.

**Comment by joe-lawrence** [comment]
I don't see ```CONFIG_PARAVIRT``` in the attached .config file, can you retry with a kernel built with that option enabled?  ( We should be getting close :D )

**Comment by marcin-github** [comment]
With or without CONFIG_PARAVIRT_DEBUG ?

**Comment by joe-lawrence** [comment]
CONFIG_PARAVIRT_DEBUG doesn't need to be set

**Comment by marcin-github** [comment]
I'll back tomorrow.

**Comment by jpoimboe** [comment]
I guess we should make PARA_STRUCT_SIZE optional.

**Comment by marcin-github** [comment]
CONFIG_PARAVIRT isn't enough:

++ readelf -wi /var/tmp/kpatch-home/.kpatch/tmp/vmlinux
+ SPECIAL_VARS='export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12'
+ [[ -n export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12 ]]
+ eval 'export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12'
++ export ALT_STRUCT_SIZE=13
++ ALT_STRUCT_SIZE=13
++ export EX_STRUCT_SIZE=12
++ EX_STRUCT_SIZE=12
++ export BUG_STRUCT_SIZE=12
++ BUG_STRUCT_SIZE=12
+ [[ -z 13 ]]
+ [[ -z 12 ]]
+ [[ -z '' ]]
+ die 'can'\''t find special struct size'
+ [[ -z can't find special struct size ]]
+ msg='can'\''t find special struct size'
+ [[ -e /var/tmp/kpatch-home/.kpatch/build.log ]]
+ warn 'can'\''t find special struct size.'
+ echo 'ERROR: can'\''t find special struct size.'
ERROR: can't find special struct size.

**Comment by joe-lawrence** [comment]
@marcin-github - by any chance are you manually appending ```CONFIG_PARAVIRT=y``` to the .config file?  If so, you'll also need ```CONFIG_HYPERVISOR_GUEST=y``` as well, otherwise if will be removed from .config when the kernel's Makefile invokes ```scripts/kconfig/conf  --silentoldconfig Kconfig```.

It's probably easier to toggle this in ```make menuconfig``` so it pulls in any additional configuration dependencies:
```
     -> Processor type and features
       -> Linux guest support (HYPERVISOR_GUEST [=y])
         -> Prompt: Enable paravirtualization code = y
```

**Comment by marcin-github** [comment]
No - no. I used menuconfig to change the option.

**Comment by jpoimboe** [comment]
@marcin-github I'm not able to recreate with Linux 4.9 with your config (and CONFIG_PARAVIRT added and CONFIG_DEBUG_INFO_SPLIT removed).
```
$ readelf -wi ~/k/vmlinux | gawk --non-decimal-data '       BEGIN { a = b = p = e = 0 }
       # Set state if name matches
       a == 0 && /DW_AT_name.* alt_instr[[:space:]]*$/ {a = 1; next}
       b == 0 && /DW_AT_name.* bug_entry[[:space:]]*$/ {b = 1; next}
       p == 0 && /DW_AT_name.* paravirt_patch_site[[:space:]]*$/ {p = 1; next}
       e == 0 && /DW_AT_name.* exception_table_entry[[:space:]]*$/ {e = 1; next}
       # Reset state unless this abbrev describes the struct size
       a == 1 && !/DW_AT_byte_size/ { a = 0; next }
       b == 1 && !/DW_AT_byte_size/ { b = 0; next }
       p == 1 && !/DW_AT_byte_size/ { p = 0; next }
       e == 1 && !/DW_AT_byte_size/ { e = 0; next }
       # Now that we know the size, stop parsing for it
       a == 1 {printf("export ALT_STRUCT_SIZE=%d\n", $4); a = 2}
       b == 1 {printf("export BUG_STRUCT_SIZE=%d\n", $4); b = 2}
       p == 1 {printf("export PARA_STRUCT_SIZE=%d\n", $4); p = 2}
       e == 1 {printf("export EX_STRUCT_SIZE=%d\n", $4); e = 2}
       # Bail out once we have everything
       a == 2 && b == 2 && p == 2 && e == 2 {exit}'
export ALT_STRUCT_SIZE=13
export EX_STRUCT_SIZE=12
export BUG_STRUCT_SIZE=12
export PARA_STRUCT_SIZE=16

```

When using the '-s' option without specifying the vmlinux file, kpatch-build looks for vmlinux in the kernel source tree.  Make sure the kernel source has been built with the new config before running kpatch-build.

**Comment by marcin-github** [comment]
I'll have access to my test box tomorrow. I can prepare similar enviroment on other host but I'm afraid it could be a mess - somethong works or not on box A, something dosen't works on box B etc.

**Comment by joe-lawrence** [comment]
@jpoimboe - I'm working on a final patch for the [debug_info_reduced](https://github.com/joe-lawrence/kpatch/tree/debug_info_reduced) branch to make ```CONFIG_PARAVIRT``` optional.  I've got ```kpatch-build``` + its awk script handling cases with or without the config setting.  I *think* ```create-diff-object``` can handle no ```PARA_STRUCT_SIZE``` variable as long as the objects its inspecting do not have any .parainstructions special section.  In particular:

- ```kpatch_create_kpatch_arch_section``` - will allocate a larger special_sections[ ], but skips .parainstructions anyway
- ```kpatch_process_special_sections``` - similarly skips .parainstructions as it shouldn't be found, so ```kpatch_regenerate_special_section``` will never be called for .parainstructions.

A combined kpatch-test (minus a few patches that need rebasing for 4.9...fc25) successfully built and loaded with this approach.  Am I forgetting anything by leaving ```create-diff-object``` untouched for non-```CONFIG_PARAVIRT``` cases?

**Comment by jpoimboe** [comment]
@joe-lawrence Sounds right.  I think create-diff-object will report an error when it encounters a `.parainstructions` section and PARA_STRUCT_SIZE isn't set.

**Comment by joe-lawrence** [comment]
Hi @marcin-github - I updated my [debug_info_reduced](https://github.com/joe-lawrence/kpatch/tree/debug_info_reduced) branch to ignore ```CONFIG_PARAVIRT``` should it not be set.  The usual it's-only-been-lightly-tested disclaimers apply, but I would appreciate any test results you may provide.  Thanks!

**Comment by marcin-github** [comment]
Hi, @joe-lawrence - with options:
\# CONFIG_HYPERVISOR_GUEST is not set
\# CONFIG_SYS_HYPERVISOR is not set
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_REDUCED=y
\# CONFIG_DEBUG_INFO_SPLIT is not set
\# CONFIG_DEBUG_INFO_DWARF4 is not set

I got:
[ 3282.885400] livepatch: enabling patch 'kpatch_meminfo_test'

$ grep -i total /proc/meminfo 
MemTotalXXXXXXXX 4553908 kB

So it works! Thank you!

**Comment by joe-lawrence** [comment]
@marcin-github - great!  Thanks for testing, I'll send out a PR and think of some additional tests for this changeset.
