### ISSUE TITLE
Fedora 25 mismatch vermagic

### ISSUE THREAD

**Issue by ric96** [dynup/kpatch#670]
After applying a patch mentioned in #666 
It seems that the default kernel source downloaded using kpatch-build, doesn't match due to an additional "+" character in the version string

as detailed in https://github.com/dynup/kpatch/issues/666#issuecomment-278095329

```
[ 3143.795811] kpatch_0001_meminfo_string: version magic '4.9.6-200.fc25.x86_64+ SMP mod_unload ' should be '4.9.6-200.fc25.x86_64 SMP mod_unload '
```

**Comment by joe-lawrence** [comment]
FWIW, I just built Fedora 25 / 4.9.7-201.fc25.x86_64 and the kpatch modules did not have the '+' included in their version magic.  Any .git directory in the downloaded source dir should be deleted as per d200d40569ee251a16cc43cece10edffe70eacba  @ric96 are you applying the #666 patch on top of this commit? ( @jpoimboe checked in that fix back in Nov 2016 )  Maybe running kpatch-build with ```--skip-cleanup``` will leave behind some breadcrumbs in the ```~/.kpatch/src``` directory.

**Comment by ric96** [comment]
@joe-lawrence 
yup, on point.
The .git folder was causing the issue. But I think there needs to be a workaround rather than just deleting the .git folder.

**Comment by joe-lawrence** [comment]
@ric96 - are you saying that the .git directory is still an issue?  If so, then we need to figure out why removing it wasn't sufficient.

**Comment by ric96** [comment]
As of now kpatch-build does remove the .git folder as expected. 
The issue occurred when I initialized a git repo locally to apply the patches and create a suitable meminfo patch for kpatch.
**Deleting my .git folder solved the issue.**
I'm just saying that it is not a viable solution as tracking changes would be difficult and we would need to maintain separate directories one with .git to track changes and the other without for kpatch.

**Comment by jpoimboe** [comment]
~/.kpatch is a private cache which is managed by kpatch-build.  It's not really meant to be messed with.  Otherwise, if you make a mistake, it could result in a corrupt patch.

**Comment by ric96** [comment]
@jpoimboe agreed
