### ISSUE TITLE
kpatch build error raspberry pi

### ISSUE THREAD

**Issue by ric96** [dynup/kpatch#672]
This might seem a bit farfetched but i am trying to get kpatch working on the raspberry pi 3. It is running the default raspbian os, but the official kernel has been recompile with live patching enabled. and all the required dependencies have been installed.
```
pi@raspberrypi:~/kpatch $ uname -a
Linux raspberrypi 4.4-v7+ #1 SMP Tue Feb 7 22:09:48 UTC 2017 armv7l GNU/Linux
pi@raspberrypi:~/kpatch $ uname -r
4.4-v7+
pi@raspberrypi:~/kpatch $
```

I am getting the following error during compilation of kpatch.
```
pi@raspberrypi:~/kpatch $ make
make -C kpatch-build
make[1]: Entering directory '/home/pi/kpatch/kpatch-build'
gcc -MMD -MP -I../kmod/patch -Iinsn -Wall -g -Werror -c -o kpatch-elf.o kpatch-elf.c
kpatch-elf.c: In function ‘kpatch_create_symbol_list’:
kpatch-elf.c:330:6: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘Elf64_Addr’ [-Werror=format=]
      ERROR("symbol %s at offset %lu within section %s, expected 0",
      ^
cc1: all warnings being treated as errors
Makefile:17: recipe for target 'kpatch-elf.o' failed
make[1]: *** [kpatch-elf.o] Error 1
make[1]: Leaving directory '/home/pi/kpatch/kpatch-build'
Makefile:14: recipe for target 'build-kpatch-build' failed
make: *** [build-kpatch-build] Error 2
pi@raspberrypi:~/kpatch $ 

```
gcc version: 4.9.2

**Comment by jpoimboe** [comment]
It's failing because the Pi is 32-bit arm, and right now kpatch-build and kpatch.ko only support x86_64.  

Upstream livepatch (which could be used instead of kpatch.ko) also doesn't have arm support yet, there were some patches posted for it recently: https://lkml.kernel.org/r/1481043967-15602-1-git-send-email-abelvesa@linux.com

**Comment by jpoimboe** [comment]
Closing, because this would probably be a lot of work and we have no plans to implement it anytime soon.
