### ISSUE TITLE
http://ddebs.ubuntu.com/ zesty-security not found on Ubuntu 17.04

### ISSUE THREAD

**Issue by CasparChou** [dynup/kpatch#710]
As the title said, I performed  the steps which add some code to `/etc/apt/sources.list.d/ddebs.list`
and  this is what I got from `apt update`

![image](https://cloud.githubusercontent.com/assets/10682620/26517798/ad408e1c-42d2-11e7-8352-b51bb233377c.png)

`/etc/apt/sources.list.d/ddebs.list`
```
deb http://ddebs.ubuntu.com/ zesty main restricted universe multiverse
deb http://ddebs.ubuntu.com/ zesty-security main restricted universe multiverse
deb http://ddebs.ubuntu.com/ zesty-updates main restricted universe multiverse
deb http://ddebs.ubuntu.com/ zesty-proposed main restricted universe multiverse
```
I had tried to use `--allow-unauthenticated` option on `apt update`, it didn't work

Is it an ignorable message ?

**Comment by joe-lawrence** [comment]
@CasparChou - can you provide a little more context behind your question and how it relates to kpatch?  (I'm a RHEL/Fedora user over here, so I'm not exactly clear on what you're trying to accomplish with regard to additional apt sources).  Thanks!

**Comment by CasparChou** [comment]
When I update apt, and it return an error which said zesty-security is not found. I'm not sure the resource you provided correct or not ? Perhaps I'm doing wrong settings. ; (

**Comment by jpoimboe** [comment]
@arges Any ideas?  Maybe the README needs to be updated for Zesty?

**Comment by arges** [comment]
The only url that failed was zesty-security. This is because nothing has
been published to this pocket yet. Even with this line failing the ddebs
should be available for download. So this is a message that can be ignored.

**Comment by jpoimboe** [comment]
@joe-lawrence your README fix looks good to me, can you put it in a pull request?
