### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by akohlbre** [dynup/kpatch#720]
Hi - I'm getting an undefined symbol error after building with kpatch-build. The build completes successfully, but fails upon loading. See attached file for patch details.

[foo_bad_patch.txt](https://github.com/dynup/kpatch/files/1152711/foo_bad_patch.txt)

I'm building on Ubuntu 16.04, kernel 4.8.0-58, kpatch version 0.4.0.

The undefined symbol is `copy_mnt_ns`. There's a prototype definition for it in `include/linux/mnt_namespace.h`, and it's defined in `fs/namespace.c`. Note that it's called in `kernel/nsproxy.c` with exactly the same set of #includes that my file has, so I don't think that's the issue.

I'm building with `kpatch-build -t vmlinux foo_bad.patch`, and here's the output:
```Testing patch file
checking file include/linux/foo_control.h
checking file kernel/foo_control.c
checking file kernel/fork.c
checking file kernel/Makefile
Reading special section data
Building original kernel
Building patched kernel
Extracting new and modified ELF sections
fork.o: changed function: copy_process.part.30
fork.o: changed function: _do_fork
Patched objects: vmlinux-4.8.0-58-generic
Building patch module: kpatch-foo_bad.ko
SUCCESS
```

output from `kpatch load kpatch-foo_bad.ko`:
```loading patch module: kpatch-foo_bad.ko
insmod: ERROR: could not insert module kpatch-foo_bad.ko: Unknown symbol in module
kpatch: failed to load module kpatch-foo_bad.ko
```

and from the kernel log:
`kpatch_foo_bad: Unknown symbol copy_mnt_ns (err 0)`

Am I missing something in the patch? Is this just outside the scope of kpatch's abilities? Thanks for any help!

**Comment by jpoimboe** [comment]
I don't remember seeing a kpatch patch which touched the Makefile and added a .c file.  Normally I would have said that's not supported, but apparently it (almost) worked somehow, so I'm not so sure about that.

I tried the patch without the new .c file, by putting foo_fxn() in fork.c, and got the same error.  So it seems like a real bug in kpatch-build somewhere.

**Comment by jpoimboe** [comment]
Actually, when I put foo_fxn() in fork.c, the error is different:
```
kpatch: write to 0xffffffffc0d7650e failed for symbol copy_mnt_ns
```

**Comment by jpoimboe** [comment]
The new error was actually caused by a different bug (CONFIG_DEBUG_SET_MODULE_RONX has been replaced with CONFIG_ARCH_HAS_SET_MEMORY for upstream kernels).  I'll open a separate issue for that.

The original error was due to modifying the Makefile and adding a .c file, which as I originally suspected, is not supported :-)

It would probably be good to either: 

a) add support for that
b) have kpatch-build detect it and report an error; or
c) document it somewhere if isn't already.

**Comment by akohlbre** [comment]
Ok - thanks so much for the quick response! The extra .c file and Makefile modifications have actually been working really well, up until this problem, so congrats on unintentionally semi-supporting that :)

I'll move things back into existing files and get rid of the Makefile changes.

Thanks!
