### ISSUE TITLE
Unable to patch KVM

### ISSUE THREAD

**Issue by CiraciNicolo** [dynup/kpatch#748]
I'm trying to patch the KVM module, I've tried several building option with no result:

- `kpatch-build -t arch/x86/kvm patch.patch`: ERROR: no changed objects found.
- `kpatch-build -t vmlinux patch.patch`: ERROR: no changed objects found.
- `kpatch-build -t modules patch.patch `: create a module but I'm unable to load and get `livepatch_patch: no symbol version for module_layout`

What should I target for patching KVM?

**Comment by jpoimboe** [comment]
The `-t` option is a shortcut which doesn't always work, especially if you haven't done a full build first.  Does it work without `-t`?

**Comment by CiraciNicolo** [comment]
Yes, it works. Sorry for the trouble!
