### ISSUE TITLE
Avoid rebuilding 

### ISSUE THREAD

**Issue by CiraciNicolo** [dynup/kpatch#752]
Hi,

there is a way to avoid rebuilding the same original kernel? I would like to speed up the process.

**Comment by jpoimboe** [comment]
Some ways to speed it up:

- Use ccache
- Avoid changing header files
- After your first original tree-wide build, you can subsequently use the '-t' option.  For example: if the patch only changes .c files in vmlinux, like fs/proc/meminfo.c and fs/proc/cmdline.c, use `-t fs/proc/meminfo.o -t fs/proc/cmdline.o`.  Or if it touches a kernel module, do the kernel module target like `-t fs/ext4/ext4.ko`. Note: you have to first populate the build tree with a full build.  And in some cases it doesn't work.

This is a common question, it would be good to clarify this in the README FAQ

**Comment by jpoimboe** [comment]
> On a similar note @jpoimboe, in my clone-a-VM testing rig I was playing with a new kpatch-build --reuse-cache option. Before creating my reference VM image, I performed half of a kpatch-build, ie only building the original kernel. Then I created a tarball out of ~/.kpatch and when making the reference image, untar it into $HOME. When a new test VM is cloned, I run my modified kpatch-build with --reuse-cache --sourcedir /root/.kpatch/src to effectively skip the entire original kernel build. Does this feature seem like something that would be worth pushing into the tree? It may not be generally useful as the use case is kind of limited.

Would it make sense to generalize that idea and use it more broadly?  It seems like kpatch-build doesn't use its cache as wisely as it could, since it rebuilds the original kernel every time.  So what if, instead of doing the original build every time, it just replaces the contents of ~/.kpatch/src with the contents of a ~/.kpatch/src-read-only cache?  It will need more disk space, but it could be worth it if its demonstrably faster than just relying on ccache.

**Comment by joe-lawrence** [comment]
> Would it make sense to generalize that idea and use it more broadly? It seems like kpatch-build doesn't use its cache as wisely as it could, since it rebuilds the original kernel every time. So what if, instead of doing the original build every time, it just replaces the contents of ~/.kpatch/src with the contents of a ~/.kpatch/src-read-only cache? It will need more disk space, but it could be worth it if its demonstrably faster than just relying on ccache.

That might be a better idea, especially if we can reuse the cache for the long integration test, which performs over a dozen `kpatch-build` invocations.  I *think* default ccache behavior requires that full filepaths match, so we just need to make sure that we're not building in two different directories.

As time permits, I can run some tests to see if any of these schemes are worth pursuing (and what they'll cost disk space wise).

@CiraciNicolo - Can you elaborate on your particular use case?  Are you looking to speed up builds while iterating on developing a single patch (if so, can you share the patch).  What kernel are you building against, etc.  Thanks!

**Comment by CiraciNicolo** [comment]
Right now I'm patching KVM, editing vmx.c and I cannot find a valid target to pass to `-t` (arch/x86/kvm says that nothing has been changed `no changed objects found`). I'm build against latest Debian kernel.

**Comment by CiraciNicolo** [comment]
Using `arch/x86/kvm/vmx.o` gives me `invalid ancestor arch/x86/kvm/vmx.o for arch/x86/kvm/vmx.o`

**Comment by jpoimboe** [comment]
Did you try `arch/x86/kvm/kvm-intel.ko`?

**Comment by CiraciNicolo** [comment]
But, I cannot load the module:

```
loading patch module: livepatch-patch.ko
insmod: ERROR: could not insert module livepatch-patch.ko: Invalid module format
kpatch: failed to load module livepatch-patch.ko
```

**Comment by jpoimboe** [comment]
What does `dmesg |tail` show?

**Comment by CiraciNicolo** [comment]
I get `livepatch_patch: no symbol version for module_layout`

**Comment by jpoimboe** [comment]
Looks like issue #587.  The workaround is to remove the -t option :-)

We need to look and see if there's a better way to fix that.

**Comment by CiraciNicolo** [comment]
So I must rebuild the kernel every time? I'm using cache with 5gb of max size, but without the `-t` even if I just add a single line in vmx.c it will force to rebuild everything.

**Comment by jpoimboe** [comment]
Hm, that doesn't sound right.  The kernel makefiles do dependency checking, so if only vmx.c is getting changed, it should be pretty fast the second time.  Not sure what's going wrong there.

**Comment by CiraciNicolo** [comment]
My latest patch only add a printk in vmx.c and kpatch rebuild all the kernel. I'm I doing something wrong maybe? I'm using Debian 9.2

**Comment by joe-lawrence** [comment]
@CiraciNicolo can you attach the patch and provide the kpatch-build command line that you're running?

**Comment by CiraciNicolo** [comment]
Yes, I started a job on 19:30 CET. As soon it completes, I will post the patch, the command line and the job time.

**Comment by CiraciNicolo** [comment]
[This](https://ghostbin.com/paste/66jja) is the patch and the command, the patch is stupid because right now I'm only trying to figure out some things. By the way, I've forked kpatch to fix a problem with Debian 9.2, since the kernel source has a different package name than other distros. You can find the commit [here](https://github.com/CiraciNicolo/kpatch/commit/448d9bcc00bc4681d0ca3ce60b6ff3a10fcc1919)

It finished right now, at 20:48 CET. I'm unable to provide the build log because kpatch deleted it.

**Comment by CiraciNicolo** [comment]
This is the ccache statistic after one and a half complete run (I forgot to take it after a complete run):
```
$ ccache -s
cache directory                     /home/user/.ccache
primary config                      /home/user/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
cache hit (direct)                  4866
cache hit (preprocessed)            8438
cache miss                         10391
cache hit rate                     56.15 %
called for link                       44
called for preprocessing            5030
compile failed                         1
unsupported code directive             4
no input file                       1102
cleanups performed                    59
files in cache                     41266
cache size                           4.8 GB
max cache size                       5.0 GB
```

**Comment by joe-lawrence** [comment]
As currently coded, kpatch-build (default command line arguments) will always unpack the distro kernel and rebuild it for reference.  In this discussion thread, we've tossed around a few ideas to shortcut this process, but at the moment, building the full kernel is required for all input patches.   Next, the patch(es) are applied to the source code.  The kernel is then built a second time and as @jpoimboe mentions, its Makefiles should only be rebuilding dependencies of files that the patches have changed.

There is a little more to this process though, as kpatch isn't directly using gcc for the second build -- take a look at the kpatch-gcc wrapper script.  You'll see that for the "gcc" `$TOOLCHAINCMD` that it creates a backup copy of a given object file before rebuilding it.  That filename is also saved into a temporary `changed_objs` file.  kpatch-build will later use that file listing for ELF analysis and building the new kernel module.

Try kicking off another kpatch-build, but this time add the `--skip-cleanup` option to keep the old `~/.kpatch` directory.  (Be sure to remove it before the next build though!)  Find the `changed_objects` file (I think it's in `~/.kpatch/tmp`) and post what's in the file.  If it's relatively short, then you know that you're not rebuilding the entire kernel a second time.

On the subject of ccache, it may not be intuitive (at least it wasn't initially to me), but the cache hits for any single kpatch-build shouldn't be expected to be very high.  The reason leads back to the kernel Makefiles.  If the cache is cleared and its stats start at zero, the initial reference kernel build will not get many hits, if any at all.  The subsequent "patched" build won't hit many either, as only a few objects should be rebuilt, and they will be different than the ones in the cache from the reference build.

Where ccache will help is repeat kpatch-builds...  the second time it builds a reference kernel should hit near 99% if the cache is large enough.

**Comment by CiraciNicolo** [comment]
Okay, I got it now. I thought that once the original kernel has been build, that result can be used for the next build if the kernel version has not changed. Building the patched kernel takes very little time, so this is a expected behaviour.
