### ISSUE TITLE
Question: Best practise to update modules

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#770]
I'm missing a best practise how to work with patches / modules and kpatch.

Currently i'm building one module per CVE to patch and create a OS package which includes all modules.

After installation of the os pkg i'm doing:
  9   kpatch unload --all
 10   rmmod kpatch
 11 
 12   depmod -a $kver$
 13 
 14   modprobe kpatch
 15   kpatch load --all

But this looks a bit stupid to me. What's the recommanded way on handling patches / fixes.

**Comment by joe-lawrence** [comment]
I don't know if I can a recommended best practice, but a quick summary of how its currently handed by Red Hat:

1 - A kpatch user package which installs the build artifacts of this repository
2 - Accumulative kpatch-\<KVER\> module packages that ship a growing list of fixes:
- Package dependencies here on the kpatch user package and the specific kernel version package that its patching
- In `%post`, load and install the provided kpatch module
- In `%postun`, uninstall the said kpatch module

YMMV as your use case and package tooling might be different.

**Comment by disaster123** [comment]
Thanks a lot for your comment - but does this mean that the accumulate kpatch pkg also uninstall and reinstall all fixes? or how does it load only new ones.

**Comment by joe-lawrence** [comment]
Since all fixes are baked into a single module in a kpatch-\<KVER\> package, removing/reinstalling the package will remove/reinstall all the fixes.

**Comment by disaster123** [comment]
OK so it's really one big module? Which gets unloaded and loaded if an updated version get's installed?

**Comment by disaster123** [comment]
OK thanks!

**Comment by jpoimboe** [comment]
> OK so it's really one big module? Which gets unloaded and loaded if an updated version get's installed?

When loading an updated module, we usually don't unload the previous module, because it's a "no-op".  You just have to be sure that the new module completely replaces (or at least undoes) the old module's functionality.  There's a "replace" feature in development for upstream livepatch which will make that easier.
