### ISSUE TITLE
Unknown symbol kpatch_register Unknown symbol kpatch_unregister Unknown symbol kpatch_root_kobj

### ISSUE THREAD

**Issue by aliceinwire** [dynup/kpatch#778]
kernel 4.14.7

insmod kpatch.ko
[117098.379027] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc ffffffffa00624f8, val ffffffffa00608d0
insmod kpatch-test.ko
[117105.311368] kpatch_test: Unknown symbol kpatch_register (err 0)
[117105.311380] kpatch_test: Unknown symbol kpatch_unregister (err 0)
[117105.311383] kpatch_test: Unknown symbol kpatch_root_kobj (err 0)

**Comment by joe-lawrence** [comment]
Hi @aliceinwire ... by chance is `CONFIG_LIVEPATCH` not set in your kernel config?  The reported unknown symbols are provided by the kpatch-patch-hook.c, so I wonder if this is a kpatch-style module trying to load against a kernel that we assumed would be providing livepatch features.

**Comment by aliceinwire** [comment]
but if I set CONFIG_LIVEPATCH kpatch will use livepatch-hook
how can I use the kpatch-hook, if kpatch need such symbol but enabling  CONFIG_LIVEPATCH is triggering the livepatch-hook?

**Comment by joe-lawrence** [comment]
If CONFIG_LIVEPATCH is not set, then you'll need the kpatch-hook capabilities provided by the kpatch "core" module (it should be called kpatch.ko).  The kpatch script should check for it automatically via its load option.  The modprobe utility should also bring in the core module as the kpatch-patch module should have a dependency on it.  You might alternatively insmod the core module first.

**Comment by aliceinwire** [comment]
yes that is what i was trying to do unset CONFIG_LIVEPATCH and use kpatch core module.
but i cannot use it for the error posted here

**Comment by joe-lawrence** [comment]
AFAIK `insmod` will not load module dependencies, so what happens if kpatch.ko is loaded first?  Did the build process make a `<kpatch.git dir>/kmod/core/kpatch.ko`?

**Comment by aliceinwire** [comment]
is this 
insmod <kpatch.git dir>/kmod/core/kpatch.ko
[117098.379027] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc ffffffffa00624f8, val ffffffffa00608d0

**Comment by joe-lawrence** [comment]
Can you attach the kernel .config and patch file?  I'll try to take a deeper look when I get a chance.
