### ISSUE TITLE
Kpatch fails to process a patch file that contains new (non-existing) files

### ISSUE THREAD

**Issue by hunter86bg** [dynup/kpatch#781]
When I create patch file for a single file , patch test succeeds, but using a patch file that uses more than 1 file (for example comparison of 2 folders) - patch test fails.
Yet, the directory structure is the same.

**Comment by joe-lawrence** [comment]
Can you attach or paste an example patch file that fails in this manner?  Thanks!

**Comment by hunter86bg** [comment]
Sure.
I have 2 folders:
~/linux.orig with CentOS kernel 3.10.0-693.11.1.el7.x86_64
and 
~/linux.kpatch with kernel 3.10.0-693.11.6.el7.x86_64
The patch is created via 'diff -Nur linux.orig linux.kpatch > ver6.patch' which is run from the home directory.If I try to patch from the home directory or from the '~/linux.orig' - it both fails.
If I create a patch for a standalone file - it works:
'diff -u linux.orig/fs/proc/version.c linux.kpatch/fs/proc/version.c > ver6.patch' 
[kpatch-fail.zip](https://github.com/dynup/kpatch/files/1609257/kpatch-fail.zip)

**Comment by joe-lawrence** [comment]
I took a look at the patch and the build.log provided in the kpatch-fail.zip file.  A few observations:
1. These changes include a bunch of kaiser code, so I'm assuming its trying to create a livepatch to address the recent Meltdown / Spectre vulnerabilities.  An issue #779 was opened a few days ago requesting such patch, but was closed as the fixes are currently outside the scope what livepatch can reasonably patch today.
2.  The build.log does include a large set of files that did successfully patch.  You can see those as "checking file /foo/bar/file.c".  This indicates that kpatch can successfully patch multiple files in the fashion intended by the input patch.
3. The first file that failed to patch `arch/x86/kernel/cpu/capflags.c` is relatively new upstream, so kernel-3.10.0-693.11.1.el7 does not contain it.  So in this case, the patch utility doesn't have an original file in which to patch, hence the error message.
4. BTW, the patch file also contains a large number of changes to files with `.mod.c` suffix.  These files are usually generated by the kernel build process when creating kernel modules.  Like `capflags.c`, they do not exist in kernel sources so the patch utility complains about the missing file.

Hope this helps.

**Comment by hunter86bg** [comment]
It seems that my suspicions are true -> kpatch cannot deal with new files.
As kpatch is locally downloading the source , is there a way to properly interrupt the process, so I can manually create them (empty) ?
It seems that the patch command do not have issues patching even with missing files.
So why kpatch fails, as it uses 'patch' binary to verify the patch file ?

**Comment by joe-lawrence** [comment]
Correction -- `capflags.c` is another build generated file.  Off the top of my head, it could be theoretically possible to emulate the change in the input patch by creating a new `kpatch_x86_cap_flags[]` array with the updated values, then updating all clients of the old array to use the new one.   That said, this input patch is going to be an endless source of things not supported by kpatch (assembly code, etc.) 

As far as kpatch and new files... the patch utility should be okay with this.  In the case of the input patch however, the diff context is always adding/removing something from an existing file.  An entirely new file would have included the entire file as added diff context.  There should be no need for manual intervention.

How was the input patch file created (it should be a comparison between two **unbuilt** kernel trees) and what was the reference kernel version (it needs to be kernel-3.10.0-693.11.1.el7)?

Kpatch-non-support aside, the process is going off the rails because this looks like a comparison of two post-built kernel trees.

**Comment by hunter86bg** [comment]
I got the source from the debuginfo package and then created a diff between the 2 folders.

**Comment by joe-lawrence** [comment]
So you ran a diff -Nur between pre and post fix debuginfo kernel trees?  (Just curious to know the end user mindset :)  With a smaller changeset this might have worked if the build-generated and unrelated files were filtered from patch.  In this case though, it is very much a non-trivial change that exceeds what livepatch/kpatch can do.

**Comment by hunter86bg** [comment]
Exactly. I've copied the "/usr/src/debug/kernel-3.10.0-693.11.1.el7/linux-3.10.0-693.11.6.el7.x86_64/" contents to "/home/user/linux.kpatch", then downgraded the  debuginfo package to current kernel version and repeated the step but destination was "/home/user/linux.orig".
Then just a simple "diff -Nur linux.orig/ linux.kpatch > name.patch" did the patch file.
As I have done this with a single file for testing purposes (like same kernel in 2 folders with edited version.c to prove the test)- I thought that the current situation would work.

**Comment by joe-lawrence** [comment]
I think it would be safer to download the running kernel source rpm, install it and run `rpmbuild -bp` to generate a clean  `~/rpmbuild/BUILD/kernel-<ver>.el7/linux-<ver>` tree.  Create before/after copies of `linux-<ver>` directories and create the patch from those differences.  This way there won't be any build artifacts that litter the resulting patch file.

That said, kpatch isn't a general purpose kernel upgrade mechanism, so YMMV when it comes to creating kpatches by comparing kernel trees.  Small changes may generate expected fixes, but we typically need to review for special cases that require additional coding, like shadow variables and load hooks.  The [patch author guide](https://github.com/dynup/kpatch/blob/master/doc/patch-author-guide.md) describes some common gotchas and tools needed to workaround them.
