### ISSUE TITLE
built-in.o -> built-in.a rename in 4.17

### ISSUE THREAD

**Issue by sm00th** [dynup/kpatch#800]
linux-next.git contains [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=for-next&id=eb37d1bdf619118a41dc8fa36a12fd8fd650f802) from kbuild repo. Looks like we will have to filter on both in kpatch-build/kpatch-gcc.

**Comment by jpoimboe** [comment]
Agreed, we can go ahead put the change in now if you want to open a pull request.
