### ISSUE TITLE
create-diff-object fails to find new static functions in some cases

### ISSUE THREAD

**Issue by euspectre** [dynup/kpatch#834]
If a source patch adds a global function `foo()` that takes a callback as an argument, and a static function `bar()` that is used as such callback, create-diff-object may fail to find `bar()` in some cases. Namely, - if `foo()` is defined in one source file, but called in another source file where `bar()` is defined.

Example:
[new-static-callback.patch](https://github.com/dynup/kpatch/files/1927198/new-static-callback.patch.txt)

create-diff-object complains as follows:

> base.o: new function: foo
meminfo.o: changed function: meminfo_proc_open
meminfo.o: new function: bar
/usr/libexec/kpatch/create-diff-object: ERROR: meminfo.o: kpatch_create_intermediate_sections: 2485: lookup_local_symbol bar needed for .text.meminfo_proc_open
ERROR: 1 error(s) encountered.

A workaround is simple: just make the callback `bar()` non-static. The binary patch is built successfully and works OK in that case, so this issue is not that critical.

I guess, I probably missed some special case when preparing the patch for https://github.com/dynup/kpatch/pull/755, but I haven't dug into this yet.

x86_64, OS: Virtuozzo 7, kpatch 0.5.

**Comment by jpoimboe** [comment]
I'm in the middle of refactoring the dynrela code anyway, so I can take a look at this one.

**Comment by jpoimboe** [comment]
It's an easy fix, may_need_dynrela() just needs to add a check for new symbols in the function pointer check.

**Comment by jpoimboe** [comment]
> A workaround is simple: just make the callback bar() non-static. The binary patch is built successfully and works OK in that case, so this issue is not that critical.

BTW, this indicates another bug related to #755.  Function pointer references to existing global functions aren't getting converted to dynrelas.  I'll open another bug for that one.

**Comment by euspectre** [comment]
Thanks for looking into this!
