### ISSUE TITLE
gcc8: special-static-2: function has no fentry/mcount call, unable to patch

### ISSUE THREAD

**Issue by sm00th** [dynup/kpatch#865]
special-static-2.patch from integration tests fails to build with gcc8 and 4.17-rc6 with the following error:

```
x86.o: function kvm_set_msr_common.cold.140 has no fentry/mcount call, unable to patch 
ERROR: x86.o: 1 function(s) can not be patched                                         
/home/asavkov/dev/kpatch/kpatch-build/create-diff-object: unreconcilable difference
```

This is something @jpoimboe mentioned in #856, quoting here for convenience:

> I ran into these GCC 8 cold subfunctions with objtool. I suspect there are more kpatch-build issues to fix related to GCC 8, because the cold subfunctions aren't real patchable functions; they're instead an extension of the non-cold function. So if the cold text changes, I bet kpatch-build will fail because it won't recognize that it's a part of the parent function.

**Comment by jpoimboe** [comment]
Yeah, we'll need to figure out a way to treat the subfunction as an extension of the function.  So if the subfunction changes, the function itself should be patched, with the new subfunction also included.
