### ISSUE TITLE
testing: rhel-7.6 meminfo-cmdline-rebuild-SLOW.patch build fails

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#876]
When testing against 3.10.0-862.el7.x86_64, a couple errors, split by group:
```
create-diff-object: ERROR: aes-x86_64-asm_64.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: ia32entry.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: entry_64.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: wakeup_64.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: hibernate_asm_64.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: head_64.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: xen-asm.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: copy_user_nocache_64.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: getuser.o: main: 3086: FILE symbol not found in base. Stripped?
create-diff-object: ERROR: putuser.o: main: 3086: FILE symbol not found in base. Stripped?
```
For all of these "FILE symbol not found in base" errors, that is because they are assembly files and not .c files.  I'm guessing that somehow `kernel.h` changes percolate down to those files and we need to rethink this patch.

```
create-diff-object: ERROR: dma-noop.o: find_local_syms: 174: find_local_syms for dma-noop.c: found_none
create-diff-object: ERROR: proportions.o: find_local_syms: 174: find_local_syms for proportions.c: found_none
```
Both .c files are built into `lib.a`, so they don't have `fentry` calls for us to hook.  We could ignore them, or figure out why they are being modified by this patch.  (Again `kernel.h` I'm looking at you.)

```
cmdline.o: changed function: cmdline_proc_show
meminfo.o: changed function: meminfo_proc_show
ERROR: cx2341x.o: reference to static local variable cx2341x_video_spatial_filter_mode_menu.28486 in CSWTCH.36 was removed
/root/kpatch/kpatch-build/create-diff-object: unreconcilable difference
```
Need to do more digging on this one.

**Comment by jpoimboe** [comment]
The kernel.h patch is useful for uncovering weird issues, because it runs create-diff-object on pretty much every .o file, so I think we should definitely keep it.

For the asm files, maybe the "FILE symbol not found in base" error could be converted to a warning, and create-diff-object could exit with a value of 3, which means no changes.  Also the warning should probably be clarified that the file is either stripped or asm.

For the find_local_syms errors, while those functions aren't patchable, it would still be interesting to see the reason for the error.  There's apparently some difference in the local symbols in the .o files compared to vmlinux.

The CSWTCH static local variable reference removal seems weird, would be interesting to see what that's about.  Note that CSWTCH is one of the "special" static variables (see is_special_static).

**Comment by joe-lawrence** [comment]
> For the asm files, maybe the "FILE symbol not found in base" error could be converted to a warning, and create-diff-object could exit with a value of 3, which means no changes. Also the warning should probably be clarified that the file is either stripped or asm.

That sounds reasonable. 

> For the find_local_syms errors, while those functions aren't patchable, it would still be interesting to see the reason for the error. There's apparently some difference in the local symbols in the .o files compared to vmlinux.

There must be an easier way to do this, but it appears that the differences are entirely inside the `.debug_info` sections.
```
% diff -y <(objdump --disassemble-all orig/lib/dma-noop.o) \
          <(objdump --disassemble-all patched/lib/dma-noop.o) | \
awk '/file format elf/{next} /Disassembly of section/{SEC=$NF} /[|]/{printf("%s %s\n", SEC, $0)}'
.debug_info:     1767:  ed                      in     (%dx),%eax     |     1767:       ee                      out    %al,(%dx)
.debug_info:     a0fe:  23 c5                   and    %ebp,%eax      |     a0fe:       23 c6                   and    %esi,%eax
.debug_info:     a10a:  23 f3                   and    %ebx,%esi      |     a10a:       23 f4                   and    %esp,%esi
.debug_info:     a122:  21 02                   and    %eax,(%rdx)    |     a122:       22 02                   and    (%rdx),%al
.debug_info:     a133:  2c 02                   sub    $0x2,%al       |     a133:       2d 02 39 a1 00          sub    $0xa13902,%eax
.debug_info:     a135:  39 a1 00 00 06 11       cmp    %esp,0x1106000 |     a138:       00 06                   add    %al,(%rsi)
.debug_info:     a13b:  a1 00 00 65 00 00 00    movabs 0x400000000650 |     a13a:       11 a1 00 00 65 00       adc    %esp,0x650000(
.debug_info:     a142:  00 04                                         |     a140:       00 00                   add    %al,(%rax)
.debug_info:     a144:  0a 4e 00                or     0x0(%rsi),%cl  |     a142:       00 04 0a                add    %al,(%rdx,%rcx
.debug_info:     a147:  00 00                   add    %al,(%rax)     |     a145:       4e 00 00                rex.WRX add %r8b,(%ra
.debug_info:     a149:  0a 4e 00                or     0x0(%rsi),%cl  |     a148:       00 0a                   add    %cl,(%rdx)
.debug_info:     a14c:  00 00                   add    %al,(%rax)     |     a14a:       4e 00 00                rex.WRX add %r8b,(%ra
.debug_info:     a14e:  5a                      pop    %rdx           |     a14d:       00 5a a1                add    %bl,-0x5f(%rdx
.debug_info:     a14f:  a1 00 00 2a 52 01 00    movabs 0xff000001522a |     a150:       00 00                   add    %al,(%rax)
.debug_info:     a156:  00 ff                                         |     a152:       2a 52 01                sub    0x1(%rdx),%dl
.debug_info:     a158:  13 00                   adc    (%rax),%eax    |     a155:       00 00                   add    %al,(%rax)
.debug_info:     a15a:  65 00 00                add    %al,%gs:(%rax) |     a157:       ff 13                   callq  *(%rbx)
.debug_info:     a15d:  00 00                   add    %al,(%rax)     |     a159:       00 65 00                add    %ah,0x0(%rbp)
.debug_info:     a15f:  64 12 49 a1             adc    %fs:-0x5f(%rcx |     a15c:       00 00                   add    %al,(%rax)
.debug_info:     a163:  00 00                   add    %al,(%rax)     |     a15e:       00 64 12 49             add    %ah,0x49(%rdx,
.debug_info:     a165:  65 00 00                add    %al,%gs:(%rax) |     a162:       a1 00 00 65 00 00 00    movabs 0x650000000065
.debug_info:     a168:  00 00                   add    %al,(%rax)     |     a169:       00 65 
.debug_info:     a16a:  65 0a 44 0e 00          or     %gs:0x0(%rsi,% |     a16b:       0a 44 0e 00             or    

% diff -y <(objdump --disassemble-all orig/lib/proportions.o) \
          <(objdump --disassemble-all patched/lib/proportions.o) | \
awk '/file format elf/{next} /Disassembly of section/{SEC=$NF} /[|]/{printf("%s %s\n", SEC, $0)}'
.debug_info:     457c:  00 2c c5 01 5b 00 00    add    %ch,0x5b01(,%r |     457c:       00 2c c6                add    %ch,(%rsi,%rax
.debug_info:     4583:  00 06                   add    %al,(%rsi)     |     457f:       01 5b 00                add    %ebx,0x0(%rbx)
.debug_info:     4593:  00 2c 21                add    %ch,(%rcx,%riz |     4593:       00 2c 22                add    %ch,(%rdx,%riz
.debug_info:     45a4:  00 2c 2c                add    %ch,(%rsp,%rbp |     45a4:       00 2c 2d 02 ac 45 00    add    %ch,0x45ac02(,
.debug_info:     45a7:  02 ac 45 00 00 09 84    add    -0x7bf70000(%r |     45ab:       00 09                   add    %cl,(%rcx)
.debug_info:     45ae:  45 00 00                add    %r8b,(%r8)     |     45ad:       84 45 00                test   %al,0x0(%rbp)
.debug_info:     45b1:  71 00                   jno    45b3 <.debug_i |     45b0:       00 71 00                add    %dh,0x0(%rcx)
```

**Comment by jpoimboe** [comment]
If I'm reading it right, the find_local_syms error doesn't mean there's a difference between orig and patched.  It actually means there's a difference between orig and vmlinux, in the symbol tables.  So if you `readelf -s vmlinux` and search for the "dma-noop.c" FILE symbol, it should have the same local symbols shown in `readelf -s dma-noop.o`.

**Comment by joe-lawrence** [comment]
No such entries in ~/.kpatch/src/vmlinux:
```
% readelf --wide --symbols src/vmlinux | grep -e '\<dma-noop.c\>' -e '\<proportions.c\>'
(nothing)
```
which is really weird since I can find just about every other FILE entry for the source files in lib/Makefile, like flex_proportions.c, plist.c, ratelimit.c, etc.

**Comment by joe-lawrence** [comment]
I wonder if those FILE symbols (and its functions) are dropped from the symbol table if they aren't actually used by vmlinux?

**Comment by jpoimboe** [comment]
I wouldn't have expected the linker to be the smart, but yeah, maybe so...

**Comment by jpoimboe** [comment]
I suppose we could just add "lib/*" to the skip list in kpatch-gcc?

BTW, while you're at it, that find_local_syms message could use some clarification :-)

**Comment by joe-lawrence** [comment]
> I wouldn't have expected the linker to be the smart, but yeah, maybe so...

For an experiment, I added proportions.c back to an upstream tree and into its lib.a... no symtab FILE entry for it.  Then I modified fs/proc/meminfo.c to call prop_local_init_single() and viola, vmlinux symtab now includes "FILE    LOCAL  DEFAULT  ABS proportions.c"

**Comment by joe-lawrence** [comment]
> BTW, while you're at it, that find_local_syms message could use some clarification :-)

Something like `find_local_syms for %s: couldn't find in vmlinux symbol table` ?

And we should leave the `ERROR` for this in place and just skip over lib/* in the kpatch-gcc skip-list?

**Comment by joe-lawrence** [comment]
> For the asm files, maybe the "FILE symbol not found in base" error could be converted to a warning, and create-diff-object could exit with a value of 3, which means no changes. Also the warning should probably be clarified that the file is either stripped or asm.

Also, what if instead of a benign change to kernel.h, like an extra line break, that actual code or a constant is modified in a file included by an assembly file?   If we make this just a warning, would we be creating a patch module that leaves out the change that the assembly file would have carried?

**Comment by joe-lawrence** [comment]
> The CSWTCH static local variable reference removal seems weird, would be interesting to see what that's about. Note that CSWTCH is one of the "special" static variables (see is_special_static).

See these attached files for gdb create-diff-object setup with example object files:
[debug_876.tar.gz](https://github.com/dynup/kpatch/files/2091551/debug_876.tar.gz)

I don't really fully understand the static variable correlation logic, but if I comment out the `is_special_static()` check in `kpatch_correlate_sections()`, then the .rela.rodata.CSWTCH.36 section gets correlated to a twin.  This then allows us to find a `patched_sym` for bundled symbol cx2341x_video_spatial_filter_mode_menu.28486 in the second stage of `kpatch_correlate_static_local_variables` as we now pass the `kpatch_find_static_twin()` test for `sec->twin`.  The end result is that create-diff-object finishes with exit status 3 (no differences).

**Comment by jpoimboe** [comment]
> Something like find_local_syms for %s: couldn't find in vmlinux symbol table ?

Sounds good to me.

> And we should leave the ERROR for this in place and just skip over lib/* in the kpatch-gcc skip-list?

I think so.

> Also, what if instead of a benign change to kernel.h, like an extra line break, that actual code or a constant is modified in a file included by an assembly file? If we make this just a warning, would we be creating a patch module that leaves out the change that the assembly file would have carried?

We don't support patching assembly files.  The user always needs to look at the kpatch-build output anyway to make sure the right functions are getting patched.

**Comment by jpoimboe** [comment]
> I don't really fully understand the static variable correlation logic, but if I comment out the is_special_static() check in kpatch_correlate_sections(), then the .rela.rodata.CSWTCH.36 section gets correlated to a twin. This then allows us to find a patched_sym for bundled symbol cx2341x_video_spatial_filter_mode_menu.28486 in the second stage of kpatch_correlate_static_local_variables as we now pass the kpatch_find_static_twin() test for sec->twin. The end result is that create-diff-object finishes with exit status 3 (no differences).

Looking at the .o file, I suspect commit dea77c42dcf1b1a7f3b4929f32ead18f834bf2e7 was a bit too simplistic with the way it dealt with CSWTCH variables.

A description of the CSWTCH static locals, from the gcc source:
```
/*
     Switch initialization conversion

The following pass changes simple initializations of scalars in a switch
statement into initializations from a static array.  Obviously, the values
must be constant and known at compile time and a default branch must be
provided.  For example, the following code:

        int a,b;

        switch (argc)
	{
         case 1:
         case 2:
                a_1 = 8;
                b_1 = 6;
                break;
         case 3:
                a_2 = 9;
                b_2 = 5;
                break;
         case 12:
                a_3 = 10;
                b_3 = 4;
                break;
         default:
                a_4 = 16;
                b_4 = 1;
		break;
        }
	a_5 = PHI <a_1, a_2, a_3, a_4>
	b_5 = PHI <b_1, b_2, b_3, b_4>


is changed into:

        static const int = CSWTCH01[] = {6, 6, 5, 1, 1, 1, 1, 1, 1, 1, 1, 4};
        static const int = CSWTCH02[] = {8, 8, 9, 16, 16, 16, 16, 16, 16, 16,
                                 16, 16, 10};

        if (((unsigned) argc) - 1 < 11)
          {
	    a_6 = CSWTCH02[argc - 1];
            b_6 = CSWTCH01[argc - 1];
	  }
	else
	  {
	    a_7 = 16;
	    b_7 = 1;
          }
	a_5 = PHI <a_6, a_7>
	b_b = PHI <b_6, b_7>

There are further constraints.  Specifically, the range of values across all
case labels must not be bigger than SWITCH_CONVERSION_BRANCH_RATIO (default
eight) times the number of the actual switch branches.

This transformation was contributed by Martin Jambor, see this e-mail:
   http://gcc.gnu.org/ml/gcc-patches/2008-07/msg00011.html  */
```
So in this .o file, CSWTCH is a static local array which has references to static local arrays.  I don't think it should be treated like a "special" static local because it's related to code flow.  Instead it should be correlated and compared somehow.

Needs more thought...
