### ISSUE TITLE
ERROR: meminfo.o: kpatch_check_relocations: 1941: out-of-range relocation .debug_str+9668 in .rela.debug_info

### ISSUE THREAD

**Issue by aliceinwire** [dynup/kpatch#877]
Building modules, stage 2.
MODPOST 259 modules
Extracting new and modified ELF sections
meminfo.o: changed function: meminfo_proc_show
/usr/libexec/kpatch/create-diff-object: ERROR: meminfo.o: kpatch_check_relocations: 1941: out-of-range relocation .debug_str+9668 in .rela.debug_info

create-diff-object debug output
[create-diff-patch.log](https://github.com/gentoo/elivepatch-server/files/2074874/create-diff-patch.log)

this is the patch tested:
```
diff -Nupr src.orig/fs/proc/meminfo.c src/fs/proc/meminfo.c
--- src.orig/fs/proc/meminfo.c  2017-11-17 15:58:41.113211972 -0500
+++ src/fs/proc/meminfo.c       2017-11-17 15:58:58.554211972 -0500
@@ -42,6 +42,8 @@ static void show_val_kb(struct seq_file
		seq_write(m, " kB\n", 4);
 }

+static int foo = 5;
+
 static int meminfo_proc_show(struct seq_file *m, void *v)
 {
		struct sysinfo i;
@@ -153,6 +155,7 @@ static int meminfo_proc_show(struct seq_
		show_val_kb(m, "CmaFree:        ",
					global_page_state(NR_FREE_CMA_PAGES));
 #endif
+       seq_printf(m, "kpatch: %d\n", foo);

		hugetlb_report_meminfo(m);


kpatch-build
	create-diff-object.c
```

**Comment by aliceinwire** [comment]
I tried to use also different patch but the error is similar.

**Comment by sm00th** [comment]
What are you building against? I couldn't reproduce it with `v4.17-1306-g716a685fdb89`.

**Comment by aliceinwire** [comment]
thanks i wlll try with a more new kernel i was using 4.9.52 if i remeber correctly.i dont have my pc with me now

**Comment by sm00th** [comment]
It is still a bug worth investigating even if it is on an older kernel, I'll try to reproduce it with something older

**Comment by jpoimboe** [comment]
If you can run it with '-d' and then attach the following data, it will probably help us debug it:
- ~/.kpatch/tmp/orig/fs/proc/meminfo.o
- ~/.kpatch/tmp/patched/fs/proc/meminfo.o
- ~/.kpatch/tmp/vmlinux.symtab
- ~/.kpatch/src/Module.symvers (or the Module.symvers from your source dir if you used the --sourcedir option)

**Comment by aliceinwire** [comment]
kernel 4.9.95
[configuration](https://gist.github.com/aliceinwire/3d8c3139610741003aa0b13be4ee01ac)

**Comment by aliceinwire** [comment]
I tried with 4.17.0 and the build is [failing](https://gist.github.com/aliceinwire/4b65a09f568e0be148cfa792e9110363)

**Comment by sm00th** [comment]
That is odd, both original and patched uploaded object-files seem to have botched sizes of .debug_str section and a bunch of relocations are out of range:

```
Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
...
  [33] .debug_str        PROGBITS        0000000000000000 009158 004f00 01 MSC  0   0  1
                                                                 ^^^^^^
...
Relocation section '.rela.debug_info' at offset 0xf390 contains 4621 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000006  000000180000000a R_X86_64_32            0000000000000000 .debug_abbrev + 0
000000000000000c  0000001d0000000a R_X86_64_32            0000000000000000 .debug_str + 9f5b
0000000000000011  0000001d0000000a R_X86_64_32            0000000000000000 .debug_str + 848f
0000000000000015  0000001d0000000a R_X86_64_32            0000000000000000 .debug_str + aea8
...
``` 

I tried reproducing it with 4.9.95 and the exact build command for meminfo.o from build.log with upstream gcc 6.4.0 (judging by the logs thats the version you are using), but no luck. I get similar rela addends, but the section size is much bigger:

```
Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
...
  [33] .debug_str        PROGBITS        0000000000000000 0148ee 00bc19 01  MS  0   0  1
                                                                 ^^^^^^
...
Relocation section '.rela.debug_info' at offset 0x218a0 contains 4622 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000006  000000180000000a R_X86_64_32            0000000000000000 .debug_abbrev + 0
000000000000000c  0000001d0000000a R_X86_64_32            0000000000000000 .debug_str + 9f7e
0000000000000011  0000001d0000000a R_X86_64_32            0000000000000000 .debug_str + 84b2
0000000000000015  0000001d0000000a R_X86_64_32            0000000000000000 .debug_str + 5c51
...
```

**Comment by aliceinwire** [comment]
also same kernel configuration ?

**Comment by sm00th** [comment]
> also same kernel configuration ?

More or less, I took your config and ran olddefconfig on top of it to remove all the gentoo-specific stuff.

**Comment by jpoimboe** [comment]
@aliceinwire It seems like your compiler is buggy...

**Comment by joe-lawrence** [comment]
@pldubouilh , which `gcc --version` ?

**Comment by jpoimboe** [comment]
@pldubouilh can you run with `-d` and attach the original and patched files from ~/.kpatch/tmp?

**Comment by pldubouilh** [comment]
`gcc --version`
```sh
gcc (GCC) 8.1.1 20180531
```

`cat ~/some.patch`
```diff
diff --git a/fs/proc/meminfo.c b/fs/proc/meminfo.c
index 2fb04846..ffe38962 100644
--- a/fs/proc/meminfo.c
+++ b/fs/proc/meminfo.c
@@ -120,7 +120,7 @@ static int meminfo_proc_show(struct seq_file *m, void *v)
        seq_printf(m, "VmallocTotal:   %8lu kB\n",
                   (unsigned long)VMALLOC_TOTAL >> 10);
        show_val_kb(m, "VmallocUsed:    ", 0ul);
-       show_val_kb(m, "VmallocChunk:   ", 0ul);
+       show_val_kb(m, "VMALLOCChunk:   ", 0ul);

 #ifdef CONFIG_MEMORY_FAILURE
        seq_printf(m, "HardwareCorrupted: %5lu kB\n",
```


[rest is here](https://github.com/dynup/kpatch/files/2266768/alles.zip)

**Comment by jpoimboe** [comment]
This needs to be reported as a GCC bug.

Excerpts from `readelf -a .kpatch/tmp/orig/fs/proc/meminfo.o`:
```
  [30] .debug_str        PROGBITS         0000000000000000  0002bac8
       00000000000057a8  0000000000000001 MSC       0     0     1
```
```
Relocation section '.rela.debug_info' at offset 0xa5f8 contains 5088 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000006  00130000000a R_X86_64_32       0000000000000000 .debug_abbrev + 0
00000000000c  00180000000a R_X86_64_32       0000000000000000 .debug_str + 2a65
000000000011  00180000000a R_X86_64_32       0000000000000000 .debug_str + 95e8
```

GCC is producing bad relocations.  The size of the .debug_str section is 0x57a8.  Many of the relocations in .rela.debug_info are referencing beyond the end of the .debug_str section.

**Comment by steils** [comment]
The issue is still here.

`create-diff-object: ERROR: meminfo.o: kpatch_check_relocations: 2264: out-of-range relocation .debug_str+5c03 in .rela.debug_info`

Linux kernel version: `5.2.3-gentoo`
gcc --version `gcc (Gentoo 9.1.0-r1 p1.1) 9.1.0`
```
diff --git a/fs/proc/meminfo.c b/fs/proc/meminfo.c
index 568d90e17c17..16b3befbef50 100644
--- a/fs/proc/meminfo.c
+++ b/fs/proc/meminfo.c
@@ -121,7 +121,7 @@ static int meminfo_proc_show(struct seq_file *m, void *v)
 	seq_printf(m, "VmallocTotal:   %8lu kB\n",
 		   (unsigned long)VMALLOC_TOTAL >> 10);
 	show_val_kb(m, "VmallocUsed:    ", 0ul);
-	show_val_kb(m, "VmallocChunk:   ", 0ul);
+	show_val_kb(m, "VMALLOCCHUNK:   ", 0ul);
 	show_val_kb(m, "Percpu:         ", pcpu_nr_pages());
 
 #ifdef CONFIG_MEMORY_FAILURE
```
Full log of `kpatch-build -d -s ./ -v ./vmlinux test.diff`: [kpatch-build-linux-5.2.3-gentoo-test.log](https://github.com/dynup/kpatch/files/3440042/kpatch-build-linux-5.2.3-gentoo-test.log)

From `readelf -a ~/.kpatch/tmp/orig/fs/proc/meminfo.o`:
```
  [32] .debug_str        PROGBITS         0000000000000000  0002b8b0
       0000000000005af1  0000000000000001 MSC       0     0     8
```
```
Relocation section '.rela.debug_info' at offset 0x9fe8 contains 5050 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000006  00150000000a R_X86_64_32       0000000000000000 .debug_abbrev + 0
00000000000c  001a0000000a R_X86_64_32       0000000000000000 .debug_str + 5c03
000000000011  001a0000000a R_X86_64_32       0000000000000000 .debug_str + a06e
000000000015  001a0000000a R_X86_64_32       0000000000000000 .debug_str + 7e8
```
[readelf-a-meminfo.log](https://github.com/dynup/kpatch/files/3440044/readelf-a-meminfo.log)

I'll try to investigate it (with different gcc versions, vanilla, i.e. without gentoo patches, etc.) and then report it to GCC bugzilla.

**Comment by steils** [comment]
Interesting. It seems the bug is somehow related to debug sections compression.
On the same configuration (linux-5.2.3-gentoo, gcc-9.1.0) I added `-gz=none` to `KCFLAGS`, and got a working patch module.

readelf -a ~/.kpatch/tmp/orig/fs/proc/meminfo.o:
```
  [32] .debug_str        PROGBITS         0000000000000000  000397e8
       000000000000de86  0000000000000001  MS       0     0     1
```
```
Relocation section '.rela.debug_info' at offset 0x15550 contains 5050 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000006  00150000000a R_X86_64_32       0000000000000000 .debug_abbrev + 0
00000000000c  001a0000000a R_X86_64_32       0000000000000000 .debug_str + 5654
000000000011  001a0000000a R_X86_64_32       0000000000000000 .debug_str + a077
000000000015  001a0000000a R_X86_64_32       0000000000000000 .debug_str + 7e8
```
```
$ sudo insmod livepatch-test.ko
$ cat /proc/meminfo | grep VMALLOCCHUNK 
VMALLOCCHUNK:          0 kB
```

**Comment by steils** [comment]
@sm00th's logs show that his debug sections are not compressed (flag `C` is not set). So my hypothesis is that create-diff-object does not support compressed debug sections.
From man gcc:
```
-gz[=type]
...If type is not given, the default type depends on the capabilities of the assembler and linker used.
```
So the sections may be not compressed by default. Is it so for other developers?

**Comment by steils** [comment]
Another odd thing:
```
$ ld --help | grep compress -A 2
  --compress-debug-sections=[none|zlib|zlib-gnu|zlib-gabi]
                              Compress DWARF debug sections using zlib
                               Default: none
```
Yet somehow when I compile the kernel, the debug sections are compressed.
