### ISSUE TITLE
kpatch-build: yumdownloader and $ARCH?

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#887]
Am I the only one who runs into an issue with kpatch-build yumdownloader invocation:
```
yumdownloader --source --destdir "$TEMPDIR" "kernel$ALT-$ARCHVERSION"
```
which I see fails when running manually on a fresh CentOS VM:
```
% yumdownloader --source kernel-$(uname -r)
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No Match for argument kernel-3.10.0-862.el7.x86_64
Nothing to download
```
Since source rpms don't have an associated architecture, doesn't make more sense to strip it out of the version string?
```
# Approximate kpatch-build variables...

% ARCHVERSION=$(uname -r)
% KVER="${ARCHVERSION%%-*}"
% if [[ "$ARCHVERSION" =~ - ]]; then
	KREL="${ARCHVERSION##*-}"
	KREL="${KREL%.*}"
	[[ "$KREL" =~ .el7a. ]] && ALT="-alt"
fi

% yumdownloader --source "kernel$ALT-$KVER-$KREL"
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
kernel-3.10.0-862.el7.src.rpm
```

I've seen this going back several CentOS versions, but haven't complained since I've been caching the kpatch src directory in my VM setup.  Just wondering if I'm seeing things, or if this is indeed a real bug.

**Comment by sm00th** [comment]
Same here, I usually run with -r on these distros, but I didn't notice that it tries to include the arch in it's search, just assumed sources for older versions weren't available.

**Comment by joe-lawrence** [comment]
The strange thing is that `yumdownloader --source --destdir "$TEMPDIR" "kernel$ALT-$ARCHVERSION"` seems to work fine on RHEL inside Red Hat beaker infrastructure.  I wonder if there is something different on the repository side for CentOS installs (I'm doing my own, so they end up pointing out to http://mirrorlist.centos.org and not internal Red Hat servers.)

I just tested my suggested change on RHEL and RHEL-ALT-ppc64 installs (inside RH beaker) and it will accept "kernel$ALT-$KVER-$KREL", so I'll send up a PR later today...
