### ISSUE TITLE
doc: add gcc-plugin-devel package dep to readme

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#888]
Without `gcc-plugin-devel`, you'll see this when building on ppc64le:
```
In file included from gcc-plugins/ppc64le-plugin.c:1:0:
gcc-plugins/gcc-common.h:4:22: fatal error: bversion.h: No such file or directory
 #include "bversion.h"
                      ^
compilation terminated.
```
So we need to update the README.md file to add the dependency for that architecture.

**Comment by kamalesh-babulal** [comment]
I will send a patch to add the dependency to `README.md`

**Comment by zhengkook** [comment]
you can try use the ` apt-get install gcc-5-plugin-dev ` command
