### ISSUE TITLE
What happens when  patching an unloaded module

### ISSUE THREAD

**Issue by ldaochen** [dynup/kpatch#893]
I made a patch for the function in the kvm_intel.ko module and it works fine on the intel cpu machine.
But on the amd machine, this patch is also loaded, but the kvm_intel.ko module is not loaded, because kvm_amd.ko is loaded on the amd machine.

So my problem is that the kvm_intel.ko module is not loaded on the amd machine, why can the patch of the module be loaded?

**Comment by sm00th** [comment]
Hi, this is normal. kpatch does not automatically load the modules containing patched functions. In case when patched functions are not loaded kpatch does not affect anything and just waits for them to be available, it applies changes while a module containing target function is being loaded.
