### ISSUE TITLE
kpatch-build fails with -mrecord-mcount

### ISSUE THREAD

**Issue by sm00th** [dynup/kpatch#895]
4.18 rc's contain 96f60dfa5819 "trace: Use -mcount-record for dynamic ftrace" that adds -mrecord-mcount to KBUILD_CFLAGS when supported by compiler.

This option moves all of the profiling call pointers to a __mcount_loc section. From gcc's man page:

```
       -mrecord-mcount
       -mno-record-mcount
           If profiling is active (-pg), generate a __mcount_loc section that contains pointers
           to each profiling call. This is useful for automatically patching and out calls.
```

create-diff-object fails unable to find fentry/mcount in the function section:

```
ERROR: meminfo.o: 1 function(s) can not be patched
meminfo.o: function meminfo_proc_show has no fentry/mcount call, unable to patch
/home/asavkov/dev/kpatch/kpatch-build/create-diff-object: unreconcilable difference
```

**Comment by jpoimboe** [comment]
I think the difference is that now the `__fentry__` relocation type is `R_X86_64_PC32` instead of `R_X86_64_NONE`.  Should be an easy fix in kpatch_find_func_profiling_calls().

**Comment by sm00th** [comment]
Sorry, should have mentioned that I tried that and it is a bit more complicated. With `R_X86_64_PC32` added as an option in `kpatch_find_func_profiling_calls()` it fails in `kpatch_create_mcount_sections()` with `unexpected instruction at the start of a function`. The first instruction in every function looks like this:

```
   0:   e8 00 00 00 00          callq  5 <meminfo_proc_show+0x5>
```

So it is already what `kpatch_create_mcount_sections()` is trying to change it to and first rela is already of a proper type. Can we just skip create_mcount step in this case or the last part of it?

**Comment by jpoimboe** [comment]
> So it is already what kpatch_create_mcount_sections() is trying to change it to and first rela is already of a proper type. Can we just skip create_mcount step in this case or the last part of it?

Yeah, sounds like it.
