### ISSUE TITLE
 No rule to make target '/var/lib/dkms/kpatch/0.6.1/build/kmod/core/core.o', needed by '/var/lib/dkms/kpatch/0.6.1/build/kmod/core/kpatch.o'.  Stop.

### ISSUE THREAD

**Issue by disaster123** [dynup/kpatch#903]
I was trying to build current git master but i always get:
# KPATCH_BUILD=/lib/modules/4.12.0+104-ph/build make -C core
make: Entering directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
make -C /lib/modules/4.12.0+104-ph/build M=/var/lib/dkms/kpatch/0.6.1/build/kmod/core kpatch.ko
make[1]: Entering directory '/usr/src/linux-headers-4.12.0+104-ph'
make[2]: *** No rule to make target '/var/lib/dkms/kpatch/0.6.1/build/kmod/core/core.o', needed by '/var/lib/dkms/kpatch/0.6.1/build/kmod/core/kpatch.o'.  Stop.
Makefile:1739: recipe for target 'kpatch.ko' failed
make[1]: *** [kpatch.ko] Error 2

This is:
# make -v
GNU Make 4.1

**Comment by disaster123** [comment]
complete dkms log:
```
# cat /var/lib/dkms/kpatch/0.6.1/build/make.log 
DKMS make.log for kpatch-0.6.1 for kernel 4.12.0+104-ph (x86_64)
Wed Sep  5 14:02:36 UTC 2018
make: Entering directory '/var/lib/dkms/kpatch/0.6.1/build/kmod'
make -C core clean
make[1]: Entering directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
rm -f -Rf .*.o.cmd .*.ko.cmd .tmp_versions *.o *.ko *.mod.c \
Module.symvers
make[1]: Leaving directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
make -C core
make[1]: Entering directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
make -C /lib/modules/4.12.0+104-ph/build M=/var/lib/dkms/kpatch/0.6.1/build/kmod/core kpatch.ko
make[2]: Entering directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: *** No rule to make target '/var/lib/dkms/kpatch/0.6.1/build/kmod/core/core.o', needed by '/var/lib/dkms/kpatch/0.6.1/build/kmod/core/kpatch.o'.  Stop.
Makefile:1739: recipe for target 'kpatch.ko' failed
make[2]: *** [kpatch.ko] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.12.0+104-ph'
Makefile:13: recipe for target 'kpatch.ko' failed
make[1]: *** [kpatch.ko] Error 2
make[1]: Leaving directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/var/lib/dkms/kpatch/0.6.1/build/kmod'
```

**Comment by joe-lawrence** [comment]
Hi @disaster123, I'm not familiar with the DKMS implementation for kpatch, but perhaps `core.c` isn't making it into the `/var/lib/dkms/kpatch/0.6.1/build/kmod/core` directory?  It might help to attach a tar.gz of the those directories and files.

**Comment by disaster123** [comment]
Oh it is. The Makefile does not seem to know how to build core.c .

It seems to miss something like:
```
%.o: %.c
        gcc ...
```

**Comment by joe-lawrence** [comment]
Out-of-tree kernel module Makefiles do not need to specify those rules as they invoke the kernel's own Makefiles.  See the line from your dkms output here:
```
make[1]: Entering directory '/var/lib/dkms/kpatch/0.6.1/build/kmod/core'
make -C /lib/modules/4.12.0+104-ph/build M=/var/lib/dkms/kpatch/0.6.1/build/kmod/core kpatch.ko
```
You should find a Makefile in `/lib/modules/4.12.0+104-ph/build` and it should have all the rules needed to build the individual object files and kpatch.ko file.

I doubt this will improve matters, but this is the format that I usually use for out-of-tree module builds.  It's slightly different than what is packaged in the kpatch/kmod Makefile:
```
diff --git a/kmod/core/Makefile b/kmod/core/Makefile
index 93e8490..c92172a 100644
--- a/kmod/core/Makefile
+++ b/kmod/core/Makefile
@@ -7,12 +7,8 @@ ifeq ($(wildcard $(KPATCH_BUILD)),)
 $(error $(KPATCH_BUILD) doesn\'t exist.  Try installing the kernel-devel-$(KERNELRELEASE) RPM or linux-headers-$(KERNELRELEASE) DEB.)
 endif
 
-KPATCH_MAKE = $(MAKE) -C $(KPATCH_BUILD) M=$(THISDIR)
-
-kpatch.ko: core.c
-       $(KPATCH_MAKE) kpatch.ko
-
-all: kpatch.ko
+default:
+       $(MAKE) -C $(KPATCH_BUILD) SUBDIRS=$(THISDIR) modules
 
 clean:
        $(RM) -Rf .*.o.cmd .*.ko.cmd .tmp_versions *.o *.ko *.mod.c \
```

**Comment by disaster123** [comment]
```
You should find a Makefile in /lib/modules/4.12.0+104-ph/build and it should have all the rules needed to build the individual object files and kpatch.ko file.
```
Yes it does contain the kernel Makefile. But still it does not know how to build .c - no idea why.

I retested this with a 4.4 kernel - it works fine there. So it seems something with the linux kernel has changed so that the module does no longer know how to build %.c

**Comment by joe-lawrence** [comment]
[warn.tar.gz](https://github.com/dynup/kpatch/files/2354335/warn.tar.gz)

Hi @disaster123 - I've attached the demo kernel module warn.tar.gz that I have used to test module builds over the years.  If you uncompress and make, can you confirm whether or not it builds for your 4.12.0+104-ph kernel?  It's nearly verbatim from the kernel's [Documentation/kbuild/modules.txt](https://github.com/torvalds/linux/blob/master/Documentation/kbuild/modules.txt#L51) examples.  Note the prerequisites listed in the first paragraph under the "2. How to Build External Modules" section.

**Comment by disaster123** [comment]
Thanks i think i found the issue in an ubuntu bug report which says 4.9 is the last working kernel and he debian make-kpkg is broken for newer ones:
https://bugs.launchpad.net/ubuntu/+source/kernel-package/+bug/1752857

I'll check how to fix this on my side.

**Comment by disaster123** [comment]
Fixed by adding objtool to kernel header
