### ISSUE TITLE
create-diff-object fails to handle mangled function name

### ISSUE THREAD

**Issue by pcd1193182** [dynup/kpatch#918]
Hey, I posted this originally on the mailing list, and was asked to open a PR with the object files attached. The relevant context is that I'm attempting to use kpatch on an out-of-tree ko, specifically zfs.ko. However, create-diff-object fails. I've looked into it, and it looks like the specific issue is that when the initial build of dmu_send.o is done, a specific function (setup_to_thread) doesn't get its name mangled by gcc, but when we rebuild with the patch applied, it becomes setup_to_thread.constprop.20.  The error happened in find_local_syms because locals_match failed, and find_local_syms was called from lookup_open, which is called before kpatch_rename_mangled_functions (which appears to be the function that handles the .constprop renaming).

[Here](https://github.com/dynup/kpatch/files/2488803/o_files.zip) are the .o files that are triggering the issue.  If you also need the .ko, the symtab, and other files that are passed as arguments to create-diff-file, they are [here](https://github.com/dynup/kpatch/files/2488809/extra.zip). If you have any other questions, or need to see the changes I've made to create-diff-object, let me know, though I don't think any of them could cause this failure mode.

**Comment by jpoimboe** [comment]
The problem seems to be that there's a mismatch between zfs.ko and the zfs.ko.symtab file:
```
$ readelf -s zfs.ko |grep setup_to_thread
 10103: 0000000000000000   260 FUNC    LOCAL  DEFAULT 1598 setup_to_thread
$ grep setup_to_thread zfs.ko.symtab
10159: 0000000000000000    257 FUNC    LOCAL  DEFAULT     1641 setup_to_thread.constprop.20
```
Another (minor) issue is that we need to add `__FUNCTION__` to the special static list, like:
```
diff --git a/kpatch-build/create-diff-object.c b/kpatch-build/create-diff-object.c
index a24927f..0362f34 100644
--- a/kpatch-build/create-diff-object.c
+++ b/kpatch-build/create-diff-object.c
@@ -250,6 +250,7 @@ static int is_special_static(struct symbol *sym)
                "__warned.",
                "descriptor.",
                "__func__.",
+               "__FUNCTION__.",
                "_rs.",
                "CSWTCH.",
                NULL,
```
If I recreate the zfs.ko.symtab file manually, then it works:
```
$ eu-readelf -s zfs.ko > zfs.ko.symtab
$ create-diff-object orig_dmu_send.o patched_dmu_send.o zfs.ko zfs.ko.symtab Module.symvers zfs output.o
orig_dmu_send.o: changed function: dmu_adjust_send_estimate_for_indirects
orig_dmu_send.o: new function: setup_to_thread.constprop.20
orig_dmu_send.o: changed function: dmu_send_impl
orig_dmu_send.o: changed function: dmu_send_obj
orig_dmu_send.o: changed function: dmu_send
orig_dmu_send.o: changed function: dmu_send_estimate_fast
```

BTW, another oddity I noticed is that zfs.ko was built with `-ffunction-sections`.  That _might_ work, but I would instead recommend using the original zfs.ko which will be running on the system.

**Comment by pcd1193182** [comment]
That error is probably a result of the changes that I made to try to get the script to work with a non-tree module. I'm still stumbling through the process a little bit, but I think I was misunderstanding a few things. After some reworking (The symtab is now generated from the system's running zfs.ko, and \_\_FUNCTION\_\_ was added to the special static list), I no longer encounter this error. I encounter a new error, however, which I'm having a hard time debugging. 

[These are the new files I'm passing to create-diff-object.](https://github.com/dynup/kpatch/files/2493212/new.zip) The error I'm getting is similar to the previous one: `create-diff-object: ERROR: dmu_send.o: find_local_syms: 178: find_local_syms for dmu_send.c: couldn't find in vmlinux symbol table` This time, however, the symbol it cannot find is `__func__.63708`.  On examination, this symbol appears in the symtab file under the function setup_featureflags.  A similar but differently numbered `__func__` appears in the output of `readelf -s dmu_send.o.orig` (`__func__.63694`, which appears there in `dmu_send.o.patched`'s symtab as well) in its place, and no `__func__.63708` appears in `readelf`'s output in that file.  It seems clear to me that later in create-diff-object, we would realize that these are special symbols and always include them as needed, but there's no logic for that detection in `kpatch_elf_locals`, or anything else before `lookup_open`.

**Comment by jpoimboe** [comment]
I haven't looked at the files yet, but there shouldn't be any discrepancies between the original dmu_send.o and the zfs.ko file.  They should have been built identically, other than the fact that the .o is built with `-ffunction-sections` and `-fdata-sections`.  So that means that if the original .o file has `__func__.63694`, then zfs.ko should have the exact symbol with the same numbered suffix.

That's why the lookup code doesn't take "special" static local symbols into account, because the lookup code is correlating original code in the .o with original code in the .ko, so there shouldn't be any differences in the symbol names.

The differences are only expected to happen later, when correlating original code with patched code.

**Comment by pcd1193182** [comment]
I see, that makes sense.  Thanks for explaining all of this, I'm still figuring out exactly how this tool work. Then probably what's going on is again a case of me doing things slightly wrong because I'm figuring out a new workflow. The repository that I'm using as the source for `orig` is up to date with master, whereas the kernel module on the machine that is running is probably some distance behind. I'll check out the commit that was used to build the running version and see if I can make more progress. Thanks again!

**Comment by pcd1193182** [comment]
Update: With the commit used to build the running zfs.ko version, I manage to build a livepatch-thing.ko. However, when loading this module, it doesn't appear to have the effect that was intended. The patch that I applied should have caused a particular function to return a unique error code when called with specific arguments, but that doesn't appear to be happening.  Some basic systemtap confirms that the argument is set to a non-zero value, but the function returns 0.  I've tried comparing the .ko file to one generated by running the example from the README on the repo, and the structures look pretty similar, but I don't know how to go about doing any more involved debugging than that.
[Here is the output ko and the patch that this is generated from.](https://github.com/dynup/kpatch/files/2493985/output.zip)

**Comment by jpoimboe** [comment]
From looking at the relocations, I think you provided "zfs.ko" as the module name for create-diff-object.  It should instead be "zfs".

For example, dumping the symbol table shows:
```
  133: 0000000000000000      0 NOTYPE  GLOBAL DEFAULT   LOOS+0 .klp.sym.zfs.ko.dmu_objset_from_ds,0
```
And I also saw a reference to zfs.ko in the .kpatch.strings section.

That would explain why the function isn't getting patched, as it doesn't recognize the zfs module.

**Comment by pcd1193182** [comment]
I think I'm getting pretty close with this procedure, and I've cleaned up the code some so hopefully once I get it working I can create a PR or at least a guide for how to build patches against out-of-tree modules.  I'm running into what I hope is the last issue. livepatch-thing.ko builds cleanly, I've verified that the only difference in the gcc commands between the livepatch make and the normal make is that the livepatch build passes in `-I/export/home/delphix/kpatch/kmod/patch -ffunction-sections -fdata-sections`, and the symbol table for my livepatch module looks very similar to one built against an in-tree module modulo the differences in code being patched. That all said, the module fails to apply now.  The error message I get from my ssh session is `insmod: ERROR: could not insert module livepatch-thing.ko: Invalid parameters`, and on the system console I get `livepatch: symbol '__stack_chk_fail' not found in symbol table`.  
[livepatch-thing.ko.zip](https://github.com/dynup/kpatch/files/2503238/livepatch-thing.ko.zip) has the patch which fails to load in it, and it doesn't have `__stack_chk_fail` in the readelf -s output, which makes sense to me since that function shouldn't have been modified by the patch.  I attempted to debug by modifying the pr_err statements in core.c, but I wasn't sure how to get those changes into the kpatch module running in the kernel. systemtap and similar tracing efforts also failed.

**Comment by jpoimboe** [comment]
Sounds like good progress.  At the end of all this, you will be a kpatch/livepatch expert :-)  A PR (for code or docs) would be awesome.

Here's a quick observation, maybe this will help you get unstuck.  Looking at the .ko file, I see
```
  142: 0000000000000000      0 NOTYPE  GLOBAL DEFAULT   LOOS+0 .klp.sym.livepatch_thing.__stack_chk_fail,0
```
Which means that it's expecting to find the `__stack_chk_fail` symbol in the `livepatch_thing` module.  That's not right, it should instead be looking in the kernel proper (vmlinux).  So it should instead be called `.klp.sym.vmlinux.__stack_chk_fail,0`.

**Comment by jpoimboe** [comment]
I suspect your Module.symvers doesn't have `__stack_chk_fail`.

**Comment by pcd1193182** [comment]
You're referring to the Module.symvers that I'm passing into create-diff-object, yeah? It's true that file doesn't have `__stack_chk_fail`. That file is produced by the existing build infrastructure, so I haven't looked at its contents very much; should it have an entry for that function given that it isn't defined in the module?

**Comment by jpoimboe** [comment]
Have you tried just concatening the two files?  Seems like that might work...

**Comment by jpoimboe** [comment]
@pcd1193182 Thanks a lot for the PR! (I haven't had a chance to review it yet.)  I think all your issues were resolved so I'll go ahead and close this.
