### ISSUE TITLE
Won't build with kernel 4.19

### ISSUE THREAD

**Issue by DestroyFX** [dynup/kpatch#929]
make[2]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core'
make -C core
make[2]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core'
make -C /lib/modules/4.19.1/build M=/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core kpatch.ko
make[3]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
gcc -Wl,--as-needed -Wl,--hash-style=gnu -O1 -pipe -march=znver1 -mindirect-branch=thunk -mindirect-branch-register -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -flto=8 -fuse-linker-plugin  create-klp-module.o kpatch-elf.o  -lelf -o create-klp-module
gcc -Wl,--as-needed -Wl,--hash-style=gnu -O1 -pipe -march=znver1 -mindirect-branch=thunk -mindirect-branch-register -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -flto=8 -fuse-linker-plugin  create-kpatch-module.o kpatch-elf.o  -lelf -o create-kpatch-module
gcc -Wl,--as-needed -Wl,--hash-style=gnu -O1 -pipe -march=znver1 -mindirect-branch=thunk -mindirect-branch-register -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -flto=8 -fuse-linker-plugin  create-diff-object.o kpatch-elf.o lookup.o insn/insn.o insn/inat.o  -lelf -o create-diff-object
  CC [M]  /var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core/core.o
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kpatch-build'
/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core/core.c: In function ‘kpatch_find_external_symbol’:
/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core/core.c:654:14: error: ‘const struct kernel_symbol’ has no member named ‘value’
   *addr = sym->value;
              ^~
make[4]: *** [scripts/Makefile.build:306: /var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core/core.o] Error 1
make[3]: *** [Makefile:1695: kpatch.ko] Error 2
make[3]: Leaving directory '/usr/src/linux-4.19.1'
make[2]: *** [Makefile:13: kpatch.ko] Error 2
make[2]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod/core'
make[1]: *** [Makefile:7: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-9999/work/kpatch-9999/kmod'
make: *** [Makefile:22: build-kmod] Error 2

**Comment by joe-lawrence** [comment]
Hi @DestroyFX ... your report nudged me to pull in PR #927
