### ISSUE TITLE
"duplicate" mangled fuctions

### ISSUE THREAD

**Issue by sm00th** [dynup/kpatch#935]
While running integration tests on ppc64le I found out that gcc-constprop.patch is failing with 
```
ERROR: timekeeping.o: symbol changed sections: .text.timekeeping_update.constprop.9
```

It turns out that there are 2 .constprop.* subfunctions in each objectfile:

```
# eu-readelf -s orig/kernel/time/timekeeping.o  | grep timekeeping_update
  137: 0000000000000000    552 FUNC    LOCAL  DEFAULT       48 timekeeping_update.constprop.9
  138: 0000000000000000    568 FUNC    LOCAL  DEFAULT       50 timekeeping_update.constprop.8
# eu-readelf -s patched/kernel/time/timekeeping.o  | grep timekeeping_update
  137: 0000000000000000    552 FUNC    LOCAL  DEFAULT       48 timekeeping_update.constprop.10
  138: 0000000000000000    568 FUNC    LOCAL  DEFAULT       50 timekeeping_update.constprop.9
```

So `kpatch_rename_mangled_functions()` gets very confused and we end up with two .9 functions in patched objfile.

Objfiles can be found at http://dump.trac3r.net/doubleconstprop/

**Comment by jpoimboe** [comment]
I've never seen this one before.  This breaks a very basic assumption made by create-diff-object :-(

**Comment by BigSyke22** [comment]
The root of the problem is that the symbols and the sections are not properly associated.
To solve this problem, you need to:
In kpatch_correlate_sections( ) and kpatch_correlate_symbols(),You can't just associate symbols and sections with strcmp( ),You need to consider the suffix.And as for symbols,you also need to consider the section where the symbol is located.

**Comment by BigSyke22** [comment]
This problem often occurs in mips architecture, many sections generated by local static variables have diffrent suffixes.

**Comment by sm00th** [comment]
.constprop is, so far, the only case I've ever encountered. Looks like this case can be worked around by adding `__attribute__((noclone))` to offending functions.
