### ISSUE TITLE
Can't build simple alt-instructions test case

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#963]
When attempting to build this simple alternatives test case: [alternatives_test.patch.txt](https://github.com/dynup/kpatch/files/3184414/alternatives_test.patch.txt), kpatch-build fails to include all needed relocations, symbols and sections:
```
./kpatch-build/kpatch-build --skip-cleanup -t vmlinux alternatives_test.patch 
Skipping cleanup
Fedora/Red Hat distribution detected
Downloading kernel source for 3.10.0-1048.el7.bz1706733.x86_64
Unpacking kernel source
Testing patch file(s)
Reading special section data
Building original source
Building patched source
Extracting new and modified ELF sections
version.o: changed function: version_proc_show
version.o: new function: kpatch_oldinstr
/root/kpatch/kpatch-build/create-diff-object: ERROR: version.o: kpatch_create_intermediate_sections: 2804: lookup_local_symbol kpatch_newinstr needed for .altinstr_replacement
ERROR: 1 error(s) encountered. Check /root/.kpatch/build.log for more details.
```
However, if I slightly modify the [alternatives_test.patch.txt](https://github.com/dynup/kpatch/files/3184420/alternatives_test.patch.txt) so that the patched function itself calls the functions that the old and new alternative instructions call, then kpatch-build includes all needed parts and loads/executes as expected:
```
./kpatch-build/kpatch-build --skip-cleanup -t vmlinux alternatives_test.patch
Skipping cleanup
Fedora/Red Hat distribution detected
Downloading kernel source for 3.10.0-1048.el7.bz1706733.x86_64
Unpacking kernel source
Testing patch file(s)
Reading special section data
Building original source
Building patched source
Extracting new and modified ELF sections
version.o: changed function: version_proc_show
version.o: new function: kpatch_oldinstr
version.o: new function: kpatch_newinstr      << we needed this!
Patched objects: vmlinux
Building patch module: livepatch-alternatives_test.ko
SUCCESS
```

I have a [WIP.patch.txt](https://github.com/dynup/kpatch/files/3184442/WIP.patch.txt) that ensures that `kpatch_newinstr` is reported as a new function and then it and its section are included via `kpatch_include_symbol()` ... the livepatch now successfully builds, but when invoking the patched code, it crashes the box, so obviously its still missing something.

**Comment by joe-lawrence** [comment]
It could be that the create-diff-object patch is okay, but the alternatives test patch is not.

In both working and not-working cases, `kpatch_newinstr()` is compiled the same (as expected):
```
Disassembly of section .text.kpatch_newinstr:

0000000000000000 <kpatch_newinstr>:
   0:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)
			1: R_X86_64_NONE	__fentry__-0x4
   5:	55                   	push   %rbp
   6:	48 c7 c6 00 00 00 00 	mov    $0x0,%rsi
			9: R_X86_64_32S	.rodata.__func__.23511
   d:	48 c7 c7 00 00 00 00 	mov    $0x0,%rdi                        <<
			10: R_X86_64_32S	.rodata.str1.1+0x8
  14:	31 c0                	xor    %eax,%eax
  16:	48 89 e5             	mov    %rsp,%rbp
  19:	e8 00 00 00 00       	callq  1e <kpatch_newinstr+0x1e>
			1a: R_X86_64_PC32	printk-0x4
  1e:	5d                   	pop    %rbp
  1f:	c3                   	retq
```
Note that its clobbering `rdi` and using it to store an argument to its printk call.

However, notice the difference in how `version_proc_show()` is compiled:
```
not-working case                working case
------------------------------------------------------

[FTRACE NOP]                    [FTRACE NOP]
push   %rbp                     push   %rbp
mov    %rsp,%rbp                mov    %rsp,%rbp
                             |  push   %rbx
                             |  mov    %rdi,%rbx
                             >  callq  <kpatch_newinstr>
                             >  callq  <kpatch_oldinstr>
callq  <kpatch_newinstr>        callq  <kpatch_newinstr>
                             <
                             <
mov    %gs:0x10e80,%rax         mov    %gs:0x10e80,%rax
mov    0x760(%rax),%rax         mov    0x760(%rax),%rax
                             |  mov    %rbx,%rdi
mov    <ADDR1>,%rsi             mov    <ADDR1>,%rsi
mov    0x8(%rax),%rax           mov    0x8(%rax),%rax
lea    0x4(%rax),%rdx           lea    0x4(%rax),%rdx
lea    0x86(%rax),%rcx          lea    0x86(%rax),%rcx
lea    0xc7(%rax),%r8           lea    0xc7(%rax),%r8
xor    %eax,%eax                xor    %eax,%eax
callq  <seq_printf>             callq  <seq_printf>
                             |  pop    %rbx
xor    %eax,%eax                xor    %eax,%eax
pop    %rbp                     pop    %rbp
retq                            retq   
```
The additional `kpatch_*` calls are expected, but in the working case, it's pushing and popping `rdi` onto the stack before the call instructions.  I think we may have been lucky that it did so before the alternatives instructions were specified.

I'll have to think a bit on how to restructure the alternatives test patch to work around this.  Maybe it would be simpler to just move a pointer value into a register and do something based on that.

**Comment by jpoimboe** [comment]
Yeah, the compiler doesn't have visibility to the inline asm code.  Try using alternative_call() instead.

**Comment by joe-lawrence** [comment]
> Yeah, the compiler doesn't have visibility to the inline asm code. Try using alternative_call() instead.

I can't seem to figure out the syntax for `alternative_call()`.  This continues to generate a simple "call <reloc>" with no register saving:
```
alternative_call(kpatch_oldinstr, kpatch_newinstr,
		X86_FEATURE_ALWAYS,
		/* no output */,
		ASM_NO_INPUT_CLOBBER("rdi")); 
```

Then I thought, let's skip the function calls and just set a pointer:
```
char kpatch_default[]="kpatch_default";
char kpatch_alternative[]="kpatch_alternative";

foo()
{
	char *str;
	...
	alternative_io("mov %2, %0", "mov %3, %0",
			X86_FEATURE_ALWAYS,
			"=r"(str),
			"r"(kpatch_default), "r"(kpatch_alternative));
```
but the compiler gets creative:  in .text, it creates assignments to *both* the strings (via relocations) to different registers.  The altinst_replacement then sets one register to the other to pull off the alternate:

```
  0000000000000000 <foo>:
   8:   49 c7 c4 00 00 00 00    mov    $0x0,%r12
                        b: R_X86_64_32S kpatch_default
   f:   48 c7 c5 00 00 00 00    mov    $0x0,%rbp
                        12: R_X86_64_32S        kpatch_alternative
  16:   4c 89 e3                mov    %r12,%rbx

...

0000000000000000 <.altinstr_replacement>:
   0:   48 89 eb                mov    %rbp,%rbx


Relocation section [10] '.rela.altinstructions' for section [ 9]
'.altinstructions' at offset 0x28dc0 contains 2 entries:
  Offset              Type            Value               Addend Name
  000000000000000000  X86_64_PC32     000000000000000000     +22 .text
  0x0000000000000004  X86_64_PC32     000000000000000000      +0 .altinstr_replacement
```

This kinda surprised me, but then again I don't do a lot of inline assembly so maybe it's pretty difficult to dictate what the end code is going to look like.

**Comment by jpoimboe** [comment]
Ah, right.  For some reason I had assumed that alternative_call() would handle the constraints for you.  Calling functions from inline asm is tricky.  You would need to do something like what ____PVOP_VCALL() does.

**Comment by jpoimboe** [comment]
Or, you could call an asm function which saves/restores all registers before calling into the C function which calls printk.

So much for a "simple" alt-instructions test case :-)

**Comment by jpoimboe** [comment]
For the latter idea, I think you could create a thunk like those in arch/x86/entry/thunk_64.S.  You don't need to save _all_ registers, just the non-callee-saved ones.

**Comment by jpoimboe** [comment]
> Or, you could call an asm function which saves/restores all registers before calling into the C function which calls printk.

Not sure that makes sense in a live patching context though.  Alternatives can be used in asm code but we can't patch asm functions.

**Comment by joe-lawrence** [comment]
How about something like [alternatives_test.patch.txt](https://github.com/dynup/kpatch/files/3189105/alternatives_test.patch.txt) which specifies notrace functions that simply set a global variable:

```
Disassembly of section .text.kpatch_oldinstr:

0000000000000000 <kpatch_oldinstr>:
   0:   48 c7 05 00 00 00 00    movq   $0x0,0x0(%rip)        # b <kpatch_oldinstr+0xb>
   7:   00 00 00 00
                        3: R_X86_64_PC32        kpatch_str-0x8
                        7: R_X86_64_32S kpatch_default
   b:   c3                      retq

Disassembly of section .text.kpatch_newinstr:

0000000000000000 <kpatch_newinstr>:
   0:   48 c7 05 00 00 00 00    movq   $0x0,0x0(%rip)        # b <kpatch_newinstr+0xb>
   7:   00 00 00 00
                        3: R_X86_64_PC32        kpatch_str-0x8
                        7: R_X86_64_32S kpatch_alternative
   b:   c3                      retq
```
Would that be reliable enough to depend on though?

**Comment by jpoimboe** [comment]
That would probably work.  I think it would be more obviously robust if you just use alternative() to do the mov's in inline asm.  The cleanest way would be to use local variables as input and output.  And then as a bonus you'd get to learn all about [inline asm constraints](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html) ;-)

But I wouldn't object to the above approach.

**Comment by joe-lawrence** [comment]
> That would probably work. I think it would be more obviously robust if you just use alternative() to do the mov's in inline asm. The cleanest way would be to use local variables as input and output. And then as a bonus you'd get to learn all about [inline asm constraints](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html) ;-)

Isn't that what I tried with `alternate_io()` in https://github.com/dynup/kpatch/issues/963#issuecomment-493145617 ?  Even if I use local variables for the all strings, the compiler similarly uses two assignments in .text and then a third in .altinst_replacement to choose the alternative.

> But I wouldn't object to the above approach.

It feels like a hack, but I'm out of ideas on the above approach.

**Comment by jpoimboe** [comment]
Sorry, I had missed your alternative_io() solution.  In that case the generated code looks correct to me, and it looks how I would expect given the code.  I don't see a problem with loading the string addresses in .text, other than the fact that it's doing one instruction's worth of unnecessary work.  It seems to set the registers up correctly for both the original and alternative cases.  Or am I missing something?

I do think there's a bug in the parameters, %2 should be %1 and %3 should be %2.  Right?

**Comment by joe-lawrence** [comment]
> I don't see a problem with loading the string addresses in .text, other than the fact that it's doing one instruction's worth of unnecessary work. It seems to set the registers up correctly for both the original and alternative cases. Or am I missing something?

For my test point purpose, it did not interpret the inline assembly literally enough.  The net result is the same though.  I would have liked a call instruction with relocation in .text and then a similar call+reloc in .altinstr_replacement.  But the compiler is free to implement as it sees fit and I have no idea how to dictate a desired form.

> I do think there's a bug in the parameters, %2 should be %1 and %3 should be %2. Right?

This took me a while to figure out, but check out the comment about arguments in alternative_input():

```c
/*
 * Alternative inline assembly with input.
 *
 * Peculiarities:
 * No memory clobber here.
 * Argument numbers start with 1.
 * Best is to use constraints that are fixed size (like (%1) ... "r")
 * If you use variable sized constraints like "m" or "g" in the
 * replacement make sure to pad to the worst case length.
 * Leaving an unused argument 0 to keep API compatibility.
 */
#define alternative_input(oldinstr, newinstr, feature, input...)        \
        asm volatile (ALTERNATIVE(oldinstr, newinstr, feature)          \
                : : "i" (0), ## input)
                     ^^^^^^
...

/* Like alternative_input, but with a single output argument */
#define alternative_io(oldinstr, newinstr, feature, output, input...)   \
        asm volatile (ALTERNATIVE(oldinstr, newinstr, feature)          \
                : output : "i" (0), ## input)
```
I don't know what API compatibility that's talking about, but if I use %1, it ends up as $0x0

**Comment by jpoimboe** [comment]
I still don't see the problem:
```


  0000000000000000 <foo>:
   8:   49 c7 c4 00 00 00 00    mov    $0x0,%r12
                        b: R_X86_64_32S kpatch_default
   f:   48 c7 c5 00 00 00 00    mov    $0x0,%rbp
                        12: R_X86_64_32S        kpatch_alternative
  16:   4c 89 e3                mov    %r12,%rbx

...

0000000000000000 <.altinstr_replacement>:
   0:   48 89 eb                mov    %rbp,%rbx


Relocation section [10] '.rela.altinstructions' for section [ 9]
'.altinstructions' at offset 0x28dc0 contains 2 entries:
  Offset              Type            Value               Addend Name
  000000000000000000  X86_64_PC32     000000000000000000     +22 .text
  0x0000000000000004  X86_64_PC32     000000000000000000      +0 .altinstr_replacement
```
The non-alternative path is:
```
mov kpatch_default, %r12
mov kpatch_alternative, %rbp
mov %r12, %rbx
```
And the alternative path is:
```
mov kpatch_default, %r12
mov kpatch_alternative, %rbp
mov %rbp, %rbx
```
So str (rbx) always ends up with the right pointer.

**Comment by joe-lawrence** [comment]
Right.  The generated code _works_, but for a test-point, I wanted to see a relocation here:
```
  0000000000000000 <.altinstr_replacement>:
     0:   e8 00 00 00 00          callq  5 <__initcall_proc_version_init5+0x5>
                          1: R_X86_64_PC32        .text.kpatch_newinstr-0x4
```
to verify that relocation stays in `.altinst_replacement` and that kpatch-build doesn't convert it to a klp-arch variant.  (As I understand it, only the `{.rela,}.altinstruction` sections are renamed to klp-arch sections.  That's enough for the kernel to handle deferring the alternative until after klp_object load.)

What the compiler is doing in this case is to stuff both assignments via relocations in `.text` and stashing that register move into `.altinstr_replacement` instead.  That code works just as well, but I don't get my relocation in `.altinst_replacement` for testing.

**Comment by jpoimboe** [comment]
Ah, so this is for a unit test.  I was thinking it was going to be a runtime integration test.

If you wanted to solve this I think you could hard-code the use of global variables in the asm itself, instead of supplying them as constraints.  That should put the string relocation in .altrinstr_replacement.

**Comment by jpoimboe** [comment]
To do that I think you'd have to specify the used registers in the clobbers list.

**Comment by joe-lawrence** [comment]
Well, it started as a runtime test and then I hit that other bug for #965.  Out of this, we could create both:
- runtime test that just verifies the alternative was applied and visible
- unit test to exercise create-diff-object

However, I don't think we do arch-specific integration tests at the moment, do we?

**Comment by jpoimboe** [comment]
> However, I don't think we do arch-specific integration tests at the moment, do we?

Hm, I guess we don't.  Maybe the integration test isn't really needed though; didn't you have an in-progress selftest which would test the same thing?

**Comment by joe-lawrence** [comment]
> Hm, I guess we don't. Maybe the integration test isn't really needed though; didn't you have an in-progress selftest which would test the same thing?

That was for the klp-convert patchset, so that I could create the klp-arch sections without kpatch-build.  Once those pieces are in place, then we can say that there isn't anything kpatch-specific about it and let the in-kernel livepatch tests handle testing the kernel.

**Comment by jpoimboe** [comment]
But that selftest would also be useful for testing kpatch-build-generated klp-arch sections right?  Does it have any real dependency on klp-convert?

**Comment by joe-lawrence** [comment]
I think you are referring to this one:  https://github.com/joe-lawrence/linux/commit/3d52425331a71b219a849bff1414006324d8e15d  intented to be a klp-convert driven version for testing.

Bug #963 was spotted when porting that to alternatives_test.patch, a kpatch-style patch to do basically the same thing.  If we want something like this in the kpatch integration test suite, we'd need to first do the same arch-tagging that we do for unit tests.  I can look into that next week if you want.

In both klp and kpatch-build created klp-arch sections, we would write a small script that just verifies output depending on the alternatives expected.  I don't know if they'll be exactly the same, but we can model them to be similar enough.

**Comment by jpoimboe** [comment]
Sorry, I don't think my last suggestion made any sense.  My only excuse is that it's Friday.

Instead of making arch-specific integration tests, maybe the patch could include both x86 and powerpc changes.  Ideally the powerpc change would also test alternatives, but at the bare minimum it could just be a generic no-op so that it at least builds on powerpc.

**Comment by joe-lawrence** [comment]
```
% find . -name 'alternative.h'
./arch/x86/include/asm/alternative.h
./arch/parisc/include/asm/alternative.h
./arch/s390/include/asm/alternative.h
./arch/arm64/include/asm/alternative.h
```
Since ppc64le doesn't have alternatives, it could just do a nop kpatch and the user script would handle accordingly I suppose.  Arches that do have support could add their own wrinkle to the patch.

**Comment by joe-lawrence** [comment]
Bump.. I left this open as a self-reminder to write that integration test.  How about something like: https://github.com/dynup/kpatch/compare/master...joe-lawrence:integration-test-x86-smp-alternatives

**Comment by jpoimboe** [comment]
> Since ppc64le doesn't have alternatives, it could just do a nop kpatch and the user script would handle accordingly I suppose. Arches that do have support could add their own wrinkle to the patch.

FWIW, It looks like powerpc does have some version of alternatives: see apply_feature_fixups().  And it looks like create-diff-object supports the related sections (`__ftr_fixup` and friends).

**Comment by jpoimboe** [comment]
Hm, so I'm guessing we need .klp.arch. sections for powerpc...
