### ISSUE TITLE
kmod core module: v5.2-rc1 stack trace updates break build

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#966]
tglx renovated the stack trace code for 5.2 (see patchset in [lkml archive](https://lore.kernel.org/lkml/20190425094453.875139013@linutronix.de/)), changing `struct stack_trace` and its related APIs.

Sooner or later we're going to deprecate the kpatch core module since its functionality can be provided by the kernel livepatch API.  But in case anyone wants to continue to using it with newer kernels, consider this a heads up that work will be required to build it for 5.2.

cc: @euspectre

**Comment by euspectre** [comment]
Thanks for the info!
