### ISSUE TITLE
powerpc: support alternatives (aka feature fixups)

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#974]
As mentioned in #963, I think we have two gaps in powerpc support related to alternatives ("feature fixups"):

1) kpatch-build doesn't create .klp.arch sections
2) the kernel powerpc arch livepatch code doesn't read .klp.arch sections

At least in theory this means that if any of the feature fixup sections refers to a patched function, and the alternative original code has klp relas associated with it, code corruption may occur when the klp relas clobber the copied alternative replacement code, thinking that it's the alternative original code.

Phase 1 fix:
- For kernel versions which don't have livepatch-specific powerpc code (currently all kernel versions), kpatch-build needs to assert an error if it detects that one of the following sections refers to a patched function: __ftr_fixup, __mmu_ftr_fixup, __fw_ftr_fixup.

Phase 2 fix:
- The upstream kernel needs a powerpc implementation of arch_klp_init_object_loaded().
- kpatch-build needs to create klp.arch sections for powerpc for those kernel versions, instead of the phase 1 error

Phase 3 fix:
- Convince upstream that loading patches for modules which haven't been loaded yet is still a bad idea.  The easiest solution is just to modprobe all target modules before loading the patch.
- Remove all these .klp section hacks

**Comment by joe-lawrence** [comment]
The .klp arch sections are an interesting idea, but I wonder if they will be a never-ending source of weird bugs since they kind of violate a bunch of assumptions of ordinary module loading / symbol resolution.  Removing support for future modules would also simplify a bunch of callback and other core livepatch code as well.

**Comment by jpoimboe** [comment]
To see if this is more than a hypothetical issue, I looked at all C object files which use feature fixups, and there are only a handful of them for a RHEL8-based config on an upstream kernel:
```
# for i in `find . -name "*.o"`; do if eu-readelf -S $i |grep -q ftr_fixup; then if [[ -e ${i/\.o/.c} ]]; then echo $i; eu-readelf -S $i | grep ftr_fixup; fi; fi; done 
./arch/powerpc/kernel/dbell.o
[ 4] __ftr_fixup          PROGBITS     0000000000000000 00000398 00000090  0 A      0   0  8
[ 5] .rela__ftr_fixup     RELA         0000000000000000 00023738 00000120 24 I     30   4  8
./arch/powerpc/kernel/process.o
[45] __ftr_fixup          PROGBITS     0000000000000000 00003450 00000060  0 A      0   0  8
[46] .rela__ftr_fixup     RELA         0000000000000000 0004f228 000000c0 24 I     123  45  8
./arch/powerpc/mm/book3s64/hash_native.o
[ 6] __ftr_fixup          PROGBITS     0000000000000000 00002fc8 00000660  0 A      0   0  8
[ 7] .rela__ftr_fixup     RELA         0000000000000000 0003e018 00000cc0 24 I     39   6  8
./arch/powerpc/platforms/powernv/idle.o
[15] __ftr_fixup          PROGBITS     0000000000000000 00002680 00000030  0 A      0   0  8
[16] .rela__ftr_fixup     RELA         0000000000000000 0002fc88 00000060 24 I     58  15  8
```
And going through them manually, none of them appear to rely on relocations.

So this appears to be a false alarm.  I think we are safe.  And we can probably get by without .klp.arch sections on powerpc.  (@kamalesh-babulal I can't remember if we talked about this previously)

But to be future-proof we should at least detect the usage of those sections in a patched function and error out in kpatch-build.

I also discovered a few more related quirks:

a) fixup_lwsync_group_size() should return 8, not 4 (at least on upstream kernels).  I think it's a harmless bug though.

b) The powerpc fixup code to generate the addresses (and their corresponding relocations) in the `*_ftr_fixup` sections is a bit odd.  All the addresses are relative to the beginning of the fixup_entry struct, rather than to the offset in the struct where the pointer is stored.  This means that create-diff-object may need some hacks to properly convert the address.  For example:
```
struct fixup_entry {
        unsigned long   mask;
        unsigned long   value;
        long            start_off;
        long            end_off;
        long            alt_start_off;
        long            alt_end_off;
};

Relocation section '.rela__ftr_fixup' at offset 0x2fc88 contains 4 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000010  00010000002c R_PPC64_REL64     0000000000000000 .text + 1a0
000000000018  00010000002c R_PPC64_REL64     0000000000000000 .text + 1ac
000000000020  00080000002c R_PPC64_REL64     0000000000000000 __ftr_alt_97 + 20
000000000028  00080000002c R_PPC64_REL64     0000000000000000 __ftr_alt_97 + 2c
```
The first relocation refers to start_off.  Because start_off is 16 bytes into the structure, 16 bytes needs to be subtracted from the relocation value.  So the start address of the original code is `.text +0x1a0 - 0x10`.

**Comment by jpoimboe** [comment]
c) create-diff-object is missing __barrier_nospec_fixup special section support

**Comment by jpoimboe** [comment]
> The .klp arch sections are an interesting idea, but I wonder if they will be a never-ending source of weird bugs since they kind of violate a bunch of assumptions of ordinary module loading / symbol resolution. Removing support for future modules would also simplify a bunch of callback and other core livepatch code as well.

Fully agreed.  When one of us gets the time, it might be useful to post an RFC livepatch patch upstream to show all the complex code we can remove.

**Comment by kamalesh-babulal** [comment]
>  (@kamalesh-babulal I can't remember if we talked about this previously)

@jpoimboe I too can't recall any discussion on the powerpc fixup code. To start with, I will post patches for the kpatch side todo list soon:
1. Implement phase 1 fix
2. Fix the powerpc quirks

**Comment by jpoimboe** [comment]
> And going through them manually, none of them appear to rely on relocations.
> 
> So this appears to be a false alarm. I think we are safe. And we can probably get by without .klp.arch sections on powerpc. (@kamalesh-babulal I can't remember if we talked about this previously)
> 
> But to be future-proof we should at least detect the usage of those sections in a patched function and error out in kpatch-build.

I now disagree with my past self here.  We have a recent patch which shows:
```
unsupported reference to special section __barrier_nospec_fixup
```
There's no real reason to enforce this, since as I said above, "we are safe".  And also we will eventually be getting rid of .klp.arch sections anyway, as discussed at LPC.  I will post a patch to remove 'unsupported' for these sections.
