### ISSUE TITLE
Support R_X86_64_PLT32 relocations

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#975]
Starting with binutils 2.31, the Linux kernel may have R_X86_64_PLT32 relocations.  Make sure we support them.  This should be as simple as treating R_X86_64_PLT32 exactly like R_X86_64_PC32 everywhere.  For more details see upstream commit torvalds/linux@b21ebf2fb4cde1618915a97cc773e287ff49173e.

**Comment by joe-lawrence** [comment]
Here's a list of R_X86_64_PLT32 generated when building a 4.19 kernel with binutils-2_31:  [R_X86_64_PLT32.txt](https://github.com/dynup/kpatch/files/3325512/R_X86_64_PLT32.txt).  In the interest of creating a test case, I'm not sure if any of those files are kpatch-able.  I'll try again with a full distro build and/or later binutils to see if I can generate any more useful R_X86_64_PLT32's.

**Comment by jpoimboe** [comment]
Hm, here's what I see with an upstream kernel based on the tip tree:
```
$ eu-readelf -a vmlinux.o |grep X86_64_PLT32 |wc -l
233928
```

**Comment by joe-lawrence** [comment]
I rebuilt binutils and ensured that it was in the path, this time I see lots more `X86_64_PLT32`... I might have not done a cleaned the kernel tree the first time and had old object files laying around.

**Comment by jpoimboe** [comment]
I see this on F29:
```
$ kpatch-build/kpatch-build -t vmlinux ./test/integration/fedora-27/convert-global-local.patch
Using cache at /home/jpoimboe/.kpatch/src
Testing patch file(s)
Reading special section data
Building original source
Building patched source
Extracting new and modified ELF sections
ERROR: slub.o: 1 function(s) can not be patched
slub.o: function __kmalloc has no fentry/mcount call, unable to patch
/home/jpoimboe/git/kpatch/kpatch-build/create-diff-object: unreconcilable difference
ERROR: 1 error(s) encountered. Check /home/jpoimboe/.kpatch/build.log for more details.
```
```
0000000000000000 <__kmalloc>:
   0:   e8 00 00 00 00          callq  5 <__kmalloc+0x5>
                        1: R_X86_64_PLT32       __fentry__-0x4
```
I'll work up a patch.
