### ISSUE TITLE
Rebase integration tests for CentOS-8

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#977]
CentOS-8 won't be coming out for a while, but we can rebase against the comparable RHEL-8 kernel for now.

**Comment by joe-lawrence** [comment]
It's been a [while](https://lists.centos.org/pipermail/centos-announce/2019-September/023449.html).  With 149ff8d1dc48 ("integration/centos-7: update tests to current kernel") we symlinked `centos-7` to `rhel-7.8`.  CentOS 8 is supposed to be flipping the dependency ordering, but should we just do apply the same linking to `rhel-8.2` ?  @sm00th

**Comment by sm00th** [comment]
Right. I believe it'll be the easiest way for centos8 as well. I'll post that. Do we want to maintain a vagrant image for centos8? With every PR now being tested on RHEL it doesn't add much value anymore in my opinion.

**Comment by joe-lawrence** [comment]
> Do we want to maintain a vagrant image for centos8? With every PR now being tested on RHEL it doesn't add much value anymore in my opinion.

Yeah, I agree.  I think the rhel-8 testing should cover that since they are effectively the same.

**Comment by joe-lawrence** [comment]
Fixed by PR #1132
