### ISSUE TITLE
kpatch.service and subsequent starts

### ISSUE THREAD

**Issue by joe-lawrence** [dynup/kpatch#979]
PR #972 modified the kpatch systemd service file to _not_ unload kpatch modules on service stop.  We did this so that kpatch modules would remain in place during system shutdown.

The systemd service may also stopped manually or in the case of a kpatch package upgrade.  A subsequent `systemctl start kpatch` would then fail as `kpatch --load-all` will trip over the still-loaded modules.

A few ways to work around this:

1. Enhance the kpatch.service script to detect this scenario
2. Enhance the kpatch script with a new option for this scenario
3. (My preferred) Enhance `kpatch --load-all` so that it doesn't "die" with failure over already-loaded modules.  Ideally it would simply skip over those and then continue trying to load any that aren't loaded yet.

Option 3 would change behavior of the kpatch script that other scripts may rely upon, so I'd like to make sure that won't break anything else before pursuing it.

**Comment by joe-lawrence** [comment]
#3 could be as simple as this (untested):
```diff
diff --git a/kpatch/kpatch b/kpatch/kpatch
index 328f1197259d..1343168e06a6 100755
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -314,7 +314,8 @@ load_module () {
                                die "error: cannot re-enable patch module $modname, cannot verify checksum match"
                        fi
                else
-                       die "error: module named $modname already loaded and enabled"
+                       warn "error: module named $modname already loaded and enabled"
+                       return 0
                fi
        fi
```
that would let load_module() complain about the already present module, but not fail on it.  The modprobe command already does something similar for the same scenario, sans msg:
```
% ls -d /sys/module/e1000e/
/sys/module/e1000e/
% modprobe e1000e
% echo $?
0
```

**Comment by sm00th** [comment]
Looks good. I *think* that if there are scripts relying on that they are likely to be used for testing.
