### ISSUE TITLE
Can not make patch object if you only modify the print content and the string is relocated by the .LC symbol.

### ISSUE THREAD

**Issue by BigSyke22** [dynup/kpatch#987]
If the string is relocated by the .LC symbol, the following code cannot find the string correctly：
rela->string = rela->sym->sec->data->d_buf + rela->addend;
I think it might be necessary to distinguish between relocating through .LC symbols or section symbols:
if (rela->sym->type == STT_SECTION)
    rela->string = rela->sym->sec->data->d_buf + rela->addend;
else
    rela->string = rela->sym->sec->data->d_buf + rela->sym->sym.st_value;
cuz  if the string is relocated by the .LC symbol the actual address of the string is the start address of the rodata section plus the value of the symbol.

**Comment by jpoimboe** [comment]
Hi @BigSyke22 , any chance you have a patch which triggers this problem?

**Comment by BigSyke22** [comment]
> 嗨@ BigSyke22，你有没有机会有一个补丁来触发这个问题？
Part of the code for the patch file is controlled by the company. I can't upload it directly. Maybe I can upload a sample that triggers this problem on weekends.
But this problem is easy to trigger. For example, by adding the -fPIC and -O2 parameters to the gcc of 5.4.0, the string will be relocated by the .LC symbol. The address of the string is the starting address of the section where the .LC symbol is located (ie the rodata section) plus the value of the .LC symbol.
When there is no such compilation parameter, the string is relocated by .rodata. The address of the string is the address of the rodata segment plus rela->addend.
