### ISSUE TITLE
Sync ppc unit tests with x86

### ISSUE THREAD

**Issue by jpoimboe** [dynup/kpatch#991]
There are currently several more x86 unit tests than ppc.  We should try to sync them as much as possible.
```
[jump-label] ~/git/kpatch/test/unit/objs $ ls -l ppc64le/*ORIG.o |wc -l
19
[jump-label] ~/git/kpatch/test/unit/objs $ ls -l x86_64/*ORIG.o |wc -l
28
```

**Comment by sm00th** [comment]
Any reason to do that? Most of the unit-tests we have test architecture-independent code. Having other-arch versions would definitely not hurt and there is a chance we'll find something but doing this just to make the numbers equal should not be a priority and ppc unit-tests should focus on ppc-specific code.

**Comment by jpoimboe** [comment]
That's a good point.  However, just because the x86 tests mostly test arch-independent code doesn't mean they adequately test the other arches. 

ppc is sufficiently different, with its own set of quirks, that I think it really needs full unit test coverage on its own.  For example: it uses the TOC for relocations; it has a different set of special sections; it uses -O3 for RHEL 7/8.  Those things are all different in ppc, even for arch-independent code.  There are other differences as well.

Maybe this would be a good project for an intern or a new contributor.
